#
# $Id: Makefile,v 1.1 2005/08/31 11:21:11 mauriliolongo Exp $
#

ROOT = ../../../

C_SOURCES=\
	chartables.c \
	pcre_compile.c \
	pcre_config.c \
	pcre_dfa_exec.c \
	pcre_exec.c \
	pcre_fullinfo.c \
	pcre_get.c \
	pcre_globals.c \
	pcre_info.c \
	pcre_maketables.c \
	pcre_ord2utf8.c \
	pcre_printint.c \
	pcre_refcount.c \
	pcre_study.c \
	pcre_tables.c \
	pcre_try_flipped.c \
	pcre_ucp_findchar.c \
	pcre_valid_utf8.c \
	pcre_version.c \
	pcre_xclass.c \
	pcreposix.c 

LIBNAME=pcrepos

include $(TOP)$(ROOT)config/lib.cf
