RUNTIME NAMESPACE CL52

   EXTERNAL NAMESPACE MEMBER AADD
   EXTERNAL NAMESPACE MEMBER ABS
   EXTERNAL NAMESPACE MEMBER ACHOICE
   EXTERNAL NAMESPACE MEMBER ACLONE
   EXTERNAL NAMESPACE MEMBER ACOPY
   EXTERNAL NAMESPACE MEMBER ADEL
   EXTERNAL NAMESPACE MEMBER ADIR
   EXTERNAL NAMESPACE MEMBER AEVAL
   EXTERNAL NAMESPACE MEMBER AFIELDS
   EXTERNAL NAMESPACE MEMBER AFILL
   EXTERNAL NAMESPACE MEMBER AINS
   EXTERNAL NAMESPACE MEMBER ALERT
   EXTERNAL NAMESPACE MEMBER ALIAS
   EXTERNAL NAMESPACE MEMBER ALLTRIM
   EXTERNAL NAMESPACE MEMBER ALTD
   EXTERNAL NAMESPACE MEMBER ARRAY
   EXTERNAL NAMESPACE MEMBER ASC
   EXTERNAL NAMESPACE MEMBER ASCAN
   EXTERNAL NAMESPACE MEMBER ASIZE
   EXTERNAL NAMESPACE MEMBER ASORT
   EXTERNAL NAMESPACE MEMBER AT
   EXTERNAL NAMESPACE MEMBER ATAIL
   EXTERNAL NAMESPACE MEMBER BIN2I
   EXTERNAL NAMESPACE MEMBER BIN2L
   EXTERNAL NAMESPACE MEMBER BIN2W
   EXTERNAL NAMESPACE MEMBER BOF
   EXTERNAL NAMESPACE MEMBER BREAK
   EXTERNAL NAMESPACE MEMBER BROWSE
   EXTERNAL NAMESPACE MEMBER CDOW
   EXTERNAL NAMESPACE MEMBER CHR
   EXTERNAL NAMESPACE MEMBER CMONTH
   EXTERNAL NAMESPACE MEMBER COL
   EXTERNAL NAMESPACE MEMBER COLORSELECT
   EXTERNAL NAMESPACE MEMBER CTOD
   EXTERNAL NAMESPACE MEMBER CURDIR
   EXTERNAL NAMESPACE MEMBER DATE
   EXTERNAL NAMESPACE MEMBER DAY
   EXTERNAL NAMESPACE MEMBER DBAPPEND
   EXTERNAL NAMESPACE MEMBER DBCLEARFIL
   EXTERNAL NAMESPACE MEMBER DBCLEARIND
   EXTERNAL NAMESPACE MEMBER DBCLEARREL
   EXTERNAL NAMESPACE MEMBER DBCLOSEALL
   EXTERNAL NAMESPACE MEMBER DBCLOSEAREA
   EXTERNAL NAMESPACE MEMBER DBCOMMIT
   EXTERNAL NAMESPACE MEMBER DBCOMMITALL
   EXTERNAL NAMESPACE MEMBER DBCREATE
   EXTERNAL NAMESPACE MEMBER DBCREATEIND
   EXTERNAL NAMESPACE MEMBER DBDELETE
   EXTERNAL NAMESPACE MEMBER DBEDIT
   EXTERNAL NAMESPACE MEMBER DBEVAL
   EXTERNAL NAMESPACE MEMBER DBF
   EXTERNAL NAMESPACE MEMBER DBFILTER
   EXTERNAL NAMESPACE MEMBER DBGOBOTTOM
   EXTERNAL NAMESPACE MEMBER DBGOTO
   EXTERNAL NAMESPACE MEMBER DBGOTOP
   EXTERNAL NAMESPACE MEMBER DBRECALL
   EXTERNAL NAMESPACE MEMBER DBREINDEX
   EXTERNAL NAMESPACE MEMBER DBRELATION
   EXTERNAL NAMESPACE MEMBER DBRSELECT
   EXTERNAL NAMESPACE MEMBER DBSEEK
   EXTERNAL NAMESPACE MEMBER DBSELECTAR
   EXTERNAL NAMESPACE MEMBER DBSETDRIVER
   EXTERNAL NAMESPACE MEMBER DBSETFILTER
   EXTERNAL NAMESPACE MEMBER DBSETINDEX
   EXTERNAL NAMESPACE MEMBER DBSETORDER
   EXTERNAL NAMESPACE MEMBER DBSETRELAT
   EXTERNAL NAMESPACE MEMBER DBSKIP
   EXTERNAL NAMESPACE MEMBER DBSTRUCT
   EXTERNAL NAMESPACE MEMBER DBUNLOCK
   EXTERNAL NAMESPACE MEMBER DBUNLOCKALL
   EXTERNAL NAMESPACE MEMBER DBUSEAREA
   EXTERNAL NAMESPACE MEMBER DELETED
   EXTERNAL NAMESPACE MEMBER DESCEND
   EXTERNAL NAMESPACE MEMBER DEVOUT
   EXTERNAL NAMESPACE MEMBER DEVOUTPICT
   EXTERNAL NAMESPACE MEMBER DEVPOS
   EXTERNAL NAMESPACE MEMBER DIRECTORY
   EXTERNAL NAMESPACE MEMBER DISKSPACE
   EXTERNAL NAMESPACE MEMBER DISPBEGIN
   EXTERNAL NAMESPACE MEMBER DISPBOX
   EXTERNAL NAMESPACE MEMBER DISPCOUNT
   EXTERNAL NAMESPACE MEMBER DISPEND
   EXTERNAL NAMESPACE MEMBER DISPOUT
   EXTERNAL NAMESPACE MEMBER DOSERROR
   EXTERNAL NAMESPACE MEMBER DOW
   EXTERNAL NAMESPACE MEMBER DTOC
   EXTERNAL NAMESPACE MEMBER DTOS
   EXTERNAL NAMESPACE MEMBER EMPTY
   EXTERNAL NAMESPACE MEMBER EOF
   EXTERNAL NAMESPACE MEMBER ERRORBLOCK
   EXTERNAL NAMESPACE MEMBER ERRORLEVEL
   EXTERNAL NAMESPACE MEMBER EVAL
   EXTERNAL NAMESPACE MEMBER EXP
   EXTERNAL NAMESPACE MEMBER FCLOSE
   EXTERNAL NAMESPACE MEMBER FCOUNT
   EXTERNAL NAMESPACE MEMBER FCREATE
   EXTERNAL NAMESPACE MEMBER FERASE
   EXTERNAL NAMESPACE MEMBER FERROR
   EXTERNAL NAMESPACE MEMBER FIELDBLOCK
   EXTERNAL NAMESPACE MEMBER FIELDGET
   EXTERNAL NAMESPACE MEMBER FIELDNAME
   EXTERNAL NAMESPACE MEMBER FIELDPOS
   EXTERNAL NAMESPACE MEMBER FIELDPUT
   EXTERNAL NAMESPACE MEMBER FIELDWBLOCK
   EXTERNAL NAMESPACE MEMBER FILE
   EXTERNAL NAMESPACE MEMBER FKLABEL
   EXTERNAL NAMESPACE MEMBER FKMAX
   EXTERNAL NAMESPACE MEMBER FLOCK
   EXTERNAL NAMESPACE MEMBER FOPEN
   EXTERNAL NAMESPACE MEMBER FOUND
   EXTERNAL NAMESPACE MEMBER FREAD
   EXTERNAL NAMESPACE MEMBER FREADSTR
   EXTERNAL NAMESPACE MEMBER FRENAME
   EXTERNAL NAMESPACE MEMBER FSEEK
   EXTERNAL NAMESPACE MEMBER FWRITE
   EXTERNAL NAMESPACE MEMBER GETENV
   EXTERNAL NAMESPACE MEMBER HARDCR
   EXTERNAL NAMESPACE MEMBER HEADER
   EXTERNAL NAMESPACE MEMBER I2BIN
   EXTERNAL NAMESPACE MEMBER IF
   EXTERNAL NAMESPACE MEMBER INDEXEXT
   EXTERNAL NAMESPACE MEMBER INDEXKEY
   EXTERNAL NAMESPACE MEMBER INDEXORD
   EXTERNAL NAMESPACE MEMBER INKEY
   EXTERNAL NAMESPACE MEMBER INT
   EXTERNAL NAMESPACE MEMBER ISALPHA
   EXTERNAL NAMESPACE MEMBER ISCOLOR
   EXTERNAL NAMESPACE MEMBER ISDIGIT
   EXTERNAL NAMESPACE MEMBER ISLOWER
   EXTERNAL NAMESPACE MEMBER ISPRINTER
   EXTERNAL NAMESPACE MEMBER ISUPPER
   EXTERNAL NAMESPACE MEMBER L2BIN
   EXTERNAL NAMESPACE MEMBER LASTKEY
   EXTERNAL NAMESPACE MEMBER LASTREC
   EXTERNAL NAMESPACE MEMBER LEFT
   EXTERNAL NAMESPACE MEMBER LEN
   EXTERNAL NAMESPACE MEMBER LOG
   EXTERNAL NAMESPACE MEMBER LOWER
   EXTERNAL NAMESPACE MEMBER LTRIM
   EXTERNAL NAMESPACE MEMBER LUPDATE
   EXTERNAL NAMESPACE MEMBER MAX
   EXTERNAL NAMESPACE MEMBER MAXCOL
   EXTERNAL NAMESPACE MEMBER MAXROW
   EXTERNAL NAMESPACE MEMBER MEMOEDIT
   EXTERNAL NAMESPACE MEMBER MEMOLINE
   EXTERNAL NAMESPACE MEMBER MEMOREAD
   EXTERNAL NAMESPACE MEMBER MEMORY
   EXTERNAL NAMESPACE MEMBER MEMOTRAN
   EXTERNAL NAMESPACE MEMBER MEMOWRIT
   EXTERNAL NAMESPACE MEMBER MEMVARBLOCK
   EXTERNAL NAMESPACE MEMBER MIN
   EXTERNAL NAMESPACE MEMBER MLCOUNT
   EXTERNAL NAMESPACE MEMBER MLCTOPOS
   EXTERNAL NAMESPACE MEMBER MLPOS
   EXTERNAL NAMESPACE MEMBER MOD
   EXTERNAL NAMESPACE MEMBER MONTH
   EXTERNAL NAMESPACE MEMBER MPOSTOLC
   EXTERNAL NAMESPACE MEMBER NETERR
   EXTERNAL NAMESPACE MEMBER NETNAME
   EXTERNAL NAMESPACE MEMBER NEXTKEY
   EXTERNAL NAMESPACE MEMBER NOSNOW
   EXTERNAL NAMESPACE MEMBER OS
   EXTERNAL NAMESPACE MEMBER OUTERR
   EXTERNAL NAMESPACE MEMBER OUTSTD
   EXTERNAL NAMESPACE MEMBER PAD
   EXTERNAL NAMESPACE MEMBER PCOL
   EXTERNAL NAMESPACE MEMBER PCOUNT
   EXTERNAL NAMESPACE MEMBER PROCLINE
   EXTERNAL NAMESPACE MEMBER PROCNAME
   EXTERNAL NAMESPACE MEMBER PROW
   EXTERNAL NAMESPACE MEMBER QOUT
   EXTERNAL NAMESPACE MEMBER RAT
   EXTERNAL NAMESPACE MEMBER READEXIT
   EXTERNAL NAMESPACE MEMBER READINSERT
   EXTERNAL NAMESPACE MEMBER READKEY
   EXTERNAL NAMESPACE MEMBER READMODAL
   EXTERNAL NAMESPACE MEMBER READVAR
   EXTERNAL NAMESPACE MEMBER RECCOUNT
   EXTERNAL NAMESPACE MEMBER RECNO
   EXTERNAL NAMESPACE MEMBER RECSIZE
   EXTERNAL NAMESPACE MEMBER REPLICATE
   EXTERNAL NAMESPACE MEMBER RESTSCREEN
   EXTERNAL NAMESPACE MEMBER RIGHT
   EXTERNAL NAMESPACE MEMBER RLOCK
   EXTERNAL NAMESPACE MEMBER ROUND
   EXTERNAL NAMESPACE MEMBER ROW
   EXTERNAL NAMESPACE MEMBER RTRIM
   EXTERNAL NAMESPACE MEMBER SAVESCREEN
   EXTERNAL NAMESPACE MEMBER SCROLL
   EXTERNAL NAMESPACE MEMBER SECONDS
   EXTERNAL NAMESPACE MEMBER SELECT
   EXTERNAL NAMESPACE MEMBER SET
   EXTERNAL NAMESPACE MEMBER SETBLINK
   EXTERNAL NAMESPACE MEMBER SETCANCEL
   EXTERNAL NAMESPACE MEMBER SETCOLOR
   EXTERNAL NAMESPACE MEMBER SETCURSOR
   EXTERNAL NAMESPACE MEMBER SETKEY
   EXTERNAL NAMESPACE MEMBER SETMODE
   EXTERNAL NAMESPACE MEMBER SETPOS
   EXTERNAL NAMESPACE MEMBER SETPRC
   EXTERNAL NAMESPACE MEMBER SOUNDEX
   EXTERNAL NAMESPACE MEMBER SPACE
   EXTERNAL NAMESPACE MEMBER SQRT
   EXTERNAL NAMESPACE MEMBER STR
   EXTERNAL NAMESPACE MEMBER STRTRAN
   EXTERNAL NAMESPACE MEMBER STUFF
   EXTERNAL NAMESPACE MEMBER SUBSTR
   EXTERNAL NAMESPACE MEMBER TIME
   EXTERNAL NAMESPACE MEMBER TONE
   EXTERNAL NAMESPACE MEMBER TRANSFORM
   EXTERNAL NAMESPACE MEMBER TYPE
   EXTERNAL NAMESPACE MEMBER UPDATED
   EXTERNAL NAMESPACE MEMBER UPPER
   EXTERNAL NAMESPACE MEMBER USED
   EXTERNAL NAMESPACE MEMBER VAL
   EXTERNAL NAMESPACE MEMBER VALTYPE
   EXTERNAL NAMESPACE MEMBER VERSION
   EXTERNAL NAMESPACE MEMBER WORD
   EXTERNAL NAMESPACE MEMBER YEAR

END

RUNTIME NAMESPACE CL53

   EXTERNAL NAMESPACE MEMBER BLOBDIRECTEXP
   EXTERNAL NAMESPACE MEMBER BLOBDIRECTGET
   EXTERNAL NAMESPACE MEMBER BLOBDIRECTIMP
   EXTERNAL NAMESPACE MEMBER BLOBDIRECTPUT
   EXTERNAL NAMESPACE MEMBER BLOBEXPORT
   EXTERNAL NAMESPACE MEMBER BLOBGET
   EXTERNAL NAMESPACE MEMBER BLOBIMPORT
   EXTERNAL NAMESPACE MEMBER BLOBROOTGET
   EXTERNAL NAMESPACE MEMBER BLOBROOTLOCK
   EXTERNAL NAMESPACE MEMBER BLOBROOTPUT
   EXTERNAL NAMESPACE MEMBER BLOBROOTUNLOC

   EXTERNAL NAMESPACE MEMBER DBFIELDINFO
   EXTERNAL NAMESPACE MEMBER DBFILEGET
   EXTERNAL NAMESPACE MEMBER DBFILEPUT

   EXTERNAL NAMESPACE MEMBER DBINFO
   EXTERNAL NAMESPACE MEMBER DBORDERINFO

   EXTERNAL NAMESPACE MEMBER DBRECORDINFO

   EXTERNAL NAMESPACE MEMBER DBRLOCK
   EXTERNAL NAMESPACE MEMBER DBRLOCKLIST

   EXTERNAL NAMESPACE MEMBER DBRUNLOCK

   EXTERNAL NAMESPACE MEMBER DIRMAKE
   EXTERNAL NAMESPACE MEMBER DIRREMOVE
   EXTERNAL NAMESPACE MEMBER DISKCHANGE
   EXTERNAL NAMESPACE MEMBER DISKNAME

   //GBMPDISP
   //GBMPLOAD
   //GELLIPSE
   //GFNTERASE
   //GFNTLOAD
   //GFNTSET
   //GFRAME
   //GGETPIXEL
   //GLINE
   //GMODE
   //GPOLYGON
   //GPUTPIXEL
   //GRECT
   //GSETCLIP
   //GSETEXCL
   //GSETPAL
   //GWRITEAT

   EXTERNAL NAMESPACE MEMBER MDBLCLK

   EXTERNAL NAMESPACE MEMBER MEMOSETSUPER

   EXTERNAL NAMESPACE MEMBER MENUMODAL
   EXTERNAL NAMESPACE MEMBER MHIDE

   EXTERNAL NAMESPACE MEMBER MLEFTDOWN
   EXTERNAL NAMESPACE MEMBER MLPOS

   EXTERNAL NAMESPACE MEMBER MPRESENT
   EXTERNAL NAMESPACE MEMBER MRESTSTATE
   EXTERNAL NAMESPACE MEMBER MRIGHTDOWN
   EXTERNAL NAMESPACE MEMBER MROW
   EXTERNAL NAMESPACE MEMBER MSAVESTATE
   EXTERNAL NAMESPACE MEMBER MSETBOUNDS
   EXTERNAL NAMESPACE MEMBER MSETCLIP
   EXTERNAL NAMESPACE MEMBER MSETCURSOR
   EXTERNAL NAMESPACE MEMBER MSETPOS
   EXTERNAL NAMESPACE MEMBER MSHOW
   EXTERNAL NAMESPACE MEMBER MSTATE

   EXTERNAL NAMESPACE MEMBER ORDBAGEXT
   EXTERNAL NAMESPACE MEMBER ORDBAGNAME
   EXTERNAL NAMESPACE MEMBER ORDCOND
   EXTERNAL NAMESPACE MEMBER ORDCONDSET
   EXTERNAL NAMESPACE MEMBER ORDCREATE
   EXTERNAL NAMESPACE MEMBER ORDDESCEND
   EXTERNAL NAMESPACE MEMBER ORDDESTROY
   EXTERNAL NAMESPACE MEMBER ORDFOR
   EXTERNAL NAMESPACE MEMBER ORDISUNIQUE
   EXTERNAL NAMESPACE MEMBER ORDKEY
   EXTERNAL NAMESPACE MEMBER ORDKEYADD
   EXTERNAL NAMESPACE MEMBER ORDKEYCOUNT
   EXTERNAL NAMESPACE MEMBER ORDKEYDEL
   EXTERNAL NAMESPACE MEMBER ORDKEYGOTO
   EXTERNAL NAMESPACE MEMBER ORDKEYNO
   EXTERNAL NAMESPACE MEMBER ORDKEYVAL
   EXTERNAL NAMESPACE MEMBER ORDLISTADD
   EXTERNAL NAMESPACE MEMBER ORDLISTCLEAR
   EXTERNAL NAMESPACE MEMBER ORDLISTREBUI
   EXTERNAL NAMESPACE MEMBER ORDNAME
   EXTERNAL NAMESPACE MEMBER ORDNUMBER
   EXTERNAL NAMESPACE MEMBER ORDSCOPE
   EXTERNAL NAMESPACE MEMBER ORDSETFOCUS
   EXTERNAL NAMESPACE MEMBER ORDSETRELAT
   EXTERNAL NAMESPACE MEMBER ORDSKIPUNIQUE

   EXTERNAL NAMESPACE MEMBER RDDLIST
   EXTERNAL NAMESPACE MEMBER RDDNAME
   EXTERNAL NAMESPACE MEMBER RDDSETDEFAULT

   EXTERNAL NAMESPACE MEMBER READFORMAT

   EXTERNAL NAMESPACE MEMBER READKILL

   EXTERNAL NAMESPACE MEMBER READUPDATED
END

