#
# $Id: Makefile,v 1.1 2003/03/29 22:38:10 lculik Exp $
#

ROOT = ../../

C_SOURCES=\
	odbc.c \

PRG_SOURCES=\
	todbc.prg\
	browodbc.prg\
	hdo_odbc.prg

LIBNAME=hbodbc

include $(TOP)$(ROOT)config/lib.cf
