##################################
# $Id$
#
# Toplevel FreeImage makefile

all:
	make -C source
	#make -C test

clean:
	make -C source clean
	#make -C test clean
	rm -f lib/*.a


install:
	make -C source install
