#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../../

C_SOURCES = \
	blocksor.c \
	bzlib.c \
	compress.c \
	core.c \
	crctable.c \
	decompre.c \
	huffman.c \
	randtabl.c \

PRG_SOURCES= \


C_HEADERS=\

PRG_HEADERS=\
	hbbz2.ch

LIBNAME=hbbz2

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/header.cf
