#
# $Id: Makefile,v 1.2 2003/01/10 16:13:05 jonnymind Exp $
#

ROOT = ../../../

C_SOURCES=\
	dbfntx1.c \

PRG_SOURCES=\
	dbfntx0.prg \

ifeq ($(HB_MT),MT)
   LIBNAME=dbfntxmt
endif

LIBNAME=dbfntx

include $(TOP)$(ROOT)config/lib.cf
