#
# $Id: Makefile,v 1.4 2003/01/17 12:28:34 likewolf Exp $
#

ROOT = ../../../

C_SOURCES=\
	dbfntx1.c \

ifeq ($(HB_MT),MT)
   MT_LIBNAME=dbfntxmt
endif

LIBNAME=dbfntx

include $(TOP)$(ROOT)config/lib.cf
