##################################
# $Id: Makefile,v 1.1 2003/04/02 00:56:38 jonnymind Exp $
#
# Makefile for XWT GTK interface
#

TARGET=libxwt_gtk.a
CFLAGS+=-I. -I../include `pkg-config --cflags gtk+-2.0`

SOURCE_TYPE=c
XWT_INSTALL=../lib

include ../Rules.make
