
[\xharbour.com\xHarbour-OLEServer\source\OleWrap.prg]
MYC_FLAGS =
MYDEFINES =
MYPRG_FLAGS =

[\xharbour.com\xHarbour-OLEServer\source\TypeInfo.prg]
MYC_FLAGS =
MYDEFINES =
MYPRG_FLAGS =

[\xharbour.com\xHarbour-AxtiveX\TActiveX.prg]
MYC_FLAGS =
MYDEFINES =
MYPRG_FLAGS =

[\xharbour.com\IEGui\IEGui.prg]
MYC_FLAGS =
MYDEFINES =
MYPRG_FLAGS =

[\xharbour.com\xHarbour-OLEServer\source\OleCore.c]
MYC_FLAGS =
MYDEFINES =

[\xharbour.com\xHarbour-OLEServer\source\OleServer.c]
MYC_FLAGS =
MYDEFINES =

[\xharbour.com\xHarbour-OLEServer\source\TypeLib.c]
MYC_FLAGS =
MYDEFINES =

[\xharbour.com\xHarbour-AxtiveX\ActiveX.c]
MYC_FLAGS =
MYDEFINES =
