HB_INC_COMPILE=$(TOP)../include -I$(TOP)$(ROOT)include
ROOT=../../../

C_SOURCES=\
	_winbmp.c \
	_winbrsh.c \
	_wincall.c \
	_wincdlg.c \
	_winclpb.c \
	_wincomm.c \
	_wincret.c \
	_windate.c \
	_windc.c \
	_windir.c \
	_windlg.c \
	_windll.c \
	_windraw.c \
	_winfont.c \
	_wingdi.c \
	_winhead.c \
	_winicon.c \
	_winilst.c \
	_wininet.c \
	_winini.c \
	_winkbrd.c \
	_winlv.c \
	_winmain.c \
	_winmapi.c \
	_winmem.c \
	_winmenu.c \
	_winmeta.c \
	_winmisc.c \
	_winmmcap.c \
	_winmous.c \
	_winmsg.c \
	_winpen.c \
	_winprn.c \
	_winrect.c \
	_winreg.c \
	_winrgn.c \
	_winscrlb.c \
	_winserial.c \
	_winshell.c \
	_winsock.c \
	_winsys.c \
	_wintab.c \
	_wintbar.c \
	_wintext.c \
	_wintree.c \
	_winview.c \
	_winwnd.c \

PRG_SOURCES=\
	debug.prg \
	errorsys.prg \
	whatutil.prg \
	wincdlg.prg \
	wincomm.prg \
	wincore.prg \
	winini.prg \
	winrbar.prg \
	wintabs.prg \
	wintbar.prg \

LIBNAME=what32

include $(TOP)$(ROOT)config/header.cf
INSTALL_RULE_HEADERS := $(INSTALL_RULE)
include $(TOP)$(ROOT)config/lib.cf
