[source\sql.y]

[source\sqlsrodbc.c]

[source\sqlconnection.prg]

[source\sqlrdd0.prg]

[source\sqlrdd2.prg]

[source\utils.prg]

[source\sqlgen1.prg]

[source\utilslang.prg]

[source\sqlmy.prg]

[source\ExprTransl.prg]

[source\ExprParser.prg]

[source\ExprSimpl.prg]

[source\ExprObjs.prg]

[source\ExprRelation.prg]

[source\ExprUDF.prg]

[source\sqlact.c]

[source\sqllex.c]

[source\mysql.c]

[source\sqlrdd1.c]

