#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../../

C_SOURCES = \
	xhbsqlite3.c \

PRG_SOURCES= \

C_HEADERS=\

PRG_HEADERS=\

LIBNAME=hbsqlite3

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/header.cf
