##################################
# $Id: Makefile,v 1.2 2003/03/22 03:29:19 gian Exp $
#
# Makefile for XWT Test program
#

TARGET=xwt_test
PRGFLAGS=-I../include 
LIBS=`pkg-config --libs gtk+-2.0` -L../lib -lxwt -lxwt_gtk -lxwt
include ../Rules.make
