##################################
# $Id: Makefile.linux,v 1.1 2003/11/28 14:46:34 lf_sfnet Exp $
#
# Makefile for XWT Test program
#


PRGFLAGS=-I../include
LIBS=`pkg-config --libs gtk+-2.0` -L../lib -lxwt -lxwt_gtk -lxwt

TARGETS=t_browse xwt_test
include ../Rules.make
