#
# $Id: makefile.bc,v 1.1 2003/02/22 21:26:52 jonnymind Exp $
#

#
# Makefile for XWT_TEST for Borland C/C++ 3.x, 4.x, 5.x compilers
#
.autodepend

CC = bcc32
IL = implib
ID = impdef
# NOTE: Using TASM for some reason, this should be normally TASM32.
#       I'll leave it to TASM until a better solution is found
AS = tasm

TARGET_EXE=wndtest.exe

BIN_DIR = ..\..\..\bin
OBJ_DIR = obj
LIB_DIR = ..\..\..\lib

COMMON_LIB   = $(LIB_DIR)\common.lib
DBFCDX_LIB   = $(LIB_DIR)\dbfcdx.lib
DBFNTX_LIB   = $(LIB_DIR)\dbfntx.lib
DBFDBT_LIB   = $(LIB_DIR)\dbfdbt.lib
DEBUG_LIB    = $(LIB_DIR)\debug.lib
LANG_LIB     = $(LIB_DIR)\lang.lib
MACRO_LIB    = $(LIB_DIR)\macro.lib
NULSYS_LIB   = $(LIB_DIR)\nulsys.lib
PP_LIB       = $(LIB_DIR)\pp.lib
RDD_LIB      = $(LIB_DIR)\rdd.lib
RTL_LIB      = $(LIB_DIR)\rtl.lib
VM_LIB       = $(LIB_DIR)\vm.lib
GTWIN_LIB    = $(LIB_DIR)\gtwin.lib
XWT_LIB      = $(LIB_DIR)\xwt.lib
HB_GT_LIB    = $(GTWIN_LIB)



#
# Directory macros. These should never have to change.
#

INCLUDE_DIR  = ..\..\..\include;..\include
WINSYS_DIR   = \WINDOWS\SYSTEM
CFLAGS       = -I$(INCLUDE_DIR) -d $(C_USR) $(CFLAGS)  -DWIN32
CLIBFLAGS    = $(CFLAGS)
HARBOUR_EXE  = $(BIN_DIR)\harbour.exe
HARBOURFLAGS = -i$(INCLUDE_DIR) -n -q0 -w -es2  -gc0 $(PRG_USR) $(HARBOURFLAGS)
LDFLAGS      = $(LDFLAGS)

#
# Macros to access our library names
#


TARGET_OBJS=\
   $(OBJ_DIR)\wndtest.obj

all: $(TARGET_EXE)

$(TARGET_EXE) : $(TARGET_OBJS)
   echo. $(CFLAGS)  > make.tmp
   echo. -M -e$(TARGET_EXE) >> make.tmp
   echo. -I$(INCLUDE_DIR) >> make.tmp
   echo. $(OBJ_DIR)\wndtest.obj >> make.tmp
   echo. $(PP_LIB) >> make.tmp
   echo. $(COMMON_LIB) >> make.tmp
   echo. $(VM_LIB) >> make.tmp
   echo. $(RTL_LIB) >> make.tmp
   echo. $(HB_GT_LIB) >> make.tmp
   echo. $(LANG_LIB) >> make.tmp
   echo. $(RDD_LIB) >> make.tmp
   echo. $(MACRO_LIB) >> make.tmp
   echo. $(DBFNTX_LIB) >> make.tmp
   echo. $(DBFCDX_LIB) >> make.tmp
   echo. $(DBFDBT_LIB) >> make.tmp
   echo. $(XWT_LIB) >> make.tmp
   $(CC) @make.tmp
   del make.tmp

$(OBJ_DIR)\wndtest.c: wndtest.prg
   $(HARBOUR_EXE) $(HARBOURFLAGS) $** -o$@

$(OBJ_DIR)\wndtest.obj: $(OBJ_DIR)\wndtest.c
   $(CC) -u -c $(CLIBFLAGS) -o$@ $**
