##################################
# $Id: Makefile,v 1.3 2003/11/08 00:45:56 jonnymind Exp $
#
# Makefile for XWT Test program
#

TARGET = xwt_test
SOURCES = xwt_test.prg

#TARGET = t_browse
#SOURCES = t_browse.prg

PRGFLAGS=-I../include
LIBS=-L../lib -lxwt -lxwt_gtk -lxwt `pkg-config --libs gtk+-2.0` 

include ../Rules.make
