#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../../

C_SOURCES =\
	jaricom.c \
	jcapimin.c \
	jcapistd.c \
	jcarith.c \
	jctrans.c \
	jcparam.c \
	jdatadst.c \
	jcinit.c \
	jmemansi.c \
	jcmaster.c \
	jcmarker.c \
	jcmainct.c \
	jcprepct.c \
	jccoefct.c \
	jccolor.c \
	jcsample.c \
	jchuff.c \
	jcdctmgr.c \
	jfdctfst.c \
	jfdctflt.c \
	jfdctint.c \
	jdapimin.c \
	jdapistd.c \
	jdtrans.c \
	jdatasrc.c \
	jdmaster.c \
	jdinput.c \
	jdmarker.c \
	jdhuff.c \
	jdmainct.c \
	jdcoefct.c \
	jdpostct.c \
	jddctmgr.c \
	jidctfst.c \
	jidctflt.c \
	jidctint.c \
	jdsample.c \
	jdcolor.c \
	jquant1.c \
	jquant2.c \
	jdmerge.c \
	jcomapi.c \
	jutils.c \
	jerror.c \
	jmemmgr.c \
	jdarith.c \
	cdjpeg.c \
	rdcolmap.c \
	wrbmp.c \
	wrgif.c \
	wrppm.c \
	wrtarga.c 



LIBNAME=jpeg

include $(TOP)$(ROOT)config/header.cf
INSTALL_RULE_HEADERS := $(INSTALL_RULE)
include $(TOP)$(ROOT)config/lib.cf

install::
	$(INSTALL_RULE_HEADERS)
