#
# $Id: makefile.nt,v 1.3 2003/09/25 14:24:52 paultucker Exp $
#

#
# Makefile.nt - This file is identical to makefile.vc, except that
# under something higher than Win9x, you should see overall improved
# speed of building Harbour.
#

#
# Makefile for Harbour Project for Microsoft Visual C (32 bit)
#

# ---------------------------------------------------------------
# If you need to set additional compiler/linker options use the
# environment variables below, but please DON'T MODIFY THIS FILE
# for this purpose.
# ---------------------------------------------------------------

#
# NOTE: You can use these envvars to configure the make process:
#       (note that these are all optional)
#
#       CFLAGS       - Extra C compiler options for libraries and for
#                      executables
#       CLIBFLAGS    - Extra C compiler options for the libraries
#       C_USR        - Extra C compiler options for libraries and for
#                      executables (GNU make compatible envvar)
#       HARBOURFLAGS - Extra Harbour compiler options
#       HB_DOC_PDF   - Turns on the .PDF file support in the HBDOC utility.
#                      Note that this will require the pdflib contrib.
#       HB_GT_LIB    - To override the default GT driver
#                      (search for HB_GT_LIBS for a list of values)
#       PRG_USR      - Extra Harbour compiler options
#                      (GNU make compatible envvar)
#

#
# Notes about this makefile:
#
# 1. To add new files to a dependancy list, add an obj name to one of the
#    OBJ lists for the appropriate library.
#    NOTE: put .prg related obj's last in the lib list.
#
# 2. This is a recursive script.  If you change the name of this file,
#    be sure to change MK_FILE (a few lines down) to the new name as well.
#
# 3. Recurrsion rules are quite simple:
#     If you specifiy /a on the command line, files in the obj\vc dir
#     will be deleted, and when nmake recurses, it's without the /a flag
#
#     If a .prg.obj rule is fired, nmake will execute this script with
#     a specific target as a parameter immediatley after compiling a given
#     set of prg files.
#      ie: Harbour $<
#          nmake /fmakefile.nt obj\vc\rtl.lib2
#     which will simply get make to re-evaluate the dependancy list for the
#     lib, and as a result, it will execute the C compiler using the .c.obj
#     rule below to create the obj's for the prg's that were created just
#     prior to the recurrsive call. Once the obj's are created, the
#     recurrsion is complete.
#     See additional notes under RTL.LIB below.
#

# ---------------------------------------------------------------
# "echo." intentionally used instead of "echo", to avoid conflicts
# with external commands named echo.
# using macros for ECHO and DEL to allow overiding such as:
#
#    set ECHO=cmd /c echo
#    set DEL=cmd /c del
#
# The above might be needed on Windows 2000 and XP.
# The macros are referenced in makefile.bc
# ---------------------------------------------------------------

!ifndef ECHO
# don't indent definitions
ECHO = echo.
!endif
!ifndef DEL
# You might need to set 'ECHO=echo.' - but don't set 'DEL=del.' !!!
DEL = del
!endif


MK_FILE      =makefile.nt
MK_FLAGS     =$(MAKEFLAGS: =)

BIN_DIR      =..\..\bin
LIB_DIR      =..\..\lib\vc
OBJ_DIR      =obj\vc

#
# Directory macros. These should never have to change.
#

INCLUDE_DIR  =include
SOURCE_DIR   =src
XWT_DIR      =$(SOURCE_DIR)\xwt_mfc # ??

#
# C compiler definition and C flags. These should never have to change.
#

AS           =ML
C_FLAGS      =-G6 -Ogtyb2 -FD -Gs -GA -TP -W3 -nologo -I$(INCLUDE_DIR) -I$(XWT_DIR) -I..\..\include -DHB_OS_WIN_32 -DSIMPLEX $(C_USR) $(CFLAGS)
CLIBFLAGS    =-c $(C_FLAGS) $(CLIBFLAGS)
HARBOURFLAGS =-i$(INCLUDE_DIR) -i..\..\include -n -q0 -w -es2 -gc0 $(PRG_USR) $(HARBOURFLAGS)
LFLAGS       =/MACHINE:IX86 /SUBSYSTEM:CONSOLE
L_DFLAGS     =$(LFLAGS) /NODEFAULTLIB:LIBCMT /NODEFAULTLIB:LIBCPMT $(LDFLAGS)

#
# Macros to access our library names
#

XWT_LIB =$(LIB_DIR)\xwt.lib

HARBOUR_EXE  =$(BIN_DIR)\harbour.exe

#
# Rules
#

.SUFFIXES: .prg .lib .c .obj .asm

# override builtin

.c.obj::
   $(CC) $(CLIBFLAGS) -Fo$(OBJ_DIR)$(MT)\ $<

.cpp.obj::
   $(CC) $(CLIBFLAGS) -Fo$(OBJ_DIR)$(MT)\ $<

#
#
#

# TODO: Add GTSLN and GTCRS

LIBLIST = \
   $(XWT_LIB)


#
# XWT.LIB rules
#
# how this works:
#
#  {target>.prg{objdir}.obj
#  Harbour (flags) -oobjdir\ $<
#    The list of dependant prgs is sent to the harbour compiler
#    Since the rule is .prg to .obj and the compiler spits out
#    C code (as we use it), we need to get those into obj format.
#    Since $(<:.prg=.c) doesn't work, we execute this script again
#    with a specific target via:
#  nMake /fmakefile.vc target.lib2
#    If you view that target at the bottom of this file, all it does
#    is cause make to evaluate the obj list of dependants which then
#    causes the .c.obj rule above to fire. (by inference)

{$(XWT_DIR)}.c{$(OBJ_DIR)}.obj::
   $(CC) $(CLIBFLAGS) -Fo$(OBJ_DIR)\ $<

{$(SOURCE_DIR)}.c{$(OBJ_DIR)}.obj::
   $(CC) $(CLIBFLAGS) -Fo$(OBJ_DIR)\ $<

{$(SOURCE_DIR)}.prg{$(OBJ_DIR)}.c::

{$(SOURCE_DIR)}.prg{$(OBJ_DIR)}.obj::
   $(HARBOUR_EXE) $(HARBOURFLAGS) -o$(OBJ_DIR)\ $<
   $(MAKE) -nologo /$(MK_FLAGS)f$(MK_FILE) $(XWT_LIB)2

# List C modules first, then PRG modules

XWT_LIB_OBJS = \
   $(OBJ_DIR)\xwt_api.obj \
   \
   \
   $(OBJ_DIR)\button.obj \
   $(OBJ_DIR)\checkbox.obj \
   $(OBJ_DIR)\container.obj \
   $(OBJ_DIR)\event.obj \
   $(OBJ_DIR)\filesel.obj \
   $(OBJ_DIR)\fontsel.obj \
   $(OBJ_DIR)\framewindow.obj \
   $(OBJ_DIR)\grid.obj \
   $(OBJ_DIR)\hex.obj \
   $(OBJ_DIR)\image.obj \
   $(OBJ_DIR)\inputmask.obj \
   $(OBJ_DIR)\label.obj \
   $(OBJ_DIR)\laycontainer.obj \
   $(OBJ_DIR)\layout.obj \
   $(OBJ_DIR)\menu.obj \
   $(OBJ_DIR)\menuitem.obj \
   $(OBJ_DIR)\msgbox.obj \
   $(OBJ_DIR)\pane.obj \
   $(OBJ_DIR)\radiobutton.obj \
   $(OBJ_DIR)\splitter.obj \
   $(OBJ_DIR)\textbox.obj \
   $(OBJ_DIR)\togglebutton.obj \
   $(OBJ_DIR)\treeitem.obj \
   $(OBJ_DIR)\treelist.obj \
   $(OBJ_DIR)\viewport.obj \
   $(OBJ_DIR)\widget.obj \
   $(OBJ_DIR)\window.obj

#
# Our default target
#
TARGETS= \
   $(XWT_LIB)

!if ( "$(MK_FLAGS:Y=)"=="A" )

all: \
   CLEAN \
   $(TARGETS)

MK_FLAGS = $(MK_FLAGS:A=)

!else

all: \
   $(TARGETS)

!endif

CLEAN:
   -@if exist $(OBJ_DIR)\*.obj $(DEL) $(OBJ_DIR)\*.obj >nul
   -@if exist $(OBJ_DIR)\*.c $(DEL) $(OBJ_DIR)\*.c >nul
   -@if exist $(XWT_LIB) $(DEL) $(XWT_LIB) > nul


#
# Library dependencies and build rules
#

$(XWT_LIB) : $(XWT_LIB_OBJS)
   lib /out:$@ $**


# dummy targets used for prg to c creation

$(XWT_LIB)2    : $(XWT_LIB_OBJS)
