#define _DBNAME "_tst"
#define NREC 15
#include "ord.ch"
FIELD FNUM
function main()
local n, aDB
RDDSETDEFAULT("DBFCDX")
aeval(directory("./"+_DBNAME+".??x"),{|x|ferase(x[1])})
ferase("./"+_DBNAME+".dbf")
? "RDD: "+rddsetdefault()
? "creating databse and index..."
aDb:={{"FNUM", "N", 10, 0}}
dbcreate(_DBNAME, aDb)
use _DBNAME shared
for n:=1 to NREC
    dbappend()
    replace FNUM with int((n+2)/3)
next
INDEX on FNUM tag TG_N to _DBNAME
ORDSETFOCUS(1)

/*
SKIPTEST()
INKEY(0)

DBORDERINFO(DBOI_ISDESC,,,.T.)
SKIPTEST()
INKEY(0)

DBORDERINFO(DBOI_ISDESC,,,.F.)
DBORDERINFO(DBOI_UNIQUE,,,.T.)
SKIPTEST()
INKEY(0)

DBORDERINFO(DBOI_ISDESC,,,.T.)
SKIPTEST()
INKEY(0)
*/

?
? "ORDKEYGOTO TEST"
DBORDERINFO(DBOI_ISDESC,,,.F.)
DBORDERINFO(DBOI_UNIQUE,,,.F.)
SKIPTEST()
KEYGOTOTEST()
INKEY(0)

DBORDERINFO(DBOI_ISDESC,,,.T.)
SKIPTEST()
KEYGOTOTEST()
INKEY(0)

DBORDERINFO(DBOI_ISDESC,,,.F.)
DBORDERINFO(DBOI_UNIQUE,,,.T.)
SKIPTEST()
KEYGOTOTEST()
INKEY(0)

DBORDERINFO(DBOI_ISDESC,,,.T.)
SKIPTEST()
KEYGOTOTEST()
INKEY(0)



DBCLOSEAREA()
? "END OF TEST"
RETURN NIL

FUNCTION SKIPTEST()
? "UNIQUE FLAG:", DBORDERINFO(DBOI_UNIQUE), ", DESCEND FLAG:", DBORDERINFO(DBOI_ISDESC)
DBGOTOP()
? "[TOP]", "RECORD:", RECNO(), ", VAL:", FNUM, ORDKEYNO()
WHILE !EOF()
    ? "RECORD:", RECNO(), ", VAL:", FNUM, ORDKEYNO()
    DBSKIP()
ENDDO
? "[EOF]", "RECORD:", RECNO(), ", VAL:", FNUM, ORDKEYNO()
WHILE !BOF()
    ? "RECORD:", RECNO(), ", VAL:", FNUM, ORDKEYNO()
    DBSKIP(-1)
ENDDO
DBGOBOTTOM()
? "[BOTTOM]", "RECORD:", RECNO(), ", VAL:", FNUM, ORDKEYNO()
WHILE !BOF()
    ? "RECORD:", RECNO(), ", VAL:", FNUM, ORDKEYNO()
    DBSKIP(-1)
ENDDO
RETURN NIL

FUNCTION KEYGOTOTEST()
LOCAL i, n, nKeys:=ORDKEYCOUNT()
n:=int(log(nKeys)/log(10))+1
? "UNIQUE FLAG:", DBORDERINFO(DBOI_UNIQUE), ", DESCEND FLAG:", DBORDERINFO(DBOI_ISDESC)
for i:=0 to nKeys+1
    ? "ORDKEYGOTO("+str(i,n)+") => ", ORDKEYGOTO(i),;
      "RECORD:", RECNO(), ", VAL:", FNUM, ORDKEYNO()
NEXT
RETURN NIL
