#
# $Id: Makefile.base64test,v 1.1 2003/11/30 14:42:03 jonnymind Exp $
#

TARGET=timetest
INCLUDE=-I../include
LIBS=-lhbtip
LIBDIR=-L../
SOURCES=timetest.prg
HB_GT_LIB=gtcgi

#COMMANDS
include ../Rules.make

