#
# $Id: Makefile,v 1.5 2003/11/22 15:10:33 jonnymind Exp $
#

all:
	make -f Makefile.tiptest
	make -f Makefile.ftpadvtest
	make -f Makefile.httpadvtest
	make -f Makefile.base64test

clean:
	make -f Makefile.tiptest clean
	make -f Makefile.ftpadvtest clean
	make -f Makefile.httpadvtest clean
	make -f Makefile.base64test clean

