#
# $Id: Makefile,v 1.3 2003/11/14 12:01:53 jonnymind Exp $
#

all:
	make -f Makefile.tiptest
	make -f Makefile.ftpadvtest

clean:
	make -f Makefile.tiptest clean
	make -f Makefile.ftpadvtest clean
	
