#
# $Id: Makefile.ftpadvtest,v 1.1 2003/11/14 12:01:53 jonnymind Exp $
#

TARGET=base64test
INCLUDE=-I../include
LIBS=-lhbtip
LIBDIR=-L../
SOURCES=base64test.prg
HB_GT_LIB=gtcgi

#COMMANDS
include ../Rules.make

