#
# $Id: Makefile,v 1.4 2003/11/20 16:44:36 jonnymind Exp $
#

all:
	make -f Makefile.tiptest
	make -f Makefile.ftpadvtest
	make -f Makefile.httpadvtest

clean:
	make -f Makefile.tiptest clean
	make -f Makefile.ftpadvtest clean
	make -f Makefile.httpadvtest clean
	
