ECHO -----------
ECHO VC8 VERSION
ECHO -----------

set XHB_VC8=\xharbour
SET _XB_Compiler=vc8
SET _XB_NonDebug=-NoXbp
SET _XB_Debug=-NoXbp -Debug
SET _XB_Exe=%_XB_NonDebug%

SET _BUILD_MT=YES
SET _BUILD_DEBUG=NO

SET _BUILD_DEMO=NO
SET _BUILD_PERSONAL=NO
SET _BUILD_PROF=NO
SET _BUILD_XHB_EXE=NO
SET _BUILD_XHB_LIB=NO
SET _BUILD_XHB_DLL=NO
SET _BUILD_CORE=NO
SET _BUILD_XBUILD=NO
SET _BUILD_CONTRIB=NO
SET _BUILD_DMAIN_LIB=NO
SET _BUILD_VXHDLL=YES
SET _BUILD_HBZLIB=YES
SET _BUILD_XHBCOMM=YES
SET _BUILD_ADS=YES
SET _BUILD_BGD=YES
SET _BUILD_XDO_DLL=YES
SET _BUILD_IEGUI_LIB=NO
SET _BUILD_DBG_CLIENT=YES

SET _BUILD_TPROJECT_LIB=YES
SET _BUILD_XEDIT_LIB=YES

SET _BUILD_APOLLORDD=YES
SET _BUILD_WINAPI_LIB=YES
SET _BUILD_XBSCRIPT_LIB=YES
SET _BUILD_CT3COMM=YES
SET _BUILD_ACTIVEX=YES
SET _BUILD_RMDBFCDX=YES
SET _BUILD_WINCORE=YES
SET _BUILD_OLE=YES
SET _BUILD_SQLRDD=YES

SET _BUILD_XBUILDW_AS=EXE
SET _BUILD_VXH_AS=EXE
SET _BUILD_XEDITW_AS=DLL
SET _BUILD_XPROMPT_AS=DLL
SET _BUILD_XDEBUGW_AS=DLL


IF "%VC8_MT%"=="YES"           SET _BUILD_MT=YES
IF "%VC8_MT%"=="NO"            SET _BUILD_MT=NO

IF "%VC8_DEMO%"=="YES"         SET _BUILD_DEMO=YES
IF "%VC8_DEMO%"=="NO"          SET _BUILD_DEMO=NO

IF "%VC8_PERSONAL%"=="YES"     SET _BUILD_PERSONAL=YES
IF "%VC8_PERSONAL%"=="NO"      SET _BUILD_PERSONAL=NO

IF "%VC8_PROF%"=="YES"         SET _BUILD_PROF=YES
IF "%VC8_PROF%"=="NO"          SET _BUILD_PROF=NO

IF "%VC8_XHB_EXE%"=="YES"      SET _BUILD_XHB_EXE=YES
IF "%VC8_XHB_EXE%"=="NO"       SET _BUILD_XHB_EXE=NO

IF "%VC8_XHB_LIB%"=="YES"      SET _BUILD_XHB_LIB=YES
IF "%VC8_XHB_LIB%"=="NO"       SET _BUILD_XHB_LIB=NO

IF "%VC8_XHB_DLL%"=="YES"      SET _BUILD_XHB_DLL=YES
IF "%VC8_XHB_DLL%"=="NO"       SET _BUILD_XHB_DLL=NO

IF "%VC8_CORELIBS%"=="YES"     SET _BUILD_CORE=YES
IF "%VC8_CORELIBS%"=="NO"      SET _BUILD_CORE=NO

IF "%VC8_XBUILD%"=="YES"       SET _BUILD_XBUILD=YES
IF "%VC8_XBUILD%"=="NO"        SET _BUILD_XBUILD=NO

IF "%VC8_CONTRIB%"=="YES"      SET _BUILD_CONTRIB=YES
IF "%VC8_CONTRIB%"=="NO"       SET _BUILD_CONTRIB=NO

IF "%VC8_DMAIN_LIB%"=="YES"    SET _BUILD_DMAIN_LIB=YES
IF "%VC8_DMAIN_LIB%"=="NO"     SET _BUILD_DMAIN_LIB=NO

IF "%VC8_VXHDLL%"=="YES"       SET _BUILD_VXHDLL=YES
IF "%VC8_VXHDLL%"=="NO"        SET _BUILD_VXHDLL=NO

IF "%VC8_SQLRDD%"=="YES"       SET _BUILD_SQLRDD=YES
IF "%VC8_SQLRDD%"=="NO"        SET _BUILD_SQLRDD=NO

IF "%VC8_HBZLIB%"=="YES"       SET _BUILD_HBZLIB=YES
IF "%VC8_HBZLIB%"=="NO"        SET _BUILD_HBZLIB=NO

IF "%VC8_CT3COMM%"=="YES"      SET _BUILD_CT3COMM=YES
IF "%VC8_CT3COMM%"=="NO"       SET _BUILD_CT3COMM=NO

IF "%VC8_XHBCOMM%"=="YES"      SET _BUILD_XHBCOMM=YES
IF "%VC8_XHBCOMM%"=="NO"       SET _BUILD_XHBCOMM=NO

IF "%VC8_APOLLORDD%"=="YES"    SET _BUILD_APOLLORDD=YES
IF "%VC8_APOLLORDD%"=="NO"     SET _BUILD_APOLLORDD=NO

IF "%VC8_WINAPI_LIB%"=="YES"   SET _BUILD_WINAPI_LIB=YES
IF "%VC8_WINAPI_LIB%"=="NO"    SET _BUILD_WINAPI_LIB=NO

IF "%VC8_TPROJECT_LIB%"=="YES" SET _BUILD_TPROJECT_LIB=YES
IF "%VC8_TPROJECT_LIB%"=="NO"  SET _BUILD_TPROJECT_LIB=NO

IF "%VC8_XEDIT_LIB%"=="YES"    SET _BUILD_XEDIT_LIB=YES
IF "%VC8_XEDIT_LIB%"=="NO"     SET _BUILD_XEDIT_LIB=NO

IF "%VC8_XDO_DLL%"=="YES"      SET _BUILD_XDO_DLL=YES
IF "%VC8_XDO_DLL%"=="NO"       SET _BUILD_XDO_DLL=NO

IF "%VC8_IEGUI_LIB%"=="YES"    SET _BUILD_IEGUI_LIB=YES
IF "%VC8_IEGUI_LIB%"=="NO"     SET _BUILD_IEGUI_LIB=NO

IF "%VC8_DBG_CLIENT%"=="YES"   SET _BUILD_DBG_CLIENT=YES
IF "%VC8_DBG_CLIENT%"=="NO"    SET _BUILD_DBG_CLIENT=NO

IF "%VC8_BGD%"=="YES"          SET _BUILD_BGD=YES
IF "%VC8_BGD%"=="NO"           SET _BUILD_BGD=NO

IF "%VC8_XBSCRIPT_LIB%"=="YES" SET _BUILD_XBSCRIPT_LIB=YES
IF "%VC8_XBSCRIPT_LIB%"=="NO"  SET _BUILD_XBSCRIPT_LIB=NO

IF "%VC8_WINCORE%"=="YES"      SET _BUILD_WINCORE=YES
IF "%VC8_WINCORE%"=="NO"       SET _BUILD_WINCORE=NO

IF "%VC8_DEBUG%"=="YES"        SET _XB_Exe=%_XB_Debug%
IF "%VC8_DEBUG%"=="NO"         SET _XB_Exe=%_XB_NonDebug%
IF "%VC8_DEBUG%"=="YES"        SET _BUILD_DEBUG=YES
IF "%VC8_DEBUG%"=="NO"         SET _BUILD_DEBUG=NO
IF "%VC8_DEBUG%"=="NO"         SET _XB_Debug=%_XB_NonDebug%

IF "%VC8_XBUILDW_AS%"=="DLL"   SET _BUILD_XBUILDW_AS=DLL
IF "%VC8_XBUILDW_AS%"=="EXE"   SET _BUILD_XBUILDW_AS=EXE
IF "%VC8_XBUILDW_AS%"=="NONE"  SET _BUILD_XBUILDW_AS=NONE

IF "%VC8_VXH_AS%"=="DLL"       SET _BUILD_VXH_AS=DLL
IF "%VC8_VXH_AS%"=="EXE"       SET _BUILD_VXH_AS=EXE
IF "%VC8_VXH_AS%"=="NONE"      SET _BUILD_VXH_AS=NONE

IF "%VC8_XEDITW_AS%"=="DLL"    SET _BUILD_XEDITW_AS=DLL
IF "%VC8_XEDITW_AS%"=="EXE"    SET _BUILD_XEDITW_AS=EXE
IF "%VC8_XEDITW_AS%"=="NONE"   SET _BUILD_XEDITW_AS=NONE

IF "%VC8_XDEBUGW_AS%"=="DLL"   SET _BUILD_XDEBUGW_AS=DLL
IF "%VC8_XDEBUGW_AS%"=="EXE"   SET _BUILD_XDEBUGW_AS=EXE
IF "%VC8_XDEBUGW_AS%"=="NONE"  SET _BUILD_XDEBUGW_AS=NONE

IF "%VC8_XPROMPT_AS%"=="DLL"   SET _BUILD_XPROMPT_AS=DLL
IF "%VC8_XPROMPT_AS%"=="EXE"   SET _BUILD_XPROMPT_AS=EXE
IF "%VC8_XPROMPT_AS%"=="NONE"  SET _BUILD_XPROMPT_AS=NONE


SET _XHB_LIB=\xHB\lib\%_XB_Compiler%
SET _XHB_BIN=\xHB\bin\%_XB_Compiler%
SET _XHB_DLL=\xHB\dll\%_XB_Compiler%

ECHO ON
