/* 
* Utility to transform txt files generated by outputtxt into 
* html/chm files. Html docs are customized for use on the 
* xhdn.xharbour.com website.
*
* example: txttohtm output\
* Transform all txt files from the output\ folder into html or
* chm files.
*/ 


#include "common.ch" 
#include "directry.ch"
#include "fileio.ch"

MEMVAR aIni
MEMVAR aFileNames 
MEMVAR aDocContent 
 
PROCEDURE Main(cSourceDir)
   // Description:
   // ... 

   // Variables: 
   LOCAL nStartTime := Seconds()
   LOCAL cPath := ""
   LOCAL aDocsContent := {}
   LOCAL aTempArray := {}
   LOCAL nCnt_1
   LOCAL nCnt_2 
   PUBLIC aIni := {}
   PUBLIC aFileNames := {} 

   // Code:
   // Define the type of output. Two possible types are: separate HTML files and a (compiled) CHM file. 
   IF Alert("Create separate HTML files or a CHM help document?", { "HTML", "CHM" } ) == 1 
      cPath := "Html\" 
   ELSE
      cPath := "Chm\" 
   ENDIF

   // Option to remove the previous generated files.
   IF Alert("Remove old files before processing?", { "Yes", "No" } ) == 1  
      IF Empty(Directory(cPath, "D"))
         DirMake(cPath) 
      ELSE
         ? "- Deleting previous files ..."
         nCnt_1 := LEN(Directory(cPath + "*.*")) 
         AEval(Directory(cPath + "*.*"), { |xFile| nCnt_1 += FErase(cPath + xFile[F_NAME]) })

         ? "-", AllTrim(Str(nCnt_1)), "files deleted" 
      ENDIF
   ENDIF

   // Load parameters for formatting etc. into the 'aIni' array.
   aIni := LoadIni()

   // Should the parameter 'cSourceDir' be empty, use the current directory as source.
   IF Empty(cSourceDir)
      cSourceDir := CurDir() 
   ENDIF
   cSourceDir += IIF(Right(cSourceDir, 1) = HB_OsPathSeparator(), "", HB_OsPathSeparator())

   // Read a txt file into an array and compose the HTML document. Add the return value of the function to the 'aTempArray' 
   // array. This array contains information about each HTML file (caption, filename, category, ...).  
   AEval(ComposeRecursive(cSourceDir), { |xFile| AAdd(aTempArray, TransformTxt(xFile, cPath)) })  

   // Reformat the temporary array into a more easy and flexible array.
   FOR nCnt_1 := 1 TO Len(aTempArray)
      FOR nCnt_2 := 1 TO Len(aTempArray[nCnt_1])
         AAdd(aDocsContent, { aTempArray[nCnt_1][nCnt_2][1], aTempArray[nCnt_1][nCnt_2][2], aTempArray[nCnt_1][nCnt_2][3], aTempArray[nCnt_1][nCnt_2][4] }) 
      NEXT
   NEXT

   // If the output format is CHM, compose the CHM indexes, content and project file. After composing the necessary files, the 
   // CHM file is compiled upon user request.
   IF cPath = "Chm\"
      ? "- Composing CHM indexes" 
      ComposeCHM(aDocsContent)
      ? "- Compiling CHM document"
      ? 
      CompileCHM(aDocsContent) 
   ENDIF

   // Display the amount of files processed and the total processing time.
   ? "-", AllTrim(Str(Len(Directory(cSourceDir + "*.txt")))), "files processed in", AllTrim(Str(Seconds() - nStartTime)), "seconds"
RETURN


FUNCTION ComposeRecursive(cPath)
   LOCAL aTxtFiles := {} 
   LOCAL aTempArray := {} 
   LOCAL aTxtFileList := {}
   LOCAL cnt_1 := 1
   LOCAL cnt_2:= 1 

   aTxtFiles := Directory(cPath + "*.*", "D")

   FOR cnt_1 := 1 TO Len(aTxtFiles)
      IF Left(aTxtFiles[cnt_1][1], 1) != "." .AND. "D" $ aTxtFiles[cnt_1][5]
         //AAdd(aTempArray, ComposeRecursive(cPath + aTxtFiles[cnt_1][1] + HB_OsPathSeparator()))
         aTempArray := ComposeRecursive(cPath + aTxtFiles[cnt_1][1] + HB_OsPathSeparator()) 
         FOR cnt_2 := 1 TO len(aTempArray) 
            AAdd(aTxtFileList, atemparray[cnt_2])
         NEXT cnt_2

      ELSEIF Lower(Right(aTxtFiles[cnt_1][1], 4)) = ".txt" 
         AAdd(aTxtFileList, cPath + aTxtFiles[cnt_1][1]) 
      ENDIF 
   NEXT cnt_1

RETURN aTxtFileList 
 

FUNCTION TransformTxt(cFile, cPath)
   // Description: 
   // Open a txt file, read the identifiers and their values into an array and compose a HTML file. The return value of the  
   // function is the same as the return value of the 'ComposeHTML' function. The value represents an array with information 
   // about all the HTML files created, based upon the single txt file.

   // Variables: 
   LOCAL nFileHandle
   LOCAL aDocsContent := {} 
   PUBLIC aDocContent := {}

   // Code:  
   nFileHandle := FOpen(AllTrim(cFile))
   IF nFileHandle < 0
      ? "- Error reading", cFile
      RETURN .F. 
   ELSE
      ? "- Processing:", cFile
   ENDIF
 
   // Read the identifiers and their value into an array
   aDocContent := ReadIdentifiersInArray(nFileHandle)
 
   // Compose the HTML/CHM files
   aDocsContent := ComposeHTML(aDocContent, cPath)
RETURN aDocsContent 


FUNCTION ComposeHTML(aDocContent, cPath)
   // Description: 
   // Compose an HTML file based on the 'aDocContent' array. This array contains all the identifiers and their values which 
   // were extracted from a single txt file by the 'ReadIdentifiersInArray' function. 

   // Variables: 
   LOCAL nCnt_1 := 1
   LOCAL nCnt_2 := 1
   LOCAL cTempString_1 := ""
   LOCAL oHtm
   LOCAL cCss
   LOCAL cBullet := "<strong>" + GetIniValue("BULLET") + "</strong> "
   LOCAL cFileName := "" 
   LOCAL aFunction := { {"Syntax", "syntax"}, {"Arguments", "arguments"}, {"Return value", "returns"}, ;
      {"Description", "description"}, {"Examples", "examples"}, {"Tests", "tests"}, {"Status", "status"}, ;
      {"Compliance", "compliance"}, {"Platforms", "platforms"}, {"Files", "files"}, {"See also", "seealso"} }
   LOCAL aCommand := aFunction
   LOCAL aStatement := aFunction
   LOCAL aOperator := { {"Syntax", "syntax"}, {"Operands", "operands"}, {"Description", "description"}, ;
      {"Examples", "examples"}, {"Tests", "tests"}, {"Status", "status"}, {"Compliance", "compliance"}, ;
      {"Platforms", "platforms"}, {"Files", "files"}, {"See also", "seealso"} }
   LOCAL aDocsContent := {} 
 
   // Code: 
   // Check to see if a stylesheet is used for the HTML files. 
   IF GetIniValue("STYLSHEET") = "YES"
      cCss := "<LINK REL='stylesheet' type='text/css' href='" + GetIniValue("STYLESHEETLOC") + "' />"
   ELSE
      cCSS := "<STYLE>body{font-family:" + GetIniValue("FONT") + ";font-size:" + GetIniValue("FONTSIZE") + ";}"
      cCss += ".Title{font-size:16px;font-weight:bold;}"
      cCss += ".Oneliner{font-style:" + IIF(GetIniValue("ONELINERITALIC") = "YES", "italic", "") + ";padding-bottom:10px;}"
      cCss += ".SubTitle{}" 
      cCss += ".Item{padding-left:10px;padding-bottom:4px;}</STYLE>"
   ENDIF

   // Depending on the type of document, sort the 'aDocContent' array. 
   IF AScan(aDocContent[1], { |x| x[2, 1] = "CLASS" }) <> 0
      ASort(aDocContent,,, { |x, y| x[2, 2] < y[2, 2] }) 
   ELSE
      ASort(aDocContent, 2,, { |x, y| x[3, 2] < y[3, 2] })
   ENDIF 

   DO WHILE nCnt_1 <= LEN(aDocContent) 
      // If the information in the 'aDocContent' array is about a function.
      IF Upper(aDocContent[nCnt_1][2, 1]) = "FUNCNAME" 
         cFileName := VerifyFileName("fun_" + Lower(StrTran(aDocContent[nCnt_1][2, 2], "<br>", "")), aFileNames) 
         AAdd(aFileNames, cFileName)
         oHtm := THTML():New(cPath + cFileName + ".htm")

         oHtm:WriteText("<TITLE>" + GetDocValue(nCnt_1, "FUNCNAME") + " (function)</TITLE>")
         oHtm:WriteText(cCss) 
         oHtm:WriteText("</HEAD><BODY>") 
         oHtm:WriteText("<div class='Title'>" + "Function " + GetDocValue(nCnt_1, "FUNCNAME") + "</div>") 
         oHtm:WriteText("<div class='Oneliner'>" + GetDocValue(nCnt_1, "ONELINER") + "</div>") 
         DO WHILE nCnt_2 <= LEN(aFunction)
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + aFunction[nCnt_2][1] + "</div>")  
            oHtm:WriteText("<div class='Item'>" + StrTran(GetDocValue(nCnt_1, aStatement[nCnt_2][2]), " ", "&nbsp;") + "</div>") 
            nCnt_2++
         END 
         nCnt_2 := 1

         oHtm:Close()
         AAdd(aDocsContent, { GetDocValue(nCnt_1, "FUNCNAME"), cFileName, GetDocValue(nCnt_1, "CATEGORY"), GetDocValue(nCnt_1, "EXTENSION")} )
      ENDIF
      
      // If the information in the 'aDocContent' array is about a command. 
      IF Upper(aDocContent[nCnt_1][2, 1]) = "COMMANDNAME"  
         cFileName := VerifyFileName("com_" + Lower(StrTran(aDocContent[nCnt_1][2, 2], "<br>", "")), aFileNames)  
         AAdd(aFileNames, cFileName)
         oHtm := THTML():New(cPath + cFileName + ".htm")

         oHtm:WriteText("<TITLE>" + GetDocValue(nCnt_1, "COMMANDNAME") + " (command)</TITLE>")
         oHtm:WriteText(cCss) 
         oHtm:WriteText("</HEAD><BODY>") 
         oHtm:WriteText("<div class='Title'>" + "Command " + GetDocValue(nCnt_1, "COMMANDNAME") + "</div>") 
         oHtm:WriteText("<div class='Oneliner'>" + GetDocValue(nCnt_1, "ONELINER") + "</div>") 
         DO WHILE nCnt_2 <= LEN(aCommand)
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + aCommand[nCnt_2][1] + "</div>")  
            oHtm:WriteText("<div class='Item'>" + StrTran(GetDocValue(nCnt_1, aStatement[nCnt_2][2]), " ", "&nbsp;") + "</div>") 
            nCnt_2++
         END 
         nCnt_2 := 1

         oHtm:Close()
         AAdd(aDocsContent, { GetDocValue(nCnt_1, "COMMANDNAME"), cFileName, GetDocValue(nCnt_1, "CATEGORY"), GetDocValue(nCnt_1, "EXTENSION")} ) 
      ENDIF

      // If the information in the 'aDocContent' array is about a statement. 
      IF Upper(aDocContent[nCnt_1][2, 1]) = "STATEMENT"  
         cFileName := VerifyFileName("stat_" + Lower(StrTran(aDocContent[nCnt_1][2, 2], "<br>", "")), aFileNames)  
         AAdd(aFileNames, cFileName)
         oHtm := THTML():New(cPath + cFileName + ".htm")

         oHtm:WriteText("<TITLE>" + GetDocValue(nCnt_1, "STATEMENT") + " (statement)</TITLE>")
         oHtm:WriteText(cCss) 
         oHtm:WriteText("</HEAD><BODY>") 
         oHtm:WriteText("<div class='Title'>" + "Statement " + GetDocValue(nCnt_1, "STATEMENT") + "</div>") 
         oHtm:WriteText("<div class='Oneliner'>" + GetDocValue(nCnt_1, "ONELINER") + "</div>") 
         DO WHILE nCnt_2 <= LEN(aStatement)
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + aStatement[nCnt_2][1] + "</div>")  
            oHtm:WriteText("<div class='Item'>" + StrTran(GetDocValue(nCnt_1, aStatement[nCnt_2][2]), " ", "&nbsp;") + "</div>") 
            nCnt_2++
         END 
         nCnt_2 := 1

         oHtm:Close()
         AAdd(aDocsContent, { GetDocValue(nCnt_1, "STATEMENT"), cFileName, GetDocValue(nCnt_1, "CATEGORY"), GetDocValue(nCnt_1, "EXTENSION")} ) 
      ENDIF

      // If the information in the 'aDocContent' array is about a operator. 
      IF Upper(aDocContent[nCnt_1][2, 1]) = "OPERATOR"  
         cFileName := VerifyFileName("oper_" + Lower(StrTran(aDocContent[nCnt_1][2, 2], "<br>", "")), aFileNames)  
         AAdd(aFileNames, cFileName)
         oHtm := THTML():New(cPath + cFileName + ".htm")

         oHtm:WriteText("<TITLE>" + GetDocValue(nCnt_1, "OPERATOR") + " (operator)</TITLE>")
         oHtm:WriteText(cCss) 
         oHtm:WriteText("</HEAD><BODY>") 
         oHtm:WriteText("<div class='Title'>" + "Operator " + GetDocValue(nCnt_1, "OPERATOR") + "</div>") 
         oHtm:WriteText("<div class='Oneliner'>" + GetDocValue(nCnt_1, "ONELINER") + "</div>") 
         DO WHILE nCnt_2 <= LEN(aOperator)
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + aOperator[nCnt_2][1] + "</div>")  
            oHtm:WriteText("<div class='Item'>" + StrTran(GetDocValue(nCnt_1, aStatement[nCnt_2][2]), " ", "&nbsp;") + "</div>") 
            nCnt_2++
         END 
         nCnt_2 := 1

         oHtm:Close()
         AAdd(aDocsContent, { GetDocValue(nCnt_1, "OPERATOR"), cFileName, GetDocValue(nCnt_1, "CATEGORY"), GetDocValue(nCnt_1, "EXTENSION")} )
      ENDIF

      // If the information in the 'aDocContent' array is about a class. 
      IF Upper(aDocContent[nCnt_1][2, 1]) = "CLASS"

         // The actual class 
         IF aDocContent[nCnt_1][3, 1] <> "METHOD" .AND. aDocContent[nCnt_1][3, 1] <> "DATA"
            cFileName := VerifyFileName("class_" + Lower(StrTran(aDocContent[nCnt_1][2, 2], "<br>", "")), aFileNames)  
            AAdd(aFileNames, cFileName)
            oHtm := THTML():New(cPath + cFileName + ".htm")
             
            oHtm:WriteText("<TITLE>" + GetDocValue(nCnt_1, "CLASS") + " (class)</TITLE>")
            oHtm:WriteText(cCss) 
            oHtm:WriteText("</HEAD><BODY>") 
            oHtm:WriteText("<div class='Title'>" + "Class " + GetDocValue(nCnt_1, "CLASS") + "</div>") 
            oHtm:WriteText("<div class='Oneliner'>" + GetDocValue(nCnt_1, "ONELINER") + "</div>") 
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Inherits" + "</div>")
            IF Lower(GetDocValue(nCnt_1, "INHERITS")) = "-" 
               oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "INHERITS") + "</div>") 
            ELSE
               IF cPath = "Html\" 
                  oHtm:WriteText("<div class='Item'><a href=" + Chr(34) + "javascript:loadintoiframe('myframe', 'class_" + Lower(GetDocValue(nCnt_1, "INHERITS")) + ".htm')" + Chr(34) + " target='_top'>" + GetDocValue(nCnt_1, "INHERITS") + "</a></div>")
               ELSE
                  oHtm:WriteText("<div class='Item'><a href='class_" + Lower(GetDocValue(nCnt_1, "INHERITS")) + ".htm' target='_self'>" + GetDocValue(nCnt_1, "INHERITS") + "</a></div>")
               ENDIF 
            ENDIF
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Constructor" + "</div>")
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "CONSTRUCTOR") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Syntax" + "</div>") 
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "SYNTAX") + "</div>") 
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Arguments" + "</div>")  
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "ARGUMENTS") + "</div>") 
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Return value" + "</div>")  
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "RETURNS") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Properties" + "</div>")
            FOR nCnt_2 := 1 TO Len(aDocContent) 
               IF aDocContent[nCnt_2][3, 1] = "DATA" .AND. IsUpper(aDocContent[nCnt_2][3, 2])
                  IF cPath = "Html\"  
                     oHtm:WriteText("<div class='Item'>&bull; <a href=" + Chr(34) + "javascript:loadintoiframe('myframe', '" + VerifyFileName(cFileName + "_p_" + Lower(StrTran(aDocContent[nCnt_2][3, 2], "<br>", "")), aFileNames) + ".htm')" + Chr(34) + " target='_top'>" + GetDocValue(nCnt_2, "DATA") + "</a></div>")
                  ELSE
                     oHtm:WriteText("<div class='Item'>&bull; <a href='" + VerifyFileName(cFileName + "_p_" + Lower(StrTran(aDocContent[nCnt_2][3, 2], "<br>", "")), aFileNames) + ".htm' target='_self'>" + GetDocValue(nCnt_2, "DATA") + "</a></div>")
                  ENDIF  
               ENDIF 
            NEXT
            IF GetDocValue(nCnt_1, "INHERITS") <> "-"
               cTempString_1 := Lower(GetDocValue(nCnt_1, "INHERITS")) 
               IF cPath = "Html\" 
                  oHtm:WriteText("<div class='Item'>&bull; <a href=" + Chr(34) + "javascript:loadintoiframe('myframe', 'class_" + cTempString_1 + ".htm')" + Chr(34) + " target='_top'>" + "Properties inherited by " + cTempString_1 + "</a></div>")    
               ELSE
                  oHtm:WriteText("<div class='Item'>&bull; <a href='class_" + cTempString_1 + ".htm' target='_self'>Properties inherited by " + cTempString_1 + "</a></div>")
               ENDIF 
            ENDIF 
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Methods" + "</div>") 
            FOR nCnt_2 := 1 TO Len(aDocContent)
               IF aDocContent[nCnt_2][3, 1] = "METHOD" .AND. IsUpper(aDocContent[nCnt_2][3, 2]) 
                  IF cPath = "Html\"  
                     oHtm:WriteText("<div class='Item'>&bull; <a href=" + Chr(34) + "javascript:loadintoiframe('myframe', '" + VerifyFileName(cFileName + "_m_" + Lower(StrTran(aDocContent[nCnt_2][3, 2], "<br>", "")), aFileNames) + ".htm')" + Chr(34) + " target='_top'>" + GetDocValue(nCnt_2, "METHOD") + "</a></div>")
                  ELSE
                     oHtm:WriteText("<div class='Item'>&bull; <a href='" + VerifyFileName(cFileName + "_m_" + Lower(StrTran(aDocContent[nCnt_2][3, 2], "<br>", "")), aFileNames) + ".htm' target='_self'>" + GetDocValue(nCnt_2, "METHOD") + "</a></div>")
                  ENDIF    
               ENDIF 
            NEXT
            IF GetDocValue(nCnt_1, "INHERITS") <> "-"
               cTempString_1 := Lower(GetDocValue(nCnt_1, "INHERITS")) 
               IF cPath = "Html\" 
                  oHtm:WriteText("<div class='Item'>&bull; <a href=" + Chr(34) + "javascript:loadintoiframe('myframe', 'class_" + cTempString_1 + ".htm')" + Chr(34) + " target='_top'>" + "Methods inherited by " + cTempString_1 + "</a></div>")
               ELSE
                  oHtm:WriteText("<div class='Item'>&bull; <a href='class_" + cTempString_1 + ".htm' target='_self'>Methods inherited by " + cTempString_1 + "</a></div>")
               ENDIF 
            ENDIF 
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Category" + "</div>")   
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "CATEGORY") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "See also" + "</div>")   
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "SEEALSO") + "</div>")

            oHtm:Close()
            AAdd(aDocsContent, { GetDocValue(nCnt_1, "CLASS"), cFileName, GetDocValue(nCnt_1, "CATEGORY"), GetDocValue(nCnt_1, "EXTENSION")} ) 
         ENDIF

         // Methods inside the class 
         IF aDocContent[nCnt_1][3, 1] = "METHOD" .AND. IsUpper(aDocContent[nCnt_1][3, 2]) 
            cTempString_1 := VerifyFileName(cFileName + "_m_" + Lower(StrTran(aDocContent[nCnt_1][3, 2], "<br>", "")), aFileNames)
            AAdd(aFileNames, cTempString_1)
            oHtm := THTML():New(cPath + cTempString_1 + ".htm")

            oHtm:WriteText("<TITLE>" + GetDocValue(nCnt_1, "METHOD") + " (class method)</TITLE>") 
            oHtm:WriteText(cCss) 
            oHtm:WriteText("</HEAD><BODY>") 
            oHtm:WriteText("<div class='Title'>" + "Method " + GetDocValue(nCnt_1, "METHOD") + "</div>") 
            oHtm:WriteText("<div class='Oneliner'>" + GetDocValue(nCnt_1, "ONELINER") + "</div>") 
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Category" + "</div>")
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "CATGEGORY") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Scope" + "</div>")
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "SCOPE") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Syntax" + "</div>")
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "SYNTAX") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Arguments" + "</div>")
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "ARGUMENTS") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Return value" + "</div>")
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "RETURNS") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Description" + "</div>")
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "DESCRIPTION") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Examples" + "</div>")
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "EXAMPLES") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "See also" + "</div>") 
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "SEEALSO") + "</div>") 
             
            oHtm:Close()
            AAdd(aDocsContent, { GetDocValue(nCnt_1, "CLASS"), cTempString_1, "Method", GetDocValue(nCnt_1, "METHOD") })
         ENDIF

         // Properties inside the class 
         IF aDocContent[nCnt_1][3, 1] = "DATA" .AND. IsUpper(aDocContent[nCnt_1][3, 2]) 
            cTempString_1 := VerifyFileName(cFileName + "_p_" + Lower(StrTran(aDocContent[nCnt_1][3, 2], "<br>", "")), aFileNames) 
            Aadd(aFileNames, cTempString_1)
            oHtm := THTML():New(cPath + cTempString_1 + ".htm")

            oHtm:WriteText("<TITLE>" + GetDocValue(nCnt_1, "DATA") + " (class property)</TITLE>") 
            oHtm:WriteText(cCss) 
            oHtm:WriteText("</HEAD><BODY>") 
            oHtm:WriteText("<div class='Title'>" + "Property " + GetDocValue(nCnt_1, "DATA") + "</div>") 
            oHtm:WriteText("<div class='Oneliner'>" + GetDocValue(nCnt_1, "ONELINER") + "</div>") 
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Category" + "</div>") 
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "CATGEGORY") + "</div>") 
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Scope" + "</div>")
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "SCOPE") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "Description" + "</div>") 
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "DESCRIPTION") + "</div>")
            oHtm:WriteText("<div class='SubTitle'>" + cBullet + "See also" + "</div>") 
            oHtm:WriteText("<div class='Item'>" + GetDocValue(nCnt_1, "SEEALSO") + "</div>")
             
            oHtm:Close()
            AAdd(aDocsContent, { GetDocValue(nCnt_1, "CLASS"), cTempString_1, "Property", GetDocValue(nCnt_1, "DATA") }) 
         ENDIF 
      ENDIF

      nCnt_1 ++
   END
RETURN aDocsContent


FUNCTION ComposeCHM(aDocsContent)
   LOCAL oHtm
   LOCAL cCss
   LOCAL cBullet := "<strong>" + GetIniValue("BULLET") + "</strong> " 
   LOCAL nCnt_1 := 1
   LOCAL nCnt_2 := 1 
   LOCAL cTempString_1 
 
   // Check to see if a stylesheet is used for the HTML files.
   IF GetIniValue("STYLSHEET") = "YES" 
      cCss := "<LINK REL='stylesheet' type='text/css' href='" + GetIniValue("STYLESHEETLOC") + "' />"
   ELSE
      cCSS := "<STYLE>body{font-family:" + GetIniValue("FONT") + ";font-size:" + GetIniValue("FONTSIZE") + ";}"
      cCss += "a{text-decoration:none;}" 
      cCss += ".Title{font-size:16px;font-weight:bold;padding-bottom:6px;}"
      cCss += ".SubTitle{font-size:12px;font-weight:bold;}" 
      cCss += ".Item{padding-left:10px;padding-bottom:4px;}</STYLE>"
   ENDIF 

   // If no default page was defined, create a new. 
   IF Empty(GetIniValue("CHM_ROOT"))
      oHtm := THTML():New("Chm\xhdn_index.htm")
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_index.htm")
      oHtm:WriteText(MemoRead(GetIniValue("CHM_ROOT")))
      oHtm:Close()
   ENDIF

   IF Empty(GetIniValue("CHM_FUN_ROOT")) 
      oHtm := THTML():New("Chm\xhdn_fun_index.htm")
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_fun_index.htm")
      oHtm:WriteText(MemoRead(GetIniValue("CHM_FUN_ROOT")))
      oHtm:Close()
   ENDIF 

   IF Empty(GetIniValue("CHM_FUN_AL"))  
      oHtm := THTML():New("Chm\xhdn_fun_al_index.htm")
      oHtm:WriteText("<TITLE>xHDN - Function Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Functions</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) })  
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_" .AND. (aDocsContent[nCnt_1, 3] <> "WinAPI" .aND. aDocsContent[nCnt_1, 3] <> "WinXPAPI")
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF 
      NEXT 
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_fun_al_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_FUN_AL"))) 
      oHtm:Close() 
   ENDIF

   IF Empty(GetIniValue("CHM_FUN_CAT"))
      oHtm := THTML():New("Chm\xhdn_fun_cat_index.htm")
      oHtm:WriteText("<TITLE>xHDN - Function Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Functions</div>") 
      ASort(aDocsContent,,, { |x, y| Upper(Left(x[2], 3) + x[3] + x[1]) < Upper(Left(y[2], 3) + y[3] + y[1]) })
      cTempString_1 := "*****" 
      FOR nCnt_1 := 1 TO Len(aDocsContent) 
         IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_"
            IF cTempString_1 <> aDocsContent[nCnt_1, 3]
               cTempString_1 := aDocsContent[nCnt_1, 3]
               oHtm:WriteText("<div class='SubTitle'>" + IIF(Empty(cTempString_1) .OR. cTempString_1 = "-", "Other", cTempString_1) + "</div>")
            ENDIF  
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_fun_cat_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_FUN_CAT"))) 
      oHtm:Close() 
   ENDIF 

   IF Empty(GetIniValue("CHM_COM_ROOT"))  
      oHtm := THTML():New("Chm\xhdn_com_index.htm")
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_com_index.htm")
      oHtm:WriteText(MemoRead(GetIniValue("CHM_COM_ROOT")))
      oHtm:Close()
   ENDIF  

   IF Empty(GetIniValue("CHM_COM_AL"))  
      oHtm := THTML():New("Chm\xhdn_com_al_index.htm") 
      oHtm:WriteText("<TITLE>xHDN - Command Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Commands</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) })
      FOR nCnt_1 := 1 TO Len(aDocsContent) 
         IF Left(aDocsContent[nCnt_1, 2], 4) = "com_" 
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF 
      NEXT 
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_com_al_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_COM_AL"))) 
      oHtm:Close() 
   ENDIF 

   IF Empty(GetIniValue("CHM_COM_CAT"))   
      oHtm := THTML():New("Chm\xhdn_com_cat_index.htm") 
      oHtm:WriteText("<TITLE>xHDN - Command Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Commands</div>") 
      ASort(aDocsContent,,, { |x, y| Upper(Left(x[2], 3) + x[3] + x[1]) < Upper(Left(y[2], 3) + y[3] + y[1]) })
      cTempString_1 := "*****" 
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 4) = "com_" 
            IF cTempString_1 <> aDocsContent[nCnt_1, 3]
               cTempString_1 := aDocsContent[nCnt_1, 3]
               oHtm:WriteText("<div class='SubTitle'>" + IIF(Empty(cTempString_1) .OR. cTempString_1 = "-", "Other", cTempString_1) + "</div>") 
            ENDIF 
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT 
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_com_cat_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_COM_CAT"))) 
      oHtm:Close() 
   ENDIF 

   IF Empty(GetIniValue("CHM_CLASSES_ROOT"))      
      oHtm := THTML():New("Chm\xhdn_classes_index.htm")   
      oHtm:WriteText("<TITLE>xHDN - xHarbour Classes Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Classes</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) }) 
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 6) = "class_" .AND. !("VISUAL XHARBOUR GUI LIBRARY" $ Upper(aDocsContent[nCnt_1, 3])) .AND. (aDocsContent[nCnt_1, 3] <> "Property" .AND. aDocsContent[nCnt_1, 3] <> "Method")  
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_classes_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_CLASSES_ROOT")))
      oHtm:Close() 
   ENDIF   

   IF Empty(GetIniValue("CHM_STAT_ROOT"))
      oHtm := THTML():New("Chm\xhdn_stat_index.htm")  
      oHtm:WriteText("<TITLE>xHDN - Statement Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Statements</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) }) 
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 5) = "stat_" 
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT 
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_stat_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_STAT_ROOT"))) 
      oHtm:Close()  
   ENDIF 

   IF Empty(GetIniValue("CHM_OPER_ROOT"))   
      oHtm := THTML():New("Chm\xhdn_oper_index.htm")   
      oHtm:WriteText("<TITLE>xHDN - Operator Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Operators</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) }) 
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 5) = "oper_" 
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT
       
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_oper_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_OPER_ROOT"))) 
      oHtm:Close() 
   ENDIF

   IF Empty(GetIniValue("CHM_RDD_ROOT"))      
      oHtm := THTML():New("Chm\xhdn_rdd_index.htm")   
      oHtm:WriteText("<TITLE>xHDN - RDD Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour RDD</div>")

      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_rdd_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_RDD_ROOT")))
      oHtm:Close() 
   ENDIF  

   IF Empty(GetIniValue("CHM_VCLASSES_ROOT"))      
      oHtm := THTML():New("Chm\xhdn_vclasses_index.htm")   
      oHtm:WriteText("<TITLE>xHDN - Visual xHarbour Classes Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>Visual xHarbour Classes</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) }) 
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 6) = "class_" .AND. ("VISUAL XHARBOUR GUI LIBRARY" $ Upper(aDocsContent[nCnt_1, 3]))
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_vclasses_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_VCLASSES_ROOT")))
      oHtm:Close() 
   ENDIF 

   IF Empty(GetIniValue("CHM_WINAPI_ROOT"))    
      oHtm := THTML():New("Chm\xhdn_winapi_index.htm")   
      oHtm:WriteText("<TITLE>xHDN - WinAPI Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour WinAPI</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) }) 
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_" .AND. (aDocsContent[nCnt_1, 3] = "WinAPI" .OR. aDocsContent[nCnt_1, 3] = "WinXPAPI")
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_winapi_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_WINAPI_ROOT"))) 
      oHtm:Close() 
   ENDIF

   IF Empty(GetIniValue("CHM_EX_ROOT"))   
      oHtm := THTML():New("Chm\xhdn_ex_index.htm")
      oHtm:WriteText("<TITLE>xHDN - Extensions Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Extensions</div>")
          
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_ex_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_EX_ROOT"))) 
      oHtm:Close() 
   ENDIF

   IF Empty(GetIniValue("CHM_FUNEX_ROOT"))  
      oHtm := THTML():New("Chm\xhdn_funex_index.htm")
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_funex_index.htm")
      oHtm:WriteText(MemoRead(GetIniValue("CHM_FUNEX_ROOT")))
      oHtm:Close()
   ENDIF  

   IF Empty(GetIniValue("CHM_FUNEX_AL"))  
      oHtm := THTML():New("Chm\xhdn_funex_al_index.htm")
      oHtm:WriteText("<TITLE>xHDN - Extended Function Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Extended Functions</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) })  
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES"  
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF 
      NEXT 
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_funex_al_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_FUNEX_AL"))) 
      oHtm:Close() 
   ENDIF

   IF Empty(GetIniValue("CHM_FUNEX_CAT"))
      oHtm := THTML():New("Chm\xhdn_funex_cat_index.htm")
      oHtm:WriteText("<TITLE>xHDN - Extended Function Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Extended Functions</div>") 
      ASort(aDocsContent,,, { |x, y| Upper(Left(x[2], 3) + x[3] + x[1]) < Upper(Left(y[2], 3) + y[3] + y[1]) })
      cTempString_1 := "*****" 
      FOR nCnt_1 := 1 TO Len(aDocsContent) 
         IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES"  
            IF cTempString_1 <> aDocsContent[nCnt_1, 3]
               cTempString_1 := aDocsContent[nCnt_1, 3]
               oHtm:WriteText("<div class='SubTitle'>" + IIF(Empty(cTempString_1) .OR. cTempString_1 = "-", "Other", cTempString_1) + "</div>")
            ENDIF  
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_funex_cat_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_FUNEX_CAT"))) 
      oHtm:Close() 
   ENDIF 

   IF Empty(GetIniValue("CHM_COMEX_ROOT"))  
      oHtm := THTML():New("Chm\xhdn_comex_index.htm")
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_comex_index.htm")
      oHtm:WriteText(MemoRead(GetIniValue("CHM_COMEX_ROOT")))
      oHtm:Close()
   ENDIF  

   IF Empty(GetIniValue("CHM_COMEX_AL"))  
      oHtm := THTML():New("Chm\xhdn_comex_al_index.htm") 
      oHtm:WriteText("<TITLE>xHDN - Extended Command Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Extended Commands</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) })
      FOR nCnt_1 := 1 TO Len(aDocsContent) 
         IF Left(aDocsContent[nCnt_1, 2], 4) = "com_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES" 
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF 
      NEXT 
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_comex_al_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_COMEX_AL"))) 
      oHtm:Close() 
   ENDIF 

   IF Empty(GetIniValue("CHM_COMEX_CAT"))   
      oHtm := THTML():New("Chm\xhdn_comex_cat_index.htm") 
      oHtm:WriteText("<TITLE>xHDN - Extended Command Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Extended Commands</div>") 
      ASort(aDocsContent,,, { |x, y| Upper(Left(x[2], 3) + x[3] + x[1]) < Upper(Left(y[2], 3) + y[3] + y[1]) })
      cTempString_1 := "*****" 
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 4) = "com_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES" 
            IF cTempString_1 <> aDocsContent[nCnt_1, 3]
               cTempString_1 := aDocsContent[nCnt_1, 3]
               oHtm:WriteText("<div class='SubTitle'>" + IIF(Empty(cTempString_1) .OR. cTempString_1 = "-", "Other", cTempString_1) + "</div>") 
            ENDIF 
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT 
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_comex_cat_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_COMEX_CAT"))) 
      oHtm:Close() 
   ENDIF

   IF Empty(GetIniValue("CHM_STATEX_ROOT")) 
      oHtm := THTML():New("Chm\xhdn_statex_index.htm")  
      oHtm:WriteText("<TITLE>xHDN - Extended Statement Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Extended Statements</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) }) 
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 5) = "stat_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES" 
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT 
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_statex_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_STATEX_ROOT"))) 
      oHtm:Close()  
   ENDIF 

   IF Empty(GetIniValue("CHM_OPEREX_ROOT"))   
      oHtm := THTML():New("Chm\xhdn_operex_index.htm")   
      oHtm:WriteText("<TITLE>xHDN - Extended Operator Overview</TITLE>") 
      oHtm:WriteText(cCss) 
      oHtm:WriteText("</HEAD><BODY>")
      oHtm:WriteText("<div class='Title'>xHarbour Extended Operators</div>")
      ASort(aDocsContent,,, { |x, y| Upper(AllTrim(x[1])) < Upper(AllTrim(y[1])) }) 
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         IF Left(aDocsContent[nCnt_1, 2], 5) = "oper_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES" 
            oHtm:WriteText("<div class='Item'>" + cBullet + " <a href='" + aDocsContent[nCnt_1, 2] +".htm' target='_self'>" + aDocsContent[nCnt_1, 1] + "</a></div>")
         ENDIF
      NEXT
       
      oHtm:Close()
   ELSE
      oHtm := THTML():New("Chm\xhdn_operex_index.htm") 
      oHtm:WriteText(MemoRead(GetIniValue("CHM_OPEREX_ROOT"))) 
      oHtm:Close() 
   ENDIF 
RETURN NIL


FUNCTION CompileCHM(aDocsContent) 
   LOCAL oHtm
   LOCAL nCnt_1 := 1
   LOCAL nCnt_2 := 1 
   LOCAL cTempString_1 := ""

   // Create the CHM project file with some parameters and a listing of al files inside the CHM file. 
   oHtm := FCreate("Chm\xHarbour.hhp")
   FWrite(oHtm, "[OPTIONS]" + Chr(13) + Chr(10))
   FWrite(oHtm, "Compatibility=1.1 or later" + Chr(13) + Chr(10))
   FWrite(oHtm, "Auto Index=Yes" + Chr(13) + Chr(10))
   FWrite(oHtm, "Full-text search=Yes" + Chr(13) + Chr(10))
   FWrite(oHtm, "Language=0x416 Português (brasileiro)" + Chr(13) + Chr(10) )
   FWrite(oHtm, "Contents file=.\" + "xHarbour.hhc" + Chr(13) + Chr(10) )
   FWrite(oHtm, "Compiled file=.\" + "xHarbour.chm" + Chr(13) + Chr(10) )
   FWrite(oHtm, "Display compile progress=No" + Chr(13) + Chr(10))
   FWrite(oHtm, "Default topic=xhdn_index.htm" + Chr(13) + Chr(10))
   FWrite(oHtm, "Index file=xHarbour.hhk" + Chr(13) + Chr(10)) 
   FWrite(oHtm, "[FILES]" + Chr(13) + Chr(10) )
   FOR nCnt_1 := 1 TO Len(aDocsContent)
      FWrite(oHtm, Lower(aDocsContent[nCnt_1, 2]) + ".htm" + Chr(13) + Chr(10))
   NEXT
   FClose(oHtm) 

   // Create the CHM index file. This file defines the lay-out and content of the Tree-View in the left side of the CHM file. 
   oHtm:=THTML():NewContent("Chm\xHarbour.hhk")
   oHtm:WriteText('<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">') 
   oHtm:WriteText('<HTML><HEAD><meta name="GENERATOR" content="Microsoft&reg; HTML Help Workshop 4.1">')
   oHtm:WriteText('<!-- Sitemap 1.0 --></HEAD><BODY>')
   oHtm:WriteText('<ul>')
      FOR nCnt_1 := 1 TO Len(aDocsContent)
         oHtm:Listitem()
         oHtm:AddObject("text/sitemap")
         oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
         oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
         oHtm:EndObject()
      NEXT
   oHtm:WriteText('</ul>')
   oHtm:Close() 

   oHtm:=THTML():NewContent("chm\xHarbour.hhc")  
   oHtm:WriteText('<!--Sitemap 1.0-->')
   oHtm:Addobject("text/site properties")
   oHtm:AddParam("FrameName","Ajuda")
   oHtm:EndObject()
   oHtm:WriteText("<ul>") 

      // xHarbour root 
      oHtm:ListItem() 
      oHtm:AddObject("text/sitemap")
      oHtm:AddParam("Name", "xHarbour Reference Guide")
      oHtm:AddParam("Local", "xhdn_index.htm")
      oHtm:EndObject()
      oHtm:WriteText("<ul>")

         // xHarbour functions
         oHtm:ListItem()     
         oHtm:AddObject("text/sitemap") 
         oHtm:AddParam("Name", "xHarbour Functions")
         oHtm:AddParam("Local", "xhdn_fun_index.htm") 
         oHtm:EndObject()
         oHtm:WriteText("<ul>")
            // xHarbour functions (alphabetical) 
            oHtm:ListItem()      
            oHtm:AddObject("text/sitemap") 
            oHtm:AddParam("Name", "Alphabetical")
            oHtm:AddParam("Local", "xhdn_fun_al_index.htm") 
            oHtm:EndObject()
            oHtm:WriteText("<ul>")
               ASort(aDocsContent,,, { |x, y| Upper(x[1]) < Upper(y[1]) }) 
               FOR nCnt_1 := 1 TO Len(aDocsContent)
                  IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_" .AND. !("WINAPI" $ Upper(aDocsContent[nCnt_1, 3])) .AND. !("WINXPAPI" $ Upper(aDocsContent[nCnt_1, 3])) 
                     oHtm:ListItem()       
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                  ENDIF 
               NEXT 
            oHtm:WriteText("</ul>")
            // xHarbour functions (categorical)
            oHtm:ListItem()      
            oHtm:AddObject("text/sitemap") 
            oHtm:AddParam("Name", "Categorical")
            oHtm:AddParam("Local", "xhdn_fun_cat_index.htm") 
            oHtm:EndObject() 
            oHtm:WriteText("<ul>")
               ASort(aDocsContent,,, { |x, y| Upper(x[3] + Upper(x[1])) < Upper(y[3] + Upper(y[1])) })  
               cTempString_1 := "*****" 
               FOR nCnt_1 := 1 TO Len(aDocsContent) 
                  IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_" .AND. (aDocsContent[nCnt_1, 3] <> "WinAPI" .AND. aDocsContent[nCnt_1, 3] <> "WinXPAPI")  
                     IF Upper(cTempString_1) <> Upper(aDocsContent[nCnt_1, 3])
                        IF cTempString_1 <> "*****"
                           oHtm:WriteText("</ul>") 
                        ENDIF 
                        oHtm:ListItem()
                        oHtm:AddObject("text/sitemap")
                        oHtm:AddParam("Name", IIF(Empty(aDocsContent[nCnt_1, 3]) .OR. aDocsContent[nCnt_1, 3] = "-", "Other", aDocsContent[nCnt_1, 3]) )
                        oHtm:AddParam("Local", "")
                        oHtm:EndObject() 
                        oHtm:WriteText("<ul>")
                        cTempString_1 := aDocsContent[nCnt_1, 3] 
                     ENDIF
                     oHtm:ListItem()       
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                  ENDIF 
               NEXT
               oHtm:WriteText("</ul>") 
            oHtm:WriteText("</ul>") 
         oHtm:WriteText("</ul>")

         // xHarbour Commands 
         oHtm:ListItem()      
         oHtm:AddObject("text/sitemap") 
         oHtm:AddParam("Name", "xHarbour Commands")
         oHtm:AddParam("Local", "xhdn_com_index.htm")
         oHtm:EndObject()
         oHtm:WriteText("<ul>")
            // xHarbour commands (alphabetical) 
            oHtm:ListItem()      
            oHtm:AddObject("text/sitemap") 
            oHtm:AddParam("Name", "Alphabetical")
            oHtm:AddParam("Local", "xhdn_com_al_index.htm")
            oHtm:EndObject()
            oHtm:WriteText("<ul>")
               ASort(aDocsContent,,, { |x, y| Upper(x[1]) < Upper(y[1]) }) 
               FOR nCnt_1 := 1 TO Len(aDocsContent)
                  IF Left(aDocsContent[nCnt_1, 2], 4) = "com_" 
                     oHtm:ListItem()       
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                  ENDIF 
               NEXT 
            oHtm:WriteText("</ul>")
            // xHarbour commands (categorical)
            oHtm:ListItem()      
            oHtm:AddObject("text/sitemap") 
            oHtm:AddParam("Name", "Categorical")
            oHtm:AddParam("Local", "xhdn_com_cat_index.htm")
            oHtm:EndObject() 
            oHtm:WriteText("<ul>")
               ASort(aDocsContent,,, { |x, y| Upper(x[3] + Upper(x[1])) < Upper(y[3] + Upper(y[1])) })
               cTempString_1 := "*****" 
               FOR nCnt_1 := 1 TO Len(aDocsContent) 
                  IF Left(aDocsContent[nCnt_1, 2], 4) = "com_"
                     IF Upper(cTempString_1) <> Upper(aDocsContent[nCnt_1, 3])
                        IF cTempString_1 <> "*****"
                           oHtm:WriteText("</ul>") 
                        ENDIF 
                        oHtm:ListItem()
                        oHtm:AddObject("text/sitemap")
                        oHtm:AddParam("Name", IIF(Empty(aDocsContent[nCnt_1, 3]) .OR. aDocsContent[nCnt_1, 3] = "-", "Other", aDocsContent[nCnt_1, 3]) )
                        oHtm:AddParam("Local", "")
                        oHtm:EndObject() 
                        oHtm:WriteText("<ul>")
                        cTempString_1 := aDocsContent[nCnt_1, 3]
                     ENDIF
                     oHtm:ListItem()       
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                  ENDIF
               NEXT
               oHtm:WriteText("</ul>") 
            oHtm:WriteText("</ul>")
         oHtm:WriteText("</ul>")

         // xHarbour Classes  
         oHtm:ListItem()     
         oHtm:AddObject("text/sitemap") 
         oHtm:AddParam("Name", "xHarbour Classes")
         oHtm:AddParam("Local", "xhdn_classes_index.htm") 
         oHtm:EndObject()
         oHtm:WriteText("<ul>")
            ASort(aDocsContent,,, { |x, y| Upper(x[1] + x[4]) < Upper(y[1] + y[4]) })  
               FOR nCnt_1 := 1 TO Len(aDocsContent)
               IF Left(aDocsContent[nCnt_1, 2], 6) = "class_" .AND. !("VISUAL XHARBOUR GUI LIBRARY" $ Upper(aDocsContent[nCnt_1, 3])) .AND. (aDocsContent[nCnt_1, 3] <> "Property" .AND. aDocsContent[nCnt_1, 3] <> "Method") 
                  oHtm:ListItem()       
                  oHtm:AddObject("text/sitemap") 
                  oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                  oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                  oHtm:EndObject()
                  oHtm:WriteText("<ul>")
                     // Properties  
                     oHtm:ListItem()         
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", "Properties")
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                     oHtm:WriteText("<ul>") 
                        FOR nCnt_2 := 1 TO Len(aDocsContent)
                           IF aDocsContent[nCnt_2, 1] = aDocsContent[nCnt_1, 1] .AND. aDocsContent[nCnt_2, 3] = "Property" .AND. IsUpper(aDocsContent[nCnt_2, 4]) 
                              oHtm:ListItem()        
                              oHtm:AddObject("text/sitemap") 
                              oHtm:AddParam("Name", aDocsContent[nCnt_2, 4])
                              oHtm:AddParam("Local", aDocsContent[nCnt_2, 2] + ".htm")
                              oHtm:EndObject()
                           ENDIF 
                        NEXT 
                     oHtm:WriteText("</ul>")

                     // Methods 
                     oHtm:ListItem()          
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", "Methods")
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                     oHtm:WriteText("<ul>") 
                        FOR nCnt_2 := 1 TO Len(aDocsContent)
                           IF aDocsContent[nCnt_2, 1] = aDocsContent[nCnt_1, 1] .AND. aDocsContent[nCnt_2, 3] = "Method" .AND. IsUpper(aDocsContent[nCnt_2, 4]) 
                              oHtm:ListItem()        
                              oHtm:AddObject("text/sitemap") 
                              oHtm:AddParam("Name", aDocsContent[nCnt_2, 4])
                              oHtm:AddParam("Local", aDocsContent[nCnt_2, 2] + ".htm")
                              oHtm:EndObject()
                           ENDIF 
                        NEXT 
                     oHtm:WriteText("</ul>")
                  oHtm:WriteText("</ul>") 
               ENDIF 
            NEXT  
         oHtm:WriteText("</ul>") 

         // xHarbour Statements  
         oHtm:ListItem()      
         oHtm:AddObject("text/sitemap") 
         oHtm:AddParam("Name", "xHarbour Statements")
         oHtm:AddParam("Local", "xhdn_stat_index.htm")
         oHtm:EndObject()
         oHtm:WriteText("<ul>")
            ASort(aDocsContent,,, { |x, y| Upper(x[1]) < Upper(y[1]) }) 
            FOR nCnt_1 := 1 TO Len(aDocsContent)
               IF Left(aDocsContent[nCnt_1, 2], 5) = "stat_" 
                  oHtm:ListItem()       
                  oHtm:AddObject("text/sitemap") 
                  oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                  oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                  oHtm:EndObject()
               ENDIF 
            NEXT 
         oHtm:WriteText("</ul>") 

         // xHarbour Operators 
         oHtm:ListItem()      
         oHtm:AddObject("text/sitemap") 
         oHtm:AddParam("Name", "xHarbour Operators")
         oHtm:AddParam("Local", "xhdn_oper_index.htm")
         oHtm:EndObject()
         oHtm:WriteText("<ul>")
            ASort(aDocsContent,,, { |x, y| Upper(x[1]) < Upper(y[1]) }) 
            FOR nCnt_1 := 1 TO Len(aDocsContent)
               IF Left(aDocsContent[nCnt_1, 2], 5) = "oper_" 
                  oHtm:ListItem()       
                  oHtm:AddObject("text/sitemap") 
                  oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                  oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                  oHtm:EndObject()
               ENDIF 
            NEXT 
         oHtm:WriteText("</ul>")

         // xHarbour RDD  
         oHtm:ListItem()      
         oHtm:AddObject("text/sitemap") 
         oHtm:AddParam("Name", "xHarbour RDD")
         oHtm:AddParam("Local", "xhdn_rdd_index.htm")
         oHtm:EndObject()
         oHtm:WriteText("<ul>")
         oHtm:WriteText("</ul>")  

         // Visual xHarbour Classes 
         oHtm:ListItem()     
         oHtm:AddObject("text/sitemap") 
         oHtm:AddParam("Name", "Visual xHarbour Classes")
         oHtm:AddParam("Local", "xhdn_vclasses_index.htm") 
         oHtm:EndObject()
         oHtm:WriteText("<ul>")
            ASort(aDocsContent,,, { |x, y| Upper(x[1] + x[4]) < Upper(y[1] + y[4]) })
               FOR nCnt_1 := 1 TO Len(aDocsContent)
               IF Left(aDocsContent[nCnt_1, 2], 6) = "class_" .AND. ("VISUAL XHARBOUR GUI LIBRARY" $ Upper(aDocsContent[nCnt_1, 3]))
                  oHtm:ListItem()       
                  oHtm:AddObject("text/sitemap") 
                  oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                  oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                  oHtm:EndObject()
                  oHtm:WriteText("<ul>")
                     // Properties 
                     oHtm:ListItem()         
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", "Properties")
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                     oHtm:WriteText("<ul>") 
                        FOR nCnt_2 := 1 TO Len(aDocsContent)
                           IF aDocsContent[nCnt_2, 1] = aDocsContent[nCnt_1, 1] .AND. aDocsContent[nCnt_2, 3] = "Property" .AND. IsUpper(aDocsContent[nCnt_2, 4]) 
                              oHtm:ListItem()        
                              oHtm:AddObject("text/sitemap") 
                              oHtm:AddParam("Name", aDocsContent[nCnt_2, 4])
                              oHtm:AddParam("Local", aDocsContent[nCnt_2, 2] + ".htm")
                              oHtm:EndObject()
                           ENDIF 
                        NEXT 
                     oHtm:WriteText("</ul>")

                     // Methods 
                     oHtm:ListItem()          
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", "Methods")
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                     oHtm:WriteText("<ul>") 
                        FOR nCnt_2 := 1 TO Len(aDocsContent)
                           IF aDocsContent[nCnt_2, 1] = aDocsContent[nCnt_1, 1] .AND. aDocsContent[nCnt_2, 3] = "Method" .AND. IsUpper(aDocsContent[nCnt_2, 4]) 
                              oHtm:ListItem()        
                              oHtm:AddObject("text/sitemap") 
                              oHtm:AddParam("Name", aDocsContent[nCnt_2, 4])
                              oHtm:AddParam("Local", aDocsContent[nCnt_2, 2] + ".htm")
                              oHtm:EndObject()
                           ENDIF 
                        NEXT 
                     oHtm:WriteText("</ul>")  
                  oHtm:WriteText("</ul>")
               ENDIF 
            NEXT  
         oHtm:WriteText("</ul>") 

         // Visual xHarbour WinAPI functions
         oHtm:ListItem()     
         oHtm:AddObject("text/sitemap") 
         oHtm:AddParam("Name", "Visual xHarbour WinAPI Functions")
         oHtm:AddParam("Local", "xhdn_winapi_index.htm") 
         oHtm:EndObject()
         oHtm:WriteText("<ul>")
            ASort(aDocsContent,,, { |x, y| Upper(x[1]) < Upper(y[1]) })  
               FOR nCnt_1 := 1 TO Len(aDocsContent)
               IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_" .AND. (aDocsContent[nCnt_1, 3] = "WinAPI" .OR. aDocsContent[nCnt_1, 3] ="WinXPAPI") 
                  oHtm:ListItem()       
                  oHtm:AddObject("text/sitemap") 
                  oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                  oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                  oHtm:EndObject()
               ENDIF 
            NEXT  
         oHtm:WriteText("</ul>")

         // xHarbour Extensions 
         oHtm:ListItem()     
         oHtm:AddObject("text/sitemap") 
         oHtm:AddParam("Name", "xHarbour Extensions")
         oHtm:AddParam("Local", "xhdn_ex_index.htm") 
         oHtm:EndObject()
         oHtm:WriteText("<ul>")
            // xHarbour functions 
            oHtm:ListItem()     
            oHtm:AddObject("text/sitemap") 
            oHtm:AddParam("Name", "xHarbour Functions")
            oHtm:AddParam("Local", "xhdn_funex_index.htm") 
            oHtm:EndObject()
            oHtm:WriteText("<ul>")
               // xHarbour functions (alphabetical) 
               oHtm:ListItem()      
               oHtm:AddObject("text/sitemap") 
               oHtm:AddParam("Name", "Alphabetical")
               oHtm:AddParam("Local", "xhdn_funex_al_index.htm")
               oHtm:EndObject()
               oHtm:WriteText("<ul>")
                  ASort(aDocsContent,,, { |x, y| Upper(x[1]) < Upper(y[1]) }) 
                  FOR nCnt_1 := 1 TO Len(aDocsContent)
                     IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_" .AND. (aDocsContent[nCnt_1, 2] <> "WinAPI" .AND. aDocsContent[nCnt_1, 2] <> "WinXPAPI") .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES"
                        oHtm:ListItem()       
                        oHtm:AddObject("text/sitemap") 
                        oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                        oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                        oHtm:EndObject()
                     ENDIF 
                  NEXT 
               oHtm:WriteText("</ul>")
               // xHarbour functions (categorical)
               oHtm:ListItem()      
               oHtm:AddObject("text/sitemap") 
               oHtm:AddParam("Name", "Categorical")
               oHtm:AddParam("Local", "xhdn_funex_cat_index.htm") 
               oHtm:EndObject() 
               oHtm:WriteText("<ul>")
                  ASort(aDocsContent,,, { |x, y| Upper(x[3] + Upper(x[1])) < Upper(y[3] + Upper(y[1])) })  
                  cTempString_1 := "*****" 
                  nCnt_2 := 0 
                  FOR nCnt_1 := 1 TO Len(aDocsContent) 
                     IF Left(aDocsContent[nCnt_1, 2], 4) = "fun_" .AND. (aDocsContent[nCnt_1, 3] <> "WinAPI" .AND. aDocsContent[nCnt_1, 3] <> "WinXPAPI") .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES" 
                        IF Upper(cTempString_1) <> Upper(aDocsContent[nCnt_1, 3])
                           IF cTempString_1 <> "*****"
                              oHtm:WriteText("</ul>") 
                           ENDIF 
                           oHtm:ListItem()
                           oHtm:AddObject("text/sitemap")
                           oHtm:AddParam("Name", IIF(Empty(aDocsContent[nCnt_1, 3]) .OR. aDocsContent[nCnt_1, 3] = "-", "Other", aDocsContent[nCnt_1, 3]) )
                           oHtm:AddParam("Local", "")
                           oHtm:EndObject() 
                           oHtm:WriteText("<ul>")
                           cTempString_1 := aDocsContent[nCnt_1, 3] 
                        ENDIF
                        oHtm:ListItem()       
                        oHtm:AddObject("text/sitemap") 
                        oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                        oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                        oHtm:EndObject()
                        nCnt_2++ 
                     ENDIF
                  NEXT
                  IF nCnt_2 <> 0  
                     oHtm:WriteText("</ul>")  
                  ENDIF 
               oHtm:WriteText("</ul>") 
            oHtm:WriteText("</ul>") 

            // xHarbour Commands  
            oHtm:ListItem()      
            oHtm:AddObject("text/sitemap") 
            oHtm:AddParam("Name", "xHarbour Commands")
            oHtm:AddParam("Local", "xhdn_comex_index.htm")
            oHtm:EndObject()
            oHtm:WriteText("<ul>")
               // xHarbour commands (alphabetical) 
               oHtm:ListItem()      
               oHtm:AddObject("text/sitemap") 
               oHtm:AddParam("Name", "Alphabetical")
               oHtm:AddParam("Local", "xhdn_comex_al_index.htm")
               oHtm:EndObject()
               oHtm:WriteText("<ul>")
                  ASort(aDocsContent,,, { |x, y| Upper(x[1]) < Upper(y[1]) }) 
                  FOR nCnt_1 := 1 TO Len(aDocsContent)
                     IF Left(aDocsContent[nCnt_1, 2], 4) = "com_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES" 
                        oHtm:ListItem()       
                        oHtm:AddObject("text/sitemap") 
                        oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                        oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                        oHtm:EndObject()
                     ENDIF 
                  NEXT 
               oHtm:WriteText("</ul>")
               // xHarbour commands (categorical) 
               oHtm:ListItem()      
               oHtm:AddObject("text/sitemap") 
               oHtm:AddParam("Name", "Categorical")
               oHtm:AddParam("Local", "xhdn_comex_cat_index.htm")
               oHtm:EndObject() 
               oHtm:WriteText("<ul>")
                  ASort(aDocsContent,,, { |x, y| Upper(x[3] + Upper(x[1])) < Upper(y[3] + Upper(y[1])) })
                  cTempString_1 := "*****"
                  nCnt_2 := 0
                  FOR nCnt_1 := 1 TO Len(aDocsContent) 
                     IF Left(aDocsContent[nCnt_1, 2], 4) = "com_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES"  
                        IF Upper(cTempString_1) <> Upper(aDocsContent[nCnt_1, 3])
                           IF cTempString_1 <> "*****"
                              oHtm:WriteText("</ul>") 
                           ENDIF 
                           oHtm:ListItem()
                           oHtm:AddObject("text/sitemap")
                           oHtm:AddParam("Name", IIF(Empty(aDocsContent[nCnt_1, 3]) .OR. aDocsContent[nCnt_1, 3] = "-", "Other", aDocsContent[nCnt_1, 3]) )
                           oHtm:AddParam("Local", "")
                           oHtm:EndObject() 
                           oHtm:WriteText("<ul>")
                           cTempString_1 := aDocsContent[nCnt_1, 3]
                        ENDIF
                        oHtm:ListItem()       
                        oHtm:AddObject("text/sitemap") 
                        oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                        oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                        oHtm:EndObject()
                        nCnt_2++ 
                     ENDIF 
                  NEXT
                  IF nCnt_2 <> 0   
                     oHtm:WriteText("</ul>")  
                  ENDIF 
               oHtm:WriteText("</ul>")
            oHtm:WriteText("</ul>") 

            // xHarbour Statements   
            oHtm:ListItem()      
            oHtm:AddObject("text/sitemap") 
            oHtm:AddParam("Name", "xHarbour Statements")
            oHtm:AddParam("Local", "xhdn_statex_index.htm")
            oHtm:EndObject()
            oHtm:WriteText("<ul>")
               ASort(aDocsContent,,, { |x, y| Upper(x[1]) < Upper(y[1]) }) 
               FOR nCnt_1 := 1 TO Len(aDocsContent)
                  IF Left(aDocsContent[nCnt_1, 2], 5) = "stat_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES" 
                     oHtm:ListItem()       
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                  ENDIF 
               NEXT 
            oHtm:WriteText("</ul>")  

            // xHarbour Operators  
            oHtm:ListItem()      
            oHtm:AddObject("text/sitemap") 
            oHtm:AddParam("Name", "xHarbour Operators")
            oHtm:AddParam("Local", "xhdn_operex_index.htm")
            oHtm:EndObject()
            oHtm:WriteText("<ul>")
               ASort(aDocsContent,,, { |x, y| Upper(x[1]) < Upper(y[1]) }) 
               FOR nCnt_1 := 1 TO Len(aDocsContent)
                  IF Left(aDocsContent[nCnt_1, 2], 5) = "oper_" .AND. Upper(aDocsContent[nCnt_1, 4]) = "YES" 
                     oHtm:ListItem()       
                     oHtm:AddObject("text/sitemap") 
                     oHtm:AddParam("Name", aDocsContent[nCnt_1, 1])
                     oHtm:AddParam("Local", aDocsContent[nCnt_1, 2] + ".htm")
                     oHtm:EndObject()
                  ENDIF 
               NEXT 
            oHtm:WriteText("</ul>")
   
            // xHarbour RDD  
            oHtm:ListItem()      
            oHtm:AddObject("text/sitemap") 
            oHtm:AddParam("Name", "xHarbour RDD")
            oHtm:AddParam("Local", "xhdn_rdd_index.htm")
            oHtm:EndObject()
            oHtm:WriteText("<ul>")
            oHtm:WriteText("</ul>") 
         oHtm:WriteText("</ul>")

      oHtm:WriteText("</ul>")
   oHtm:WriteText("</ul>")
   oHtm:Close() 

   // Request to compile the created files into one CHM helpfile.
   IF Alert("Compile the CHM file with HTML Help Workshop?", { "Yes", "No" } ) == 1   
      // To be improved: search for the hhc.exe file and if present start compilation   
      IF FILE("c:\program files\html help workshop\hhc.exe") 
         RUN "c:\program files\html help workshop\hhc" Chm\xHarbour.hhp
         CLEAR SCREEN
      ENDIF
   ENDIF
RETURN NIL 


FUNCTION ReadIdentifiersInArray(nFileHandle)  
   // Description:   
   // Read source files into the 'aCurDoc' array. This function was added by nick.van.dyck@xharbour.com 

   // Variables:  
   LOCAL cBuffer := "" 
   LOCAL aTempArray := {}
   LOCAL aDocContent := {} 
   LOCAL cIdentifierKey := ""
   LOCAL cIdentifierValue := ""
   LOCAL bDocMode := .F.
   LOCAL bIdentifierSwitch := .F. 

   // Code: 
   DO WHILE Empty(HB_FReadLine(nFileHandle, @cBuffer, {CHR(13) + CHR(10), CHR(10)})) 

      // Strip possible delimiters 
      IF AT(Chr(9), cBuffer) <> 0  
         cBuffer := RTrim(SubStr(cBuffer, 4, LEN(cBuffer) - 3)) 
      ELSE
         cBuffer := RTrim(SubStr(cBuffer, 5, LEN(cBuffer) - 4))
      ENDIF

      // Mark switch to indicate doc-mode 
      bDocMode := IIF(cBuffer = "$DOC$" .OR. cBuffer = "$CLASSDOC$" .OR. bDocMode = .T., .T., .F.)

      IF bDocMode = .T.
         IF Left(cBuffer, 1) = "$" .AND. Right(cBuffer, 1) = "$" .AND. Len(cBuffer) > 2 
            cIdentifierKey := SubStr(cBuffer, 2, LEN(cBuffer) - 2)
            cIdentifierValue  := "" 

            IF cIdentifierKey <> "END"
               AAdd(aTempArray, {cIdentifierKey, ""})
            ELSE
               AEval(aTempArray, { |x| x[2] := IIF(UPPER(RIGHT(x[2], 4)) = "<BR>", Left(x[2], Len(x[2]) - 4), x[2]) })
               AEval(aTempArray, { |x| x[2] := HtmlFormat(x[2]) }) 

               AAdd(aDocContent, aTempArray)
               bDocMode :=  .F.
               aTempArray := {}
            ENDIF   
         ELSEIF Empty(cBuffer) 
            cIdentifierValue = cIdentifierValue + "<br>"
            aTempArray[Len(aTempArray), 2] := cIdentifierValue
         ELSE
            cIdentifierValue = cIdentifierValue + cBuffer + "<br>"
            aTempArray[Len(aTempArray), 2] := cIdentifierValue
         ENDIF 
 
      ENDIF 

      cBuffer := "" 
   ENDDO
RETURN aDocContent 


FUNCTION GetDocValue(nSubDoc, cID)
   // Description: 
   // Read a value from the 'aDocContent' array. 

   // Variables: 
   LOCAL cDocValue := ""
   LOCAL nDocIndex := 0

   // Code: 
   nDocIndex := AScan(aDocContent[nSubDoc], { |x| UPPER(x[1]) = UPPER(cID) }, 2)
   IF nDocIndex > 0
      cDocValue := IIF(Empty(aDocContent[nSubDoc][nDocIndex, 2]), "-", aDocContent[nSubDoc][nDocIndex, 2])  
   ELSE
      cDocValue := "-"
   ENDIF 
RETURN cDocValue


FUNCTION LoadIni()
   // Description: 
   // Load values from the TxtToHtm.ini file into the 'aIni' array 

   // Variables: 
   LOCAL nFileHandle
   LOCAL cBuffer := ""
   LOCAL aIni := {} 

   // Code: 
   nFileHandle := FOpen("TxtToHtm.ini")

   IF nFileHandle < 0 
      ? "- Error loading TxtToHtm.ini" 
      RETURN .F. 
   ELSE
      DO WHILE Empty(HB_FReadLine(nFileHandle, @cBuffer, {CHR(13) + CHR(10), CHR(10)})) 
         AAdd(aIni, {SubStr(cBuffer, 2, AT("=", cBuffer) - 2), SubStr(cBuffer, AT("=", cBuffer) + 1, Len(cBuffer) - AT("=", cBuffer) - 1)}) 
         cBuffer := ""
      ENDDO  

      ? "- TxtToHtm.ini loaded"
   ENDIF 
RETURN aIni 


FUNCTION GetIniValue(cID)
   // Description: 
   // Read a value from the 'aIni' array. 

   // Variables:
   LOCAL cIniValue := ""                               // Temporary variable to store the ini value 
   LOCAL nIniIndex := 0                                // Temporary variable to store the index of the requested ini identifier 

   // Code: 
   nIniIndex := AScan(aIni, { |x| UPPER(x[1]) = UPPER(cID) })
   IF nIniIndex > 0
      cIniValue := aIni[nIniIndex, 2]
   ELSE
      cIniValue := ""
   ENDIF 
RETURN cIniValue


FUNCTION HtmlFormat(cUnformatted)
   // Description: 
   // Transform a special character in the string 'cUnformatted' to a valid html-code.

   // Variables: 
   LOCAL cTempString_1 := cUnformatted                 // Temporary variable to store the converted value
   LOCAL nCnt_1 := 1                                   // Temporary variable to store numeric values
   LOCAL aSpecialChars := {}                           // List with special characters and their html code

   aSpecialChars := {{"&", "&amp;"}, {"<", "&lt;"}, {">", "&gt;"}, {"€", "&euro;"}, {"%", "&divide;"}, {"°", "&deg;"}}

   // Code:
   DO WHILE nCnt_1 <= LEN(aSpecialChars)
      cTempString_1 := STRTRAN(cTempString_1, aSpecialChars[nCnt_1][1], aSpecialChars[nCnt_1][2])

      nCnt_1++ 
   ENDDO 
   cTempString_1 := STRTRAN(cTempString_1, "&lt;br&gt;", "<br>")
RETURN AllTrim(cTempString_1)


FUNCTION VerifyFileName(cFileName, aFileNames)
   // Description:
   // Create a new filename based on the 'cFileName' parameter. The function checks if another file already exists with the 
   // file name and composes a new one if necessary. Also, any non-alphabetical characters are extracted from the file name 
   // and spaces are replaced by underscores.

   // Variables: 
   LOCAL cTempString_1 := ""                           // Temporary variable to store the new file name 
   LOCAL nCnt_1 := 1                                   // Temporary variable to store a counter 

   // Code: 
   FOR nCnt_1 := 1 TO LEN(cFileName)
      IF (cFileName[nCnt_1] >= "0" .AND. cFileName[nCnt_1] <= "9") .OR. (cFileName[nCnt_1] >= "A" .AND. cFileName[nCnt_1] <= "Z") .OR. (cFileName[nCnt_1] >= "a" .AND. cFileName[nCnt_1] <= "z") .OR. cFileName[nCnt_1] = "_"
         cTempString_1 = cTempString_1 + cFileName[nCnt_1] 
      ENDIF
   NEXT

   cTempString_1 := StrTran(cTempString_1, " ", "_")

   nCnt_1 := 2 
   IF AScan(aFileNames, { |x| Upper(x) == Upper(cTempString_1) }) <> 0 .OR. (Len(cTempString_1) = (At("_", cTempString_1))) 
      cTempString_1 := cTempString_1 + IIF(Right(cTempString_1, 1) = "_", "", "_") + "01" 

      DO WHILE AScan(aFileNames, { |x| Upper(x) == Upper(cTempString_1) }) <> 0
         cTempString_1 := Stuff(cTempString_1, Len(cTempString_1) - 2, 3, "_" + IIF(nCnt_1 < 10, "0" + AllTrim(Str(nCnt_1)), AllTrim(Str(nCnt_1))))
         nCnt_1++ 
      END 
   ENDIF
RETURN cTempString_1 