#
# $Id: Makefile,v 1.7 2004/12/25 11:34:10 ptsarenko Exp $
#

ROOT = ../../

C_SOURCES=\
	msgca.c      \
	msgby866.c   \
	msgbywin.c   \
	msgcs852.c   \
	msgcsiso.c   \
	msgcskam.c   \
	msgcswin.c   \
	msgde.c      \
	msgdewin.c   \
	msgen.c      \
	msgeo.c      \
	msges.c      \
	msgeswin.c   \
	msgeu.c      \
	msgfr.c      \
	msggl.c      \
	msghe862.c   \
	msghewin.c   \
	msghr852.c   \
	msghriso.c   \
	msghu852.c   \
	msghucwi.c   \
	msghuwin.c   \
	msgid.c      \
	msgis850.c   \
	msgit.c      \
	msgko.c      \
	msgltwin.c   \
	msgpl852.c   \
	msgpliso.c   \
	msgplmaz.c   \
	msgplwin.c   \
	msgpt.c      \
	msgro.c      \
	msgru866.c   \
	msgrukoi.c   \
	msgruwin.c   \
	msgsl852.c   \
	msgsliso.c   \
	msgslwin.c   \
	msgsr852.c   \
	msgsriso.c   \
	msgsrwin.c   \
	msgua866.c   \
	msguakoi.c   \
	msguawin.c   \
	msgzhb5.c    \
	msgzhgb.c    \
	
LIBNAME=lang

include $(TOP)$(ROOT)config/lib.cf
