SET PATH=c:\xHarbour\bin;%PATH%;

SET CFLAGS=/Od /EHsc /RTC1 /MTd /Gs /GS /Gy /GR /Zi /DHB_FM_STATISTICS /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE
SET LFLAGS=-DEBUG -DEBUGTYPE:CV

SET HB_DIR_ADS=C:\Program Files\Advantage 9.10\acesdk

C:
CD \xharbour
