SET PATH=\xHarbour\bin;%PATH%;

SET PF32=%ProgramFiles(x86)%
IF "%PF32%" == "" SET PF32=%ProgramFiles%
IF "%PF32%" == "" PAUSE !! ERROR setting PF32 !!

SET CFLAGS=/Od /EHsc /RTC1 /MTd /Gs /GS /Gy /GR /Zi /DHB_FM_STATISTICS /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /DHB_USE_PROFILER -D"HAVE_STDINT_H=0" -D"HAVE_INTTYPES_H=0"
SET LFLAGS=-DEBUG -DEBUGTYPE:CV
SET __MSC__=14

IF EXIST "%PF32%\Advantage 11.10\acesdk" SET HB_DIR_ADS=%PF32%\Advantage 11.10\acesdk

SET HB_DIR_OPENSSL=\OpenSSL-Win32

CD \xharbour
