#
# $Id$
#

ROOT = ../../../

C_SOURCES=\
	rmap1.c \
	rmap2.c \
	rmcdx1.c \
	rmntx1.c \
	m6funcs.c \

PRG_SOURCES=\
	cmcompat.prg \
	m6compat.prg \

LIBNAME=dbrmap

include $(TOP)$(ROOT)config/lib.cf
