#
# $Id: Makefile,v 1.1.1.1 2001/12/21 10:45:37 ronpinkas Exp $
#

ifeq ($(HB_MAIN),)
    HB_MAIN = std
endif

ROOT = ../../

PRG_SOURCES=\
	testprn.prg \
	tprint.prg

PRG_MAIN=testprn.prg

LIBS=\
	debug \
	vm \
	rtl \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	lang \
	common \

include $(TOP)$(ROOT)config/bin.cf

