#
# $Id: Makefile,v 1.5 2005/04/07 23:19:12 likewolf Exp $
#

ROOT = ../../

C_SOURCES=\

PRG_SOURCES=\
    ohtm.prg \
    ocgi.prg \
    oedit.prg \
    oframe.prg \
    oini.prg \
    ofile.prg \
    jwindow.prg \
    htmutil.prg \
    counter.prg \
    hterrsys.prg \
    htmbrows.prg \
    jlist.prg \

LIBNAME=cgi
ifneq ($(HB_ARCHITECTURE),dos)
MT_LIBNAME=cgimt
endif

DIRS=include

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
