#
# $Id: Makefile,v 1.1 2005/10/05 20:25:43 lf_sfnet Exp $
#

ROOT = ../../

C_SOURCES=\

PRG_SOURCES=\
    thtm.prg \
    tcgi.prg \
    tedit.prg \
    tframe.prg \
    tini.prg \
    tfile.prg \
    hjwindow.prg \
    htmutil.prg \
    htcount.prg \
    hterrsys.prg \
    htmbrows.prg \
    htjlist.prg \


LIBNAME=cgi
ifneq ($(HB_ARCHITECTURE),dos)
MT_LIBNAME=cgimt
endif

DIRS=include

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
