#
# $Id: Makefile,v 1.3 2005/10/14 06:31:47 lf_sfnet Exp $
#

ROOT = ../../

C_SOURCES=\

PRG_SOURCES=\
    thtm.prg \
    tcgi.prg \
    tedit.prg \
    tframe.prg \
    tini.prg \
    tfile.prg \
    hjwindow.prg \
    htmutil.prg \
    hterrsys.prg \
    htjlist.prg \

LIBNAME=cgi

DIRS=include

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
