/*
 * xHarbour 1.2.3 Intl. (SimpLex) (Build 20170725)
 * Generated C source code from <C:\\xharbour.com\\xHarbour-XBScript\\xbScriptAX.prg>
 * Command: C:\xharbour.com\xHarbour-XBScript\xbScriptAX.prg -oC:\xharbour.com\xHarbour-XBScript\XBScript\xbScriptAX.c -m -n -w -dWIN -dAX -i\xhb\include 
 * Created: 2017.08.08 11:14:29 (Microsoft Visual C++ 19.10.25019 (32-bit))
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "C:\\xharbour.com\\xHarbour-XBScript\\xbScriptAX.prg"

/* Forward declarations of all PRG defined Functions. */
HB_FUNC_INIT( INIT_XBSCRIPTAX );
HB_FUNC( __RESOLVESITEGLOBALS );
HB_FUNC( XBSCRIPTAX );
HB_FUNC_STATIC( XBSCRIPTAX_COMPILE );
HB_FUNC_STATIC( XBSCRIPTAX_SCRIPTSITEADDGLOBAL );
HB_FUNC_STATIC( XBSCRIPTAX_SCRIPTSITERESETGLOBALS );
HB_FUNC_STATIC( XBSCRIPTAX_RESET );
HB_FUNC_INITSTATICS();

/* Forward declarations of all externally defined Functions. */
/* Skipped DEFERRED call to: 'DIVERTCONSTRUCTORCALL' */
HB_FUNC_EXTERN( GETREF );
HB_FUNC_EXTERN( ERRORBLOCK );
HB_FUNC_EXTERN( TRACELOG );
HB_FUNC_EXTERN( BREAK );
HB_FUNC_EXTERN( PP_DEFAULTERRORBLOCK );
HB_FUNC_EXTERN( RESOLVESITEGLOBALS );
HB_FUNC_EXTERN( HBCLASS );
HB_FUNC_EXTERN( TINTERPRETER );
HB_FUNC_EXTERN( LEN );
HB_FUNC_EXTERN( PP_GENDYNPROCEDURES );
HB_FUNC_EXTERN( __CLSACTIVE );
HB_FUNC_EXTERN( __CLSINST );
HB_FUNC_EXTERN( __OBJHASMSG );
HB_FUNC_EXTERN( HB_APARAMS );
HB_FUNC_EXTERN( PCOUNT );
HB_FUNC_EXTERN( EMPTY );
HB_FUNC_EXTERN( TOLEAUTO );
HB_FUNC_EXTERN( AADD );
HB_FUNC_EXTERN( __QQPUB );
HB_FUNC_EXTERN( __MVPUT );
HB_FUNC_EXTERN( __MVXRELEASE );
HB_FUNC_EXTERN( ASIZE );
HB_FUNC_EXTERN( PP_RESETSTACK );
HB_FUNC_EXTERN( PP_RELEASEDYNPROCEDURES );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 10

#include "hbapi.h"

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_XBSCRIPTAX )
{ "DIVERTCONSTRUCTORCALL", {HB_FS_PUBLIC | HB_FS_DEFERRED}, {NULL}, NULL },
{ "GETREF", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETREF )}, NULL },
{ "INIT_XBSCRIPTAX$", {HB_FS_INIT | HB_FS_LOCAL}, {HB_INIT_FUNCNAME( INIT_XBSCRIPTAX )}, &ModuleFakeDyn },
{ "ERRORBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( ERRORBLOCK )}, NULL },
{ "TRACELOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRACELOG )}, NULL },
{ "BREAK", {HB_FS_PUBLIC}, {HB_FUNCNAME( BREAK )}, NULL },
{ "PP_DEFAULTERRORBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( PP_DEFAULTERRORBLOCK )}, NULL },
{ "__RESOLVESITEGLOBALS", {HB_FS_PUBLIC | HB_FS_LOCAL | HB_FS_FIRST}, {HB_FUNCNAME( __RESOLVESITEGLOBALS )}, &ModuleFakeDyn },
{ "SUBCODE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "SUBSYSTEM", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "RESOLVESITEGLOBALS", {HB_FS_PUBLIC}, {HB_FUNCNAME( RESOLVESITEGLOBALS )}, NULL },
{ "ARGS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "XBSCRIPTAX", {HB_FS_PUBLIC | HB_FS_LOCAL}, {HB_FUNCNAME( XBSCRIPTAX )}, &ModuleFakeDyn },
{ "NEW", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "HBCLASS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HBCLASS )}, NULL },
{ "CLASSH", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TINTERPRETER", {HB_FS_PUBLIC}, {HB_FUNCNAME( TINTERPRETER )}, NULL },
{ "ADDMULTICLSDATA", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ADDMULTIDATA", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ADDMETHOD", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "XBSCRIPTAX_COMPILE", {HB_FS_STATIC | HB_FS_LOCAL}, {HB_FUNCNAME( XBSCRIPTAX_COMPILE )}, &ModuleFakeDyn },
{ "XBSCRIPTAX_SCRIPTSITEADDGLOBAL", {HB_FS_STATIC | HB_FS_LOCAL}, {HB_FUNCNAME( XBSCRIPTAX_SCRIPTSITEADDGLOBAL )}, &ModuleFakeDyn },
{ "XBSCRIPTAX_SCRIPTSITERESETGLOBALS", {HB_FS_STATIC | HB_FS_LOCAL}, {HB_FUNCNAME( XBSCRIPTAX_SCRIPTSITERESETGLOBALS )}, &ModuleFakeDyn },
{ "ADDINLINE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "NNEXTDYNPROC", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "LEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( LEN )}, NULL },
{ "ACOMPILEDPROCS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_NNEXTDYNPROC", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "PP_GENDYNPROCEDURES", {HB_FS_PUBLIC}, {HB_FUNCNAME( PP_GENDYNPROCEDURES )}, NULL },
{ "PDYNLIST", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "XBSCRIPTAX_RESET", {HB_FS_STATIC | HB_FS_LOCAL}, {HB_FUNCNAME( XBSCRIPTAX_RESET )}, &ModuleFakeDyn },
{ "__CLSACTIVE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __CLSACTIVE )}, NULL },
{ "HCLASS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "REFRESH", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CREATE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "__CLSINST", {HB_FS_PUBLIC}, {HB_FUNCNAME( __CLSINST )}, NULL },
{ "__OBJHASMSG", {HB_FS_PUBLIC}, {HB_FUNCNAME( __OBJHASMSG )}, NULL },
{ "INITCLASS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "HB_APARAMS", {HB_FS_PUBLIC}, {HB_FUNCNAME( HB_APARAMS )}, NULL },
{ "PCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PCOUNT )}, NULL },
{ "EMPTY", {HB_FS_PUBLIC}, {HB_FUNCNAME( EMPTY )}, NULL },
{ "_OGLOBALINTERPRETER", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_NNEXTSTARTPROC", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "ADDTEXT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "CTEXT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "NSTARTLINE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_ACOMPILEDPROCS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "_CTEXT", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "COMPILE", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TINTERPRETER", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "TOLEAUTO", {HB_FS_PUBLIC}, {HB_FUNCNAME( TOLEAUTO )}, NULL },
{ "AADD", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADD )}, NULL },
{ "ASCRIPTHOSTGLOBALS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "__QQPUB", {HB_FS_PUBLIC}, {HB_FUNCNAME( __QQPUB )}, NULL },
{ "__MVPUT", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVPUT )}, NULL },
{ "__MVXRELEASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( __MVXRELEASE )}, NULL },
{ "ASIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( ASIZE )}, NULL },
{ "SCRIPTSITERESETGLOBALS", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "PP_RESETSTACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( PP_RESETSTACK )}, NULL },
{ "PP_RELEASEDYNPROCEDURES", {HB_FS_PUBLIC}, {HB_FUNCNAME( PP_RELEASEDYNPROCEDURES )}, NULL },
{ "_PDYNLIST", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "NNEXTSTARTPROC", {HB_FS_PUBLIC}, {NULL}, NULL },
{ "(_INITSTATICS00001)", {HB_FS_INITEXIT}, {hb_INITSTATICS}, &ModuleFakeDyn }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_XBSCRIPTAX, __PRG_SOURCE__,  0x000a )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_XBSCRIPTAX
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_XBSCRIPTAX )
   #include "hbiniseg.h"
#endif

HB_FUNC_INIT( INIT_XBSCRIPTAX )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 10, 0,	/* 10 */
	HB_P_PUSHSYMNEAR, 3,	/* ERRORBLOCK */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 22, 0,	/* 22 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 4,	/* TRACELOG */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 5,	/* BREAK */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_DOSHORT, 1,
/* 00030 */ HB_P_LINEOFFSET, 1,	/* 11 */
	HB_P_PUSHSYMNEAR, 6,	/* PP_DEFAULTERRORBLOCK */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 15, 0,	/* 15 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 5,	/* BREAK */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_DOSHORT, 1,
/* 00052 */ HB_P_LINEOFFSET, 4,	/* 14 */
	HB_P_ENDPROC
/* 00055 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( __RESOLVESITEGLOBALS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 29, 0,	/* 29 */
	HB_P_FALSE,
	HB_P_MESSAGE, 8, 0,	/* SUBCODE */
	HB_P_PUSHLOCALNEAR, 1,	/* OERR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHINT, 233, 3,	/* 1001 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00036) */
	HB_P_POP,
	HB_P_MESSAGE, 9, 0,	/* SUBSYSTEM */
	HB_P_PUSHLOCALNEAR, 1,	/* OERR */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'B', 'A', 'S', 'E', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 21,	/* 21 (abs: 00057) */
/* 00038 */ HB_P_LINEOFFSET, 1,	/* 30 */
	HB_P_PUSHSYMNEAR, 10,	/* RESOLVESITEGLOBALS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALREF, 1, 0,	/* OERR */
	HB_P_MESSAGE, 11, 0,	/* ARGS */
	HB_P_PUSHLOCALNEAR, 1,	/* OERR */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00057 */ HB_P_LINEOFFSET, 4,	/* 33 */
	HB_P_PUSHSYMNEAR, 5,	/* BREAK */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* OERR */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00068 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC( XBSCRIPTAX )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 255,	/* locals, params */
	HB_P_SFRAME, 62, 0,	/* symbol (_INITSTATICS) */
	HB_P_LOCALNEARSETINT, 2, 1, 0,	/* NSCOPE 1*/
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_POP,
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSE, 10, 2,	/* 522 (abs: 00540) */
	HB_P_MESSAGE, 13, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 14,	/* HBCLASS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'x', 'b', 'S', 'c', 'r', 'i', 'p', 't', 'A', 'X', 0, 
	HB_P_MESSAGE, 15, 0,	/* CLASSH */
	HB_P_PUSHSYMNEAR, 16,	/* TINTERPRETER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_SENDSHORT, 2,
	HB_P_POPSTATIC, 1, 0,	/* S_OCLASS */
/* 00060 */ HB_P_BASELINE, 72, 0,	/* 72 */
	HB_P_MESSAGE, 17, 0,	/* ADDMULTICLSDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 64, 0,	/* 64*/
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'n', 'N', 'e', 'x', 't', 'D', 'y', 'n', 'P', 'r', 'o', 'c', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00098 */ HB_P_LINEOFFSET, 2,	/* 74 */
	HB_P_MESSAGE, 18, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 16, 0,	/* 16 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 7,	/* __RESOLVESITEGLOBALS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALREF, 1, 0,	/* codeblockvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'b', 'I', 'n', 't', 'e', 'r', 'c', 'e', 'p', 't', 'R', 'T', 'E', 'B', 'l', 'o', 'c', 'k', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00154 */ HB_P_LINEOFFSET, 4,	/* 76 */
	HB_P_MESSAGE, 18, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'a', 'S', 'c', 'r', 'i', 'p', 't', 'H', 'o', 's', 't', 'G', 'l', 'o', 'b', 'a', 'l', 's', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00197 */ HB_P_LINEOFFSET, 5,	/* 77 */
	HB_P_MESSAGE, 18, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'o', 'G', 'l', 'o', 'b', 'a', 'l', 'I', 'n', 't', 'e', 'r', 'p', 'r', 'e', 't', 'e', 'r', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00238 */ HB_P_LINEOFFSET, 8,	/* 80 */
	HB_P_MESSAGE, 19, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'C', 'o', 'm', 'p', 'i', 'l', 'e', 0, 
	HB_P_PUSHSYMNEAR, 20,	/* XBSCRIPTAX_COMPILE */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00265 */ HB_P_LINEOFFSET, 10,	/* 82 */
	HB_P_MESSAGE, 19, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 20,	/* 20 */
	'S', 'c', 'r', 'i', 'p', 't', 'S', 'i', 't', 'e', 'A', 'd', 'd', 'G', 'l', 'o', 'b', 'a', 'l', 0, 
	HB_P_PUSHSYMNEAR, 21,	/* XBSCRIPTAX_SCRIPTSITEADDGLOBAL */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00304 */ HB_P_LINEOFFSET, 12,	/* 84 */
	HB_P_MESSAGE, 19, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 23,	/* 23 */
	'S', 'c', 'r', 'i', 'p', 't', 'S', 'i', 't', 'e', 'R', 'e', 's', 'e', 't', 'G', 'l', 'o', 'b', 'a', 'l', 's', 0, 
	HB_P_PUSHSYMNEAR, 22,	/* XBSCRIPTAX_SCRIPTSITERESETGLOBALS */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00346 */ HB_P_LINEOFFSET, 14,	/* 86 */
	HB_P_MESSAGE, 23, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'A', 'c', 't', 'i', 'v', 'a', 't', 'e', 0, 
	HB_P_PUSHBLOCK, 84, 0,	/* 84 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_POP,
	HB_P_MESSAGE, 24, 0,	/* NNEXTDYNPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSYMNEAR, 25,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 26, 0,	/* ACOMPILEDPROCS */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00400) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 50,	/* 50 (abs: 00448) */
	HB_P_MESSAGE, 27, 0,	/* _NNEXTDYNPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHSYMNEAR, 25,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 26, 0,	/* ACOMPILEDPROCS */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 28,	/* PP_GENDYNPROCEDURES */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 26, 0,	/* ACOMPILEDPROCS */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 24, 0,	/* NNEXTDYNPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 29, 0,	/* PDYNLIST */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_IVARREF,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00455 */ HB_P_LINEOFFSET, 16,	/* 88 */
	HB_P_MESSAGE, 19, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'R', 'e', 's', 'e', 't', 0, 
	HB_P_PUSHSYMNEAR, 30,	/* XBSCRIPTAX_RESET */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
	HB_P_MESSAGE, 34, 0,	/* CREATE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 35,	/* __CLSINST */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 32, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 36,	/* __OBJHASMSG */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'I', 'n', 'i', 't', 'C', 'l', 'a', 's', 's', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPFALSENEAR, 32,	/* 32 (abs: 00555) */
	HB_P_MESSAGE, 37, 0,	/* INITCLASS */
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 38,	/* HB_APARAMS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 17,	/* 17 (abs: 00555) */
	HB_P_PUSHSYMNEAR, 35,	/* __CLSINST */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 32, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 39,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 10,	/* 10 (abs: 00572) */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSYMNEAR, 0,	/* DIVERTCONSTRUCTORCALL */
	HB_P_FUNCPTR,
	HB_P_ZERO,
	HB_P_DIVERTOF,
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00576 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC_STATIC( XBSCRIPTAX_COMPILE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 1,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 2,	/* SELF */
/* 00006 */ HB_P_BASELINE, 97, 0,	/* 97 */
	HB_P_FALSE,
	HB_P_PUSHSYMNEAR, 40,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* OGLOBALINTERPRETER */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 9,	/* 9 (abs: 00026) */
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* OGLOBALINTERPRETER */
	HB_P_EXACTLYEQUAL,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 111,	/* 111 (abs: 00137) */
/* 00028 */ HB_P_LINEOFFSET, 1,	/* 98 */
	HB_P_MESSAGE, 41, 0,	/* _OGLOBALINTERPRETER */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* OGLOBALINTERPRETER */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00040 */ HB_P_LINEOFFSET, 3,	/* 100 */
	HB_P_MESSAGE, 42, 0,	/* _NNEXTSTARTPROC */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_PUSHSYMNEAR, 25,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 26, 0,	/* ACOMPILEDPROCS */
	HB_P_PUSHLOCALNEAR, 1,	/* OGLOBALINTERPRETER */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00065 */ HB_P_LINEOFFSET, 5,	/* 102 */
	HB_P_MESSAGE, 43, 0,	/* ADDTEXT */
	HB_P_PUSHLOCALNEAR, 1,	/* OGLOBALINTERPRETER */
	HB_P_MESSAGE, 44, 0,	/* CTEXT */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 45, 0,	/* NSTARTLINE */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00089 */ HB_P_LINEOFFSET, 8,	/* 105 */
	HB_P_MESSAGE, 46, 0,	/* _ACOMPILEDPROCS */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_MESSAGE, 26, 0,	/* ACOMPILEDPROCS */
	HB_P_PUSHLOCALNEAR, 1,	/* OGLOBALINTERPRETER */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00106 */ HB_P_LINEOFFSET, 11,	/* 108 */
	HB_P_MESSAGE, 47, 0,	/* _CTEXT */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00119 */ HB_P_LINEOFFSET, 13,	/* 110 */
	HB_P_MESSAGE, 48, 0,	/* COMPILE */
	HB_P_MESSAGE, 49, 0,	/* TINTERPRETER */
	HB_P_PUSHLOCALNEAR, 1,	/* OGLOBALINTERPRETER */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 3,	/* XRET */
	HB_P_JUMPNEAR, 18,	/* 18 (abs: 00153) */
/* 00137 */ HB_P_LINEOFFSET, 16,	/* 113 */
	HB_P_MESSAGE, 48, 0,	/* COMPILE */
	HB_P_MESSAGE, 49, 0,	/* TINTERPRETER */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 3,	/* XRET */
/* 00153 */ HB_P_LINEOFFSET, 22,	/* 119 */
	HB_P_PUSHLOCALNEAR, 3,	/* XRET */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00159 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC_STATIC( XBSCRIPTAX_SCRIPTSITEADDGLOBAL )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 2,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 3,	/* SELF */
/* 00006 */ HB_P_BASELINE, 124, 0,	/* 124 */
	HB_P_MESSAGE, 13, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 50,	/* TOLEAUTO */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* PDISP */
	HB_P_PUSHLOCALNEAR, 1,	/* CNAME */
	HB_P_SENDSHORT, 2,
	HB_P_POPLOCALNEAR, 4,	/* OGLOBAL */
/* 00025 */ HB_P_LINEOFFSET, 2,	/* 126 */
	HB_P_PUSHSYMNEAR, 51,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 52, 0,	/* ASCRIPTHOSTGLOBALS */
	HB_P_PUSHLOCALNEAR, 3,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* CNAME */
	HB_P_PUSHLOCALNEAR, 2,	/* PDISP */
	HB_P_PUSHLOCALNEAR, 4,	/* OGLOBAL */
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_DOSHORT, 2,
/* 00048 */ HB_P_LINEOFFSET, 4,	/* 128 */
	HB_P_PUSHSYMNEAR, 53,	/* __QQPUB */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* CNAME */
	HB_P_DOSHORT, 1,
/* 00057 */ HB_P_LINEOFFSET, 5,	/* 129 */
	HB_P_PUSHSYMNEAR, 54,	/* __MVPUT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* CNAME */
	HB_P_PUSHLOCALNEAR, 4,	/* OGLOBAL */
	HB_P_DOSHORT, 2,
/* 00068 */ HB_P_LINEOFFSET, 9,	/* 133 */
	HB_P_PUSHLOCALNEAR, 3,	/* SELF */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00074 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC_STATIC( XBSCRIPTAX_SCRIPTSITERESETGLOBALS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 140, 0,	/* 140 */
	HB_P_PUSHLOCALREF, 2, 0,	/* AGLOBAL */
	HB_P_MESSAGE, 52, 0,	/* ASCRIPTHOSTGLOBALS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FOREACH,
	HB_P_ENUMERATE,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00038) */
/* 00023 */ HB_P_LINEOFFSET, 1,	/* 141 */
	HB_P_PUSHSYMNEAR, 55,	/* __MVXRELEASE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* AGLOBAL */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_DOSHORT, 1,
/* 00034 */ HB_P_LINEOFFSET, 2,	/* 142 */
	HB_P_JUMPNEAR, 240,	/* -16 (abs: 00020) */
	HB_P_ENDENUMERATE,
/* 00039 */ HB_P_LINEOFFSET, 4,	/* 144 */
	HB_P_PUSHSYMNEAR, 56,	/* ASIZE */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 52, 0,	/* ASCRIPTHOSTGLOBALS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ZERO,
	HB_P_DOSHORT, 2,
/* 00054 */ HB_P_LINEOFFSET, 6,	/* 146 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00059 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC_STATIC( XBSCRIPTAX_RESET )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 155, 0,	/* 155 */
	HB_P_MESSAGE, 57, 0,	/* SCRIPTSITERESETGLOBALS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00017 */ HB_P_LINEOFFSET, 2,	/* 157 */
	HB_P_PUSHSYMNEAR, 40,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 26, 0,	/* ACOMPILEDPROCS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPTRUENEAR, 16,	/* 16 (abs: 00047) */
/* 00033 */ HB_P_LINEOFFSET, 3,	/* 158 */
	HB_P_PUSHSYMNEAR, 58,	/* PP_RESETSTACK */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 26, 0,	/* ACOMPILEDPROCS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 1,
/* 00047 */ HB_P_LINEOFFSET, 6,	/* 161 */
	HB_P_MESSAGE, 29, 0,	/* PDYNLIST */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 28,	/* 28 (abs: 00086) */
/* 00060 */ HB_P_LINEOFFSET, 7,	/* 162 */
	HB_P_PUSHSYMNEAR, 59,	/* PP_RELEASEDYNPROCEDURES */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_MESSAGE, 29, 0,	/* PDYNLIST */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 2,
/* 00075 */ HB_P_LINEOFFSET, 8,	/* 163 */
	HB_P_MESSAGE, 60, 0,	/* _PDYNLIST */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00086 */ HB_P_LINEOFFSET, 11,	/* 166 */
	HB_P_MESSAGE, 27, 0,	/* _NNEXTDYNPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_MESSAGE, 61, 0,	/* NNEXTSTARTPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00103 */ HB_P_LINEOFFSET, 13,	/* 168 */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00109 */
   };

   hb_vmExecute( pcode, symbols );
}

HB_FUNC_INITSTATICS()
{
   static const BYTE pcode[] =
   {
	HB_P_STATICS, 62, 0, 1, 0,	/* symbol (_INITSTATICS), 1 statics */
	HB_P_ENDPROC
/* 00006 */
   };

   hb_vmExecute( pcode, symbols );
}

