#
# $Id: Makefile,v 1.2 2001/03/23 08:47:32 brianhays Exp $
#

ROOT = ../../

C_SOURCES=    \
   ads1.c     \
   adsfunc.c  \
   adsmgmnt.c \

PRG_SOURCES=\
	ads0.prg \

LIBNAME=rddads

include $(TOP)$(ROOT)config/lib.cf
