#
# $Id: Makefile,v 1.1.1.1 2001/12/21 10:43:15 ronpinkas Exp $
#

ROOT = ../../

C_SOURCES=\
	ppcore.c \
	ppcomp.c \
	pplib.c \
	pptable.c \
	pragma.c \

ifeq ($(HB_MT),MT)
   MT_LIBNAME=ppmt
endif

LIBNAME=pp

include $(TOP)$(ROOT)config/lib.cf
