#
# $Id: Makefile,v 1.1 2003/09/08 12:56:53 druzus Exp $
#

ROOT = ../../../

C_SOURCES=\
	dbfdbt1.c \

PRG_SOURCES=\
	dbfdbt0.prg \

ifeq ($(HB_MT),MT)
   MT_LIBNAME=dbfdbtmt
endif


LIBNAME=dbfdbt

include $(TOP)$(ROOT)config/lib.cf
