#
# $Id: Makefile,v 1.13 2003/11/26 09:55:07 druzus Exp $
#

ROOT = ../

C_HEADERS=\
	clipdefs.h   \
	extend.h     \
	hbapi.h      \
	hbapierr.h   \
	hbapifs.h    \
	hbapigt.h    \
	hbfast.h     \
	hbapiitm.h   \
	hbapilng.h   \
	hbapicdp.h   \
	hbapirdd.h   \
	hbcomp.h     \
	hbcomprs.h   \
	hbdate.h     \
	hbdbf.h      \
	hbdbferr.h   \
	hbdbsort.h   \
	hbdefs.h     \
	hberrors.h   \
	hbexprop.h   \
	hbfixdj.h    \
	hbhash.h     \
	hashapi.h    \
	hbi18n.h     \
	hbinit.h     \
	hbmacro.h    \
	hbmath.h     \
	hbnxs.h      \
	hbpcode.h    \
	hbpp.h       \
	hbrddcdx.h   \
	hbrdddbf.h   \
	hbrdddbt.h   \
	hbrdddel.h   \
	hbrddfpt.h   \
	hbrddntx.h   \
	hbrddsdf.h   \
	hbrddwrk.h   \
	hbset.h      \
	hbsetup.h    \
	hbstack.h    \
	hbtrace.h    \
	hbtypes.h    \
	hbver.h      \
	hbvm.h       \
	hbvmpub.h    \
	hbxml.h      \
	hb_io.h      \
	hrbdll.h     \
	inet.h       \
	regex.h      \
	thread.h     \

PRG_HEADERS=\
	achoice.ch   \
	assert.ch    \
	assocarr.ch  \
	box.ch       \
	button.ch    \
	color.ch     \
	common.ch    \
	dbedit.ch    \
	dbinfo.ch    \
	dbstruct.ch  \
	directry.ch  \
	error.ch     \
	fileio.ch    \
	getexit.ch   \
	gtinfo.ch    \
	hbclass.ch   \
	hbcommon.ch  \
	hbcomprs.ch  \
	hbextern.ch  \
	hbinkey.ch   \
	hblang.ch    \
	hblogdef.ch  \
	hbmacro.ch   \
	hbmemory.ch  \
	hbmemvar.ch  \
	hboo.ch      \
	hbpers.ch    \
	hbsetup.ch   \
	hbserv.ch    \
	hbstruct.ch  \
	inkey.ch     \
	memoedit.ch  \
	ord.ch       \
	rddsys.ch    \
	reserved.ch  \
	set.ch       \
	setcurs.ch   \
	simpleio.ch  \
	std.ch       \
	ttable.ch    \
	classex.ch   \
	cstruct.ch   \
	hbrpc.ch     \
	hbxml.ch     \
	hblog.ch     \
	math.ch      \
	tbrowse.ch   \

API_HEADERS=\
	error.api    \
	extend.api   \
	filesys.api  \
	fm.api       \
	gt.api       \
	hbundoc.api  \
	item.api     \
	rdd.api      \
	vm.api       \

include $(TOP)$(ROOT)config/header.cf

