#
# $Id: Makefile,v 1.2 2005/10/08 08:54:54 lf_sfnet Exp $
#

ROOT = ../../

C_SOURCES=\
	hb_f.c \
	
PRG_SOURCES=\

LIBNAME=misc

ifneq ($(HB_ARCHITECTURE),dos)
MT_LIBNAME=miscmt
endif

include $(TOP)$(ROOT)config/lib.cf
