#
# $Id$
#

ROOT = ../../

C_SOURCES = \
	addascii.c \
	asciisum.c \
	ascpos.c \
	atadjust.c \
	atnum.c \
	atrepl.c \
	bit1.c \
	bit2.c \
	bit3.c \
	blank.c \
	charevod.c \
	charlist.c \
	charmirr.c \
	charmix.c \
	charone.c \
	charonly.c \
	charop.c \
	charrepl.c \
	charsort.c \
	charswap.c \
	count.c \
	ctc.c \
	ctchksum.c \
	ctcrypt.c \
	ctmath.c \
	ctmath2.c \
	ctnet.c \
	ctpad.c \
	ctset.c \
	ctstr.c \
	ctwfunc.c \
	ctwin.c \
	cursor.c \
	datetime.c \
	dattime2.c \
	dattime3.c \
	dbftools.c \
	disk.c \
	envparam.c \
	exponent.c \
	files.c \
	finan.c \
	ftoc.c \
	intneg.c \
	justify.c \
	keyset.c \
	lton.c \
	maxline.c \
	misc1.c \
	misc2.c \
	misc3.c \
	num1.c \
	numat.c \
	numcount.c \
	numline.c \
	numlohi.c \
	pack.c \
	pos1.c \
	pos2.c \
	posdiff.c \
	print.c \
	range.c \
	relation.c \
	remove.c \
	replace.c \
	screen1.c \
	screen2.c \
	setlast.c \
	settime.c \
	strdiff.c \
	strfile.c \
	strswap.c \
	tab.c \
	token1.c \
	token2.c \
	trig.c \
	video.c \
	wordrepl.c \
	wordtoch.c \

PRG_SOURCES= \
	color.prg \
	ct.prg \
	ctmisc.prg \
	ctrand.prg \
	cttime.prg \
	diskutil.prg \
	fcopy.prg \
	getinfo.prg \
	getsecrt.prg \
	keysec.prg \
	keytime.prg \
	like.prg \
	numconv.prg \
	screen3.prg \
	setkeys.prg \
	scrmark.prg \
	showtime.prg \
	spread.prg \
	trapkey.prg \
	util.prg

LIBNAME=ct

include $(TOP)$(ROOT)config/lib.cf
