#
# $Id: Makefile,v 1.5 2007/01/11 01:00:35 druzus Exp $
#

ROOT = ../

DIRS=\
	hbpp \
	hbrun \
	hbdoc \
	hbtest \
	hbmake \
	hbdict \
	hbfilere \
	xbscript \
	$(HB_UTILS) \
#	hbextern \

include $(ROOT)config/dir.cf
