#
# $Id: Makefile,v 1.4 2004/05/20 21:09:22 ronpinkas Exp $
#

ROOT = ../

DIRS=\
	hbpp \
	hbrun \
	hbdoc \
	hbtest \
	hbmake \
	hbdict \
	xbscript \
	$(HB_UTILS) \
#	hbextern \

include $(ROOT)config/dir.cf
