#
# $Id: Makefile,v 1.12 2004/12/20 16:48:43 mlombardo Exp $
#

ROOT = ../../

C_SOURCES=\
      cpesdos.c \
      cpeswin.c \
      cpesmwin.c \
      cpgedos.c \
      cpgewin.c \
      cphr852.c \
      cphr1250.c \
      cpitiso.c \
      cpitisb.c \
      cpitdos.c \
      cpdos437.c \
      cpltwin.c \
      cppl852.c \
      cppliso.c \
      cpplmaz.c \
      cpplwin.c \
      cppt850.c \
      cpptiso.c \
      cpru866.c \
      cprukoi.c \
      cpruwin.c \
      cpsl852.c \
      cpsliso.c \
      cpslwin.c \
      cpsrwin.c \
      cpua866.c \
      cpuakoi.c \
      cpuawin.c \
      uc1250.c \
      uc1251.c \
      uc1257.c \
      uc850.c \
      uc852.c \
      uc866.c \
      uc8859_1.c \
      uc88591b.c \
      uc8859_2.c \
      uckoi8.c \
      uckoi8u.c \
      ucmaz.c \

LIBNAME=codepage

include $(TOP)$(ROOT)config/lib.cf
