#
# $Id: Makefile,v 1.3 2003/05/26 13:32:49 druzus Exp $
#

ROOT = ../../

C_SOURCES=\
	cdpesdos.c    \
	cdpeswin.c    \
	cdpgedos.c    \
	cdpgewin.c    \
	cdpla850.c    \
	cdpru866.c    \
	cdprukoi.c    \
	cdpruwin.c    \
	cdppl852.c    \
	cdppliso.c    \
	cdpplmaz.c    \
	cdpplwin.c    \
	cdpsl852.c    \
	cdpsliso.c    \
	cdpslwin.c    \
	cdpsrwin.c    \

LIBNAME=codepage

include $(TOP)$(ROOT)config/lib.cf
