#
# $Id: Makefile,v 1.5 2003/06/20 00:24:15 druzus Exp $
#

ROOT = ../../

C_SOURCES=\
	cdpesdos.c    \
	cdpeswin.c    \
	cdpgedos.c    \
	cdpgewin.c    \
	cdpltwin.c    \
	cdpru866.c    \
	cdprukoi.c    \
	cdpruwin.c    \
	cdppl852.c    \
	cdppliso.c    \
	cdpplmaz.c    \
	cdpplwin.c    \
	cdppt850.c    \
	cdpptiso.c    \
	cdpsl852.c    \
	cdpsliso.c    \
	cdpslwin.c    \
	cdpsrwin.c    \

LIBNAME=codepage

include $(TOP)$(ROOT)config/lib.cf
