#
# $Id: Makefile,v 1.1.1.1 2001/12/21 10:43:42 ronpinkas Exp $
#

ROOT = ../../

PRG_SOURCES=\
	dbgmenu.prg \
   dbghelp.prg \
	dbgtmenu.prg \
	dbgtmitm.prg \
	dbgtwin.prg \
	debugger.prg \
   dbgtarr.prg \
   dbgtobj.prg \
	tbrwtext.prg \
	dbgwa.prg

LIBNAME=debug

include $(TOP)$(ROOT)config/lib.cf
