#
# $Id: Makefile,v 1.2 2003/06/09 20:38:49 lculik Exp $
#

ROOT = ../../

PRG_SOURCES=\
	dbgmenu.prg  \
	dbghelp.prg  \
	dbgtmenu.prg \
	dbgtmitm.prg \
	dbgtwin.prg  \
	debugger.prg \
	dbgaltd.prg  \
	dbgtarr.prg  \
	dbgtobj.prg  \
	tbrwtext.prg \
	dbgwa.prg

LIBNAME=debug

include $(TOP)$(ROOT)config/lib.cf
