#
# $Id: Makefile,v 1.3 2003/07/31 12:51:01 druzus Exp $
#

ROOT = ../../

PRG_SOURCES=\
	dbgmenu.prg  \
	dbghelp.prg  \
	dbgtmenu.prg \
	dbgtmitm.prg \
	dbgtwin.prg  \
	debugger.prg \
	dbgaltd.prg  \
	dbgtarr.prg  \
	dbgtobj.prg  \
	tbrwtext.prg \
	dbgwa.prg    \
        dbgbrwsr.prg

LIBNAME=debug

include $(TOP)$(ROOT)config/lib.cf
