//NOTEST
//
// $Id: lnlenli1.prg,v 1.3 2001/05/15 13:02:07 vszakats Exp $
//

// ; Pushing Harbour preprocessor to the line length limit.
// ; Donated to the public domain by
//   Viktor Szakats <viktor.szakats@syenar.hu>

FUNCTION Main()

     LongLine1()

     RETURN 0

FUNCTION LongLine1()
     RETURN {;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9},;
          {I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") , {|| I_("XXXXXXXXXXXXXXXXXXXXXXXXXXX") }, 99, 9}}

