##################################
# $Id: Makefile,v 1.2 2003/03/22 03:29:19 gian Exp $
#
# Makefile for XWT library
#

TARGET=libxwt.a

PRGFLAGS=-I../include
CFLAGS+=-I../include
XWT_INSTALL=../lib

CSOURCES=xwt_api.c

include ../Rules.make
