#
# $Id: Makefile,v 1.4 2003/09/23 21:23:56 paultucker Exp $
#

ROOT = ../../

C_SOURCES=\

PRG_SOURCES=\
    ohtm.prg \
    ocgi.prg \
    oedit.prg \
    oframe.prg \
    oini.prg \
    ofile.prg \
    jwindow.prg \
    htmutil.prg \
    counter.prg \
    hterrsys.prg \
    htmbrows.prg \
    jlist.prg \

LIBNAME=html
ifneq ($(HB_ARCHITECTURE),dos)
MT_LIBNAME=htmlmt
endif

DIRS=include

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
