#
# $Id: Makefile,v 1.2 2003/04/09 17:47:14 lculik Exp $
#

ROOT = ../../

C_SOURCES=\

PRG_HEADERS=\
	html.ch \
	colors.ch \
	default.ch \
	ferror.ch \
	forms.ch \
	lowfiles.ch \
 
PRG_SOURCES=\
    ohtm.prg \
    ocgi.prg \
    oedit.prg \
    oframe.prg \
    oini.prg \
    ofile.prg \
    jwindow.prg \
    htmutil.prg \
    counter.prg \
    hterrsys.prg \
    htmbrows.prg \
    jlist.prg \

LIBNAME=html
ifneq ($(HB_ARCHITECTURE),dos)
MT_LIBNAME=htmlmt
endif

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/header.cf