#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../../

C_SOURCES = \
	codabar.c \
	code11.c \
	code128.c \
	code39.c \
	code93.c \
	core.c \
	coredraw.c \
	datamtrx.c \
	eanupc.c \
	itf.c \
	msi.c \
	pdf417.c \
	qrcode.c \

PRG_SOURCES= \


C_HEADERS=\

PRG_HEADERS=\
	hbzebra.ch

LIBNAME=hbzebra

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/header.cf
