#
# $Id: Makefile,v 1.3 2001/10/21 08:08:17 davep Exp $
#

ifeq ($(HB_MAIN),)
    HB_MAIN = std
endif

ROOT = ../../

PRG_SOURCES=\
    hbmake.prg \
    hbmutils.prg \
    fclass1.prg \
    ffile1.prg \
    ft_funcs.prg \
    radios.prg \
    checks.prg  \
    pickarry.prg \
    pickfile.prg \
    prb_stak.prg \

PRG_MAIN=hbmake.prg

LIBS=\
	debug \
	vm \
	rtl \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	lang \
	common \

include $(TOP)$(ROOT)config/bin.cf

