#
# $Id: Makefile,v 1.4 2008/08/26 07:44:44 marchuet Exp $
#

ROOT = ../../../../

PRG_SOURCES=\
	arrayrdd.prg \
	logrdd.prg \
	fcomma.prg \
	hscdx.prg \
	rlcdx.prg \
	dbtcdx.prg \
	fptcdx.prg \
	smtcdx.prg \
	ansirdd.prg

LIBNAME=usrrdds

include $(TOP)$(ROOT)config/lib.cf
