#
# $Id: Makefile,v 1.3 2007/05/18 10:08:36 marchuet Exp $
#

ROOT = ../../../../

PRG_SOURCES=\
	arrayrdd.prg \
	fcomma.prg \
	hscdx.prg \
	rlcdx.prg \
	dbtcdx.prg \
	fptcdx.prg \
	smtcdx.prg \
        ansirdd.prg


LIBNAME=usrrdds

include $(TOP)$(ROOT)config/lib.cf
