#
# $Id: Makefile,v 1.1 2006/06/02 12:34:12 druzus Exp $
#

ROOT = ../../../../

PRG_SOURCES=\
	arrayrdd.prg \
	fcomma.prg \
	hscdx.prg \
	rlcdx.prg \
	dbtcdx.prg \
	fptcdx.prg \
	smtcdx.prg \


LIBNAME=usrrdds

include $(TOP)$(ROOT)config/lib.cf
