##################################
# $Id: Makefile,v 1.1 2003/04/02 00:56:38 jonnymind Exp $
#
# Toplevel TGD makefile

all:
	make -C source
	#make -C test

clean:
	make -C source clean
	#make -C test clean
	rm -f lib/*.a


install:
	make -C source install
