#
# $Id:  $
#

# makefile for Borland C/C++ 32 bits
# Building of gtwvw.lib

INCLUDE_DIR = ..\..\include

BIN_DIR = ..\..\bin\b32
OBJ_DIR = ..\..\obj\b32
LIB_DIR = ..\..\lib\b32

$(LIB_DIR)\gtwvw.lib : \
   $(OBJ_DIR)\gtwvw.obj

$(OBJ_DIR)\gtwvw.obj	: gtwvw.c

.c.obj:
  bcc32 $(CLIBFLAGS) -c -O2 -I$(INCLUDE_DIR) -DHB_WIN32_IO -o$@ $<
  tlib $(LIB_DIR)\gtwvw.lib -+$@,,


