##################################
# $Id: Makefile,v 1.1 2003/04/02 00:56:38 jonnymind Exp $
#
# Makefile for GD library
#

TARGET=libgdlib.a

PRGFLAGS=-I../include
CFLAGS+=-I../include
TGD_INSTALL=../lib

CSOURCES=gdwrp.c

include ../Rules.make
