#
# $Id: Makefile,v 1.2 2005/10/24 01:04:34 druzus Exp $
#

ROOT = ../../../

C_SOURCES=\
	sxcompr.c \
	sxcrypt.c \
	sxdate.c \

PRG_SOURCES=\
	sxfunc.prg 

LIBNAME=hbsix

include $(TOP)$(ROOT)config/lib.cf
