#
# $Id: Makefile,v 1.3 2007/09/26 09:20:10 marchuet Exp $
#

ROOT = ../../../


C_SOURCES=\
	sxcompr.c \
	sxcrypt.c \
	sxdate.c  \
	sxsem.c   \
	sxfname.c \
	sxtable.c \
	sxord.c   \
	sxutil.c  \
	sxredir.c 

PRG_SOURCES=\
	sxcompat.prg \
	sxini.prg    \
	sxtrig.prg 

LIBNAME=hbsix

include $(TOP)$(ROOT)config/lib.cf
