# $Id$
#
# Makefile for XWT winapi interface
#

ROOT = ../../../../

C_SOURCES=\
    xwt_win.c \
    xwt_win_framewnd.c \
    xwt_win_menu.c \
    xwt_win_menuitem.c \
    xwt_win_msgbox.c \

LIBNAME=xwt_win

include $(TOP)$(ROOT)config/lib.cf

CFLAGS += -I$(TOP) -I$(TOP)../../include
