#
# $Id: Makefile,v 1.6 2006/09/23 18:03:05 lf_sfnet Exp $
#

ROOT = ../../

C_SOURCES = \
	base64x.c \
	utils.c \

PRG_SOURCES= \
	httpcln.prg \
	popcln.prg \
	credent.prg \
	encoder.prg \
	encb64.prg \
	encqp.prg \
	encurl.prg \
	mail.prg \
	url.prg \
	client.prg \
	ftpcln.prg \
	smtpcln.prg	\
	cgi.prg \
        thtml.prg

LIBNAME=tip

include $(TOP)$(ROOT)config/lib.cf
