#
# $Id: Makefile,v 1.5 2005/11/01 22:05:50 druzus Exp $
#

ROOT = ../../

C_SOURCES = \
	base64x.c \
	utils.c \

PRG_SOURCES= \
	httpcln.prg \
	popcln.prg \
	credent.prg \
	encoder.prg \
	encb64.prg \
	encqp.prg \
	encurl.prg \
	mail.prg \
	url.prg \
	client.prg \
	ftpcln.prg \
	smtpcln.prg	\
	cgi.prg

LIBNAME=tip

include $(TOP)$(ROOT)config/lib.cf
