
Static SqlDLL
#Include "c:\what32\include\wintypes.ch"
#Include "cstruct.ch"
#Include "c:\what32\include\sqltypes.ch"

#Include "c:\what32\include\import.ch"

INIT PROCEDURE LoadSQL()
  SqlDLL := LoadLibrary("SQL.DLL")
RETURN

EXIT PROCEDURE FreeSQL()
  FreeLibrary(SqlDLL)
RETURN


IMPORT SqlDLL FUNCTION SQLRETURN SQLGetConnectAttr(SQLHDBC ConnectionHandle, SQLINTEGER Attribute, SQLPOINTER Value, SQLINTEGER BufferLength, SQLINTEGER *StringLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetConnectOption(SQLHDBC ConnectionHandle,SQLUSMALLINT Option, SQLPOINTER Value)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetCursorName(SQLHSTMT StatementHandle,SQLCHAR *CursorName, SQLSMALLINT BufferLength,SQLSMALLINT *NameLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetData(SQLHSTMT StatementHandle,SQLUSMALLINT ColumnNumber, SQLSMALLINT TargetType,SQLPOINTER TargetValue, SQLLEN BufferLength,SQLLEN *StrLen_or_Ind)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetDescField(SQLHDESC DescriptorHandle,SQLSMALLINT RecNumber, SQLSMALLINT FieldIdentifier,SQLPOINTER Value, SQLINTEGER BufferLength,SQLINTEGER *StringLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetDescRec(SQLHDESC DescriptorHandle,SQLSMALLINT RecNumber, SQLCHAR *Name,SQLSMALLINT BufferLength, SQLSMALLINT *StringLength,SQLSMALLINT *Type, SQLSMALLINT *SubType,SQLLEN *Length, SQLSMALLINT *Precision,SQLSMALLINT *Scale, SQLSMALLINT *Nullable)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetDiagField(SQLSMALLINT HandleType, SQLHANDLE Handle,SQLSMALLINT RecNumber, SQLSMALLINT DiagIdentifier,SQLPOINTER DiagInfo, SQLSMALLINT BufferLength,SQLSMALLINT *StringLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetDiagRec(SQLSMALLINT HandleType, SQLHANDLE Handle,SQLSMALLINT RecNumber, SQLCHAR *Sqlstate,SQLINTEGER *NativeError, SQLCHAR *MessageText,SQLSMALLINT BufferLength, SQLSMALLINT *TextLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetEnvAttr(SQLHENV EnvironmentHandle,SQLINTEGER Attribute, SQLPOINTER Value,SQLINTEGER BufferLength, SQLINTEGER *StringLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetFunctions(SQLHDBC ConnectionHandle,SQLUSMALLINT FunctionId, SQLUSMALLINT *Supported)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetInfo(SQLHDBC ConnectionHandle,SQLUSMALLINT InfoType, SQLPOINTER InfoValue,SQLSMALLINT BufferLength, SQLSMALLINT *StringLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetStmtAttr(SQLHSTMT StatementHandle,SQLINTEGER Attribute, SQLPOINTER Value,SQLINTEGER BufferLength, SQLINTEGER *StringLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetStmtOption(SQLHSTMT StatementHandle,SQLUSMALLINT Option, SQLPOINTER Value)
IMPORT SqlDLL FUNCTION SQLRETURN SQLGetTypeInfo(SQLHSTMT StatementHandle,SQLSMALLINT DataType)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSetConnectAttr(SQLHDBC ConnectionHandle,SQLINTEGER Attribute, SQLPOINTER Value,SQLINTEGER StringLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSetConnectOption(SQLHDBC ConnectionHandle,SQLUSMALLINT Option, SQLULEN Value)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSetCursorName(SQLHSTMT StatementHandle,SQLCHAR *CursorName, SQLSMALLINT NameLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSetDescField(SQLHDESC DescriptorHandle,SQLSMALLINT RecNumber, SQLSMALLINT FieldIdentifier,SQLPOINTER Value, SQLINTEGER BufferLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSetDescRec(SQLHDESC DescriptorHandle,SQLSMALLINT RecNumber, SQLSMALLINT Type,SQLSMALLINT SubType, SQLLEN Length,SQLSMALLINT Precision, SQLSMALLINT Scale,SQLPOINTER Data, SQLLEN *StringLength,SQLLEN *Indicator)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSetEnvAttr(SQLHENV EnvironmentHandle,SQLINTEGER Attribute, SQLPOINTER Value,SQLINTEGER StringLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSetParam(SQLHSTMT StatementHandle,SQLUSMALLINT ParameterNumber, SQLSMALLINT ValueType,SQLSMALLINT ParameterType, SQLULEN LengthPrecision,SQLSMALLINT ParameterScale, SQLPOINTER ParameterValue,SQLLEN *StrLen_or_Ind)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSetStmtAttr(SQLHSTMT StatementHandle,SQLINTEGER Attribute, SQLPOINTER Value,SQLINTEGER StringLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSetStmtOption(SQLHSTMT StatementHandle,SQLUSMALLINT Option, SQLROWCOUNT Value)
IMPORT SqlDLL FUNCTION SQLRETURN SQLAllocConnect(SQLHENV EnvironmentHandle,SQLHDBC *ConnectionHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLAllocEnv(SQLHENV *EnvironmentHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLAllocHandle(SQLSMALLINT HandleType,SQLHANDLE InputHandle, SQLHANDLE *OutputHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLAllocStmt(SQLHDBC ConnectionHandle,SQLHSTMT *StatementHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLBindCol(SQLHSTMT StatementHandle,SQLUSMALLINT ColumnNumber, SQLSMALLINT TargetType,SQLPOINTER TargetValue, SQLLEN BufferLength,SQLLEN *StrLen_or_Ind)
IMPORT SqlDLL FUNCTION SQLRETURN SQLBindParam(SQLHSTMT StatementHandle,SQLUSMALLINT ParameterNumber, SQLSMALLINT ValueType,SQLSMALLINT ParameterType, SQLULEN LengthPrecision,SQLSMALLINT ParameterScale, SQLPOINTER ParameterValue,SQLLEN *StrLen_or_Ind)
IMPORT SqlDLL FUNCTION SQLRETURN SQLCancel(SQLHSTMT StatementHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLCloseCursor(SQLHSTMT StatementHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLColAttribute (SQLHSTMT StatementHandle,SQLUSMALLINT ColumnNumber, SQLUSMALLINT FieldIdentifier,SQLPOINTER CharacterAttribute, SQLSMALLINT BufferLength,SQLSMALLINT *StringLength, SQLPOINTER NumericAttribute)
IMPORT SqlDLL FUNCTION SQLRETURN SQLColumns(SQLHSTMT StatementHandle,SQLCHAR *CatalogName, SQLSMALLINT NameLength1,SQLCHAR *SchemaName, SQLSMALLINT NameLength2,SQLCHAR *TableName, SQLSMALLINT NameLength3,SQLCHAR *ColumnName, SQLSMALLINT NameLength4)
IMPORT SqlDLL FUNCTION SQLRETURN SQLConnect(SQLHDBC ConnectionHandle,SQLCHAR *ServerName, SQLSMALLINT NameLength1,SQLCHAR *UserName, SQLSMALLINT NameLength2,SQLCHAR *Authentication, SQLSMALLINT NameLength3)
IMPORT SqlDLL FUNCTION SQLRETURN SQLCopyDesc(SQLHDESC SourceDescHandle,SQLHDESC TargetDescHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLDataSources(SQLHENV EnvironmentHandle,SQLUSMALLINT Direction, SQLCHAR *ServerName,SQLSMALLINT BufferLength1, SQLSMALLINT *NameLength1,SQLCHAR *Description, SQLSMALLINT BufferLength2,SQLSMALLINT *NameLength2)
IMPORT SqlDLL FUNCTION SQLRETURN SQLDescribeCol(SQLHSTMT StatementHandle,SQLUSMALLINT ColumnNumber, SQLCHAR *ColumnName,SQLSMALLINT BufferLength, SQLSMALLINT *NameLength,SQLSMALLINT *DataType, SQLULEN *ColumnSize,SQLSMALLINT *DecimalDigits, SQLSMALLINT *Nullable)
IMPORT SqlDLL FUNCTION SQLRETURN SQLDisconnect(SQLHDBC ConnectionHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLEndTran(SQLSMALLINT HandleType, SQLHANDLE Handle,SQLSMALLINT CompletionType)
IMPORT SqlDLL FUNCTION SQLRETURN SQLError(SQLHENV EnvironmentHandle,SQLHDBC ConnectionHandle, SQLHSTMT StatementHandle,SQLCHAR *Sqlstate, SQLINTEGER *NativeError,SQLCHAR *MessageText, SQLSMALLINT BufferLength,SQLSMALLINT *TextLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLExecDirect(SQLHSTMT StatementHandle,SQLCHAR *StatementText, SQLINTEGER TextLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLExecute(SQLHSTMT StatementHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLFetch(SQLHSTMT StatementHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLFetchScroll(SQLHSTMT StatementHandle,SQLSMALLINT FetchOrientation, SQLROWOFFSET FetchOffset)
IMPORT SqlDLL FUNCTION SQLRETURN SQLFreeConnect(SQLHDBC ConnectionHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLFreeEnv(SQLHENV EnvironmentHandle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLFreeHandle(SQLSMALLINT HandleType, SQLHANDLE Handle)
IMPORT SqlDLL FUNCTION SQLRETURN SQLFreeStmt(SQLHSTMT StatementHandle,SQLUSMALLINT Option)
IMPORT SqlDLL FUNCTION SQLRETURN SQLNumResultCols(SQLHSTMT StatementHandle,SQLSMALLINT *ColumnCount)
IMPORT SqlDLL FUNCTION SQLRETURN SQLParamData(SQLHSTMT StatementHandle,SQLPOINTER *Value)
IMPORT SqlDLL FUNCTION SQLRETURN SQLPrepare(SQLHSTMT StatementHandle,SQLCHAR *StatementText, SQLINTEGER TextLength)
IMPORT SqlDLL FUNCTION SQLRETURN SQLPutData(SQLHSTMT StatementHandle,SQLPOINTER Data, SQLLEN StrLen_or_Ind)
IMPORT SqlDLL FUNCTION SQLRETURN SQLRowCount(SQLHSTMT StatementHandle,SQLLEN* RowCount)
IMPORT SqlDLL FUNCTION SQLRETURN SQLSpecialColumns(SQLHSTMT StatementHandle,SQLUSMALLINT IdentifierType, SQLCHAR *CatalogName,SQLSMALLINT NameLength1, SQLCHAR *SchemaName,SQLSMALLINT NameLength2, SQLCHAR *TableName,SQLSMALLINT NameLength3, SQLUSMALLINT Scope,SQLUSMALLINT Nullable)
IMPORT SqlDLL FUNCTION SQLRETURN SQLStatistics(SQLHSTMT StatementHandle,SQLCHAR *CatalogName, SQLSMALLINT NameLength1,SQLCHAR *SchemaName, SQLSMALLINT NameLength2,SQLCHAR *TableName, SQLSMALLINT NameLength3,SQLUSMALLINT Unique, SQLUSMALLINT Reserved)
IMPORT SqlDLL FUNCTION SQLRETURN SQLTables(SQLHSTMT StatementHandle,SQLCHAR *CatalogName, SQLSMALLINT NameLength1,SQLCHAR *SchemaName, SQLSMALLINT NameLength2,SQLCHAR *TableName, SQLSMALLINT NameLength3,SQLCHAR *TableType, SQLSMALLINT NameLength4)
IMPORT SqlDLL FUNCTION SQLRETURN SQLTransact(SQLHENV EnvironmentHandle,SQLHDBC ConnectionHandle, SQLUSMALLINT CompletionType)
* End.

