#
# $Id: Makefile,v 1.2 2003/01/10 16:13:06 jonnymind Exp $
#

ROOT = ../../../

C_SOURCES=\

PRG_SOURCES=\
	nulsys.prg \

ifeq ($(HB_MT),MT)
  MT_LIBNAME=nulsysmt
endif
LIBNAME=nulsys

include $(TOP)$(ROOT)config/lib.cf
