#
# $Id: Makefile,v 1.1.1.1 2001/12/21 10:43:00 ronpinkas Exp $
#

ROOT = ../../../

C_SOURCES=\

PRG_SOURCES=\
	nulsys.prg \

ifeq ($(HB_MT),MT)
LIBNAME=nulsysmt
ARCH_SUFFIX=_mt
else
LIBNAME=nulsys
endif

include $(TOP)$(ROOT)config/lib.cf
