#
# $Id$
#

ROOT = ../../../

C_HEADERS=\

PRG_HEADERS=\
	firebird.ch \
	msg.ch \
	mysql.ch \
	oracle.ch \
	pgs.ch \
	sqlextern.ch \
	sqlodbc.ch \
	sqlora.ch \
	sqlrdd.ch \


	
API_HEADERS=\

include $(TOP)$(ROOT)config/header.cf
