#include "d3dx8.h"

#ifndef _D3DX8SHAPES_H
#define _D3DX8SHAPES_H

/* D3DX simple shapes */

#ifndef __PODX8API
#if __POCC__ >= 274
#define __PODX8API  __declspec(dllimport)
#else
#define __PODX8API
#endif
#endif /* __PODX8API */

#ifdef __cplusplus
extern "C" {
#endif

__PODX8API HRESULT WINAPI D3DXCreatePolygon(LPDIRECT3DDEVICE8,FLOAT,UINT,LPD3DXMESH*,LPD3DXBUFFER*);
__PODX8API HRESULT WINAPI D3DXCreateBox(LPDIRECT3DDEVICE8,FLOAT,FLOAT,FLOAT,LPD3DXMESH*,LPD3DXBUFFER*);
__PODX8API HRESULT WINAPI D3DXCreateCylinder(LPDIRECT3DDEVICE8,FLOAT,FLOAT,FLOAT,UINT,UINT,LPD3DXMESH*,LPD3DXBUFFER*);
__PODX8API HRESULT WINAPI D3DXCreateSphere(LPDIRECT3DDEVICE8,FLOAT,UINT,UINT,LPD3DXMESH*,LPD3DXBUFFER*);
__PODX8API HRESULT WINAPI D3DXCreateTorus(LPDIRECT3DDEVICE8,FLOAT,FLOAT,UINT,UINT,LPD3DXMESH*,LPD3DXBUFFER*);
__PODX8API HRESULT WINAPI D3DXCreateTeapot(LPDIRECT3DDEVICE8,LPD3DXMESH*,LPD3DXBUFFER*);
__PODX8API HRESULT WINAPI D3DXCreateTextA(LPDIRECT3DDEVICE8,HDC,LPCSTR,FLOAT,FLOAT,LPD3DXMESH*,LPD3DXBUFFER*,LPGLYPHMETRICSFLOAT);
__PODX8API HRESULT WINAPI D3DXCreateTextW(LPDIRECT3DDEVICE8,HDC,LPCWSTR,FLOAT,FLOAT,LPD3DXMESH*,LPD3DXBUFFER*,LPGLYPHMETRICSFLOAT);

#ifdef UNICODE
#define D3DXCreateText D3DXCreateTextW
#else
#define D3DXCreateText D3DXCreateTextA
#endif

#ifdef __cplusplus
}
#endif

#endif /* _D3DX8SHAPES_H */
