#
# $Id: Makefile,v 1.2 2005/04/08 12:56:31 likewolf Exp $
#

ROOT = ../../../

PRG_HEADERS=\
	html.ch \
	colors.ch \
	default.ch \
	ferror.ch \
	forms.ch \
	lowfiles.ch \
 
include $(TOP)$(ROOT)config/header.cf
