#
# $Id: Makefile,v 1.1 2005/10/05 20:25:43 lf_sfnet Exp $
#

ROOT = ../../../

PRG_HEADERS=\
	html.ch \
   htmlclrs.ch \
	ferror.ch \
   htmlform.ch \
	lowfiles.ch \
 
include $(TOP)$(ROOT)config/header.cf
