#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../../

C_SOURCES = \
	hb_btree.c \

PRG_SOURCES= \
	tbtree.prg \

C_HEADERS=\

PRG_HEADERS=\
	hb_btree.ch \

LIBNAME=hbbtree

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/header.cf
