##################################
# $Id: Makefile,v 1.2 2003/03/22 03:29:19 gian Exp $
#
# Makefile for XWT GTK interface
#

TARGET=libxwt_gtk.a
CFLAGS+=-I. -I../../include `pkg-config --cflags gtk+-2.0`

SOURCE_TYPE=c
XWT_INSTALL=../../lib

include ../../Rules.make
