#!/bin/sh
name="xharbour"
dname="xHarbour"
version="0.99.5"
releasen="0"
platform="cl9"
prefix="/usr"
hb_pref="xhb"
hb_gt="crs"
hb_gpm="yes"
hb_mt="MT"
hb_mgt="yes"
hb_lnkso=yes
hb_libs="vm pp rtl rdd dbfdbt dbffpt dbfcdx dbfntx hsx macro common lang codepage gtnul gtcrs gtsln gtcgi gtstd gtpca odbc ct debug profiler"
export HB_COMPILER="gcc"
export C_USR="-DHB_FM_STATISTICS_OFF -O3"
export HB_ARCHITECTURE="linux"
export HB_MT=MT
export HB_GT_LIB=gtcrs
export HB_GPM_MOUSE=yes
export HB_MULTI_GT=yes

export HB_BIN_INSTALL="/usr/src/xharbour/debian/tmp/usr/bin"
export HB_INC_INSTALL="/usr/src/xharbour/debian/tmp/usr/include/xharbour"
export HB_LIB_INSTALL="/usr/src/xharbour/debian/tmp/usr/lib/xharbour"
export RPM_BUILD_ROOT="/usr/src/xharbour/debian/tmp"

mkdir -p $HB_BIN_INSTALL
mkdir -p $HB_INC_INSTALL
mkdir -p $HB_LIB_INSTALL
mkdir -p $RPM_BUILD_ROOT
hb_host="www.xharbour.org"
readme="README.RPM"

pushd contrib/hbzlib
make
popd
pushd contrib/htmllib
make
popd
pushd contrib/libmisc
make
popd
pushd contrib/libnf
make
popd
pushd contrib/rdd_ads
make
popd
pushd utils/xbscript/linux/gcc
ln -s xbscript pprun
ln -s xbscript xprompt
