#
# $Id: Makefile,v 1.7 2000/04/14 20:01:21 vszel Exp $
#

ROOT = ../../

PRG_SOURCES=\
	editorhi.prg \
	
C_SOURCES=\
	editorlo.c \

PRG_MAIN=pe.prg

LIBS=\
	debug \
	vm \
	rtl \
	lang \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	common \

include $(TOP)$(ROOT)config/bin.cf
