[source\sql.y]

[source\sqlodbc.prg]

[source\sqlconnection.prg]

[source\sqlrdd0.prg]

[source\sqlrdd2.prg]

[source\utils.prg]

[source\sqlgen1.prg]

[source\utilslang.prg]

[source\sqlmy.prg]

[source\sqlpgs.prg]

[source\sqlfirebird.prg]
[source\sqlfirebird3.prg]

[source\sqloracle.prg]

[source\ExprTransl.prg]

[source\ExprParser.prg]

[source\ExprSimpl.prg]

[source\ExprObjs.prg]

[source\ExprRelation.prg]

[source\ExprUDF.prg]

[source\sqlact.c]
MYDEFINES = HB_API_MACROS

[source\firebird.c]
[source\firebird3.c]

[source\sqllex.c]

[source\mysql.c]

[source\pgs.c]

[source\sqlsrodbc.c]

[source\sqlrdd1.c]

[source\sqlora.c]

[source\sqlorax.c]

[source\sqlnames.prg]

[source\sqlex1.c]

[source\sqlex2.c]

[source\sqlex3.c]

[source\sqlmaria.prg]
[source\sqlora2.c]
[source\sqloracle2.prg]