#
# $Id: Makefile,v 1.3 2003/01/12 22:50:20 jonnymind Exp $
#

ROOT = ../../../

C_SOURCES=\
	dbfcdx1.c \

PRG_SOURCES=\
	dbfcdx0.prg \

ifeq ($(HB_MT),MT)
   MT_LIBNAME=dbfcdxmt
endif

LIBNAME=dbfcdx

include $(TOP)$(ROOT)config/lib.cf
