#
# $id:
#

#
# File:     makefile.nt
# Author:   Paul Tucker <ptucker@sympatico.ca>
# Created:  2002
# Updated:
#
# Makefile : Builds Whoo for msvc in batch mode

# Global paths
#
HBR_DIR =..\..
WHO_DIR =.
WH_DIR  =..\what32
OUTDIR  =build
OBJ_DIR =obj\vc
SRCDIR  =source
LIBDIR  =lib\vc


MK_FILE  = makefile.nt
MK_FLAGS = $(MAKEFLAGS: =)

#-- HARBOUR COMPILER ----
hbc      =$(HBR_DIR)\BIN\harbour
hbcflags =-n -w -es2 -i$(WH_DIR)\include;$(HBR_DIR)\include

#-- C COMPILER ----------
CC       =cl
CFLAGS   =-TP -W3 -Ox -GA -nologo -c -DHB_API_MACROS -DHB_STACK_MACROS -DHB_OS_WIN_32 -DHB_FM_STATISTICS_OFF -I$(WH_DIR)\include -I$(HBR_DIR)\include

#-- RESOURCE COMPILER ---
rc       =rc
rcflags  =-r

.SUFFIXES: .prg .c

.c.obj::
 $(CC) $(CFLAGS) -Fo$(OBJ_DIR)\ $<

WHOOLIB  = $(LIBDIR)\whoo.lib

LIBLIST  = $(WHOOLIB)

# library
#

{$(OBJ_DIR)}.c{$(OBJ_DIR)}.obj::
   $(CC) $(CFLAGS) -Fo$(OBJ_DIR)\ $<

{$(SRCDIR)}.c{$(OBJ_DIR)}.obj::
   $(CC) $(CFLAGS) -Fo$(OBJ_DIR)\ $<

{$(SRCDIR)}.prg{$(OBJ_DIR)}.obj::
   $(hbc) $(hbcflags) -o$(OBJ_DIR)\ $<
   $(MAKE) -nologo /$(MK_FLAGS)f$(MK_FILE) $(WHOOLIB)2

WHOOOBJ    = \
    $(OBJ_DIR)\TObject.obj \
    $(OBJ_DIR)\TPersistent.obj \
    $(OBJ_DIR)\TComponent.obj \
    $(OBJ_DIR)\TControl.obj \
    $(OBJ_DIR)\TCustomControl.obj \
    $(OBJ_DIR)\TWinControl.obj \
    $(OBJ_DIR)\TForm.obj \
    $(OBJ_DIR)\TApplication.obj \
    $(OBJ_DIR)\TMenu.obj \
    $(OBJ_DIR)\TPopup.obj \
    $(OBJ_DIR)\TMenuItem.obj \
    $(OBJ_DIR)\TrackMenu.obj \
    $(OBJ_DIR)\TCButton.obj \
    $(OBJ_DIR)\TCEdit.obj \
    $(OBJ_DIR)\TCCheck.obj \
    $(OBJ_DIR)\TCCombo.obj \
    $(OBJ_DIR)\TCRadio.obj \
    $(OBJ_DIR)\TCStatic.obj \
    $(OBJ_DIR)\TFrame.obj \
    $(OBJ_DIR)\TPanel.obj \
    $(OBJ_DIR)\TCListBox.obj \
    $(OBJ_DIR)\TCStatusBar.obj \
    $(OBJ_DIR)\TCRebar.obj \
    $(OBJ_DIR)\TCToolBar.obj \
    $(OBJ_DIR)\TabControl.obj \
    $(OBJ_DIR)\TCGroupBox.obj \
    $(OBJ_DIR)\TSplash.obj \
    $(OBJ_DIR)\TTreeView.obj \
    $(OBJ_DIR)\TTVItem.obj \
    $(OBJ_DIR)\TCBrowser.obj \
    $(OBJ_DIR)\TCProgBar.obj \
    $(OBJ_DIR)\TWColumn.obj \
    $(OBJ_DIR)\THintWindow.obj \
    $(OBJ_DIR)\TStrings.obj \
    $(OBJ_DIR)\TCommonDialog.obj \
    $(OBJ_DIR)\TOpenDialog.obj \
    $(OBJ_DIR)\TCustomTab.obj \
    $(OBJ_DIR)\TPageControl.obj \
    $(OBJ_DIR)\TTabSheet.obj

!if ( "$(MK_FLAGS)"=="A" )

all: zot \
   $(WHOOLIB)

MK_FLAGS = $(MK_FLAGS:A=)

zot:
   -@if exist $(OBJ_DIR)\*.obj $(DEL) $(OBJ_DIR)\*.obj > nul
   -@if exist $(OBJ_DIR)\*.c $(DEL) $(OBJ_DIR)\*.c > nul
   -@if exist $(OBJ_DIR)\*.h $(DEL) $(OBJ_DIR)\*.h > nul

!else

all: \
   $(WHOOLIB)
!endif

$(WHOOLIB) : $(WHOOOBJ)
   lib /out:$@ $**

$(WHOOLIB)2  : $(WHOOLIB)
