
# Global paths
#
HBR_DIR=..\..
BCC_DIR=c:\bcc55
WHO_DIR=.
WH_DIR=..\what32

!include <env\bccwin32.mak>

# library
#
WHOOLIB    = lib\whoo.lib

WHOOOBJ    = TApplication.obj TWindow.obj TForm.obj TControl.obj TMenu.obj \
             TCButton.obj TCEdit.obj TCCheck.obj TCCombo.obj TCRadio.obj \
             TCStatic.obj TFrame.obj TPanel.obj

!include $(WHO_DIR)\env\makelib.b32

