[\xHarbour\source\rdd\dbffpt\dbffpt1.c]

[\xHarbour\source\rdd\dbnubs.c]
[\xHarbour\source\rdd\hbdbsort.c]
[\xHarbour\source\rdd\workarea.c]
[\xHarbour\source\rdd\dbcmd.c]
[\xHarbour\source\rdd\wacore.c]
[\xHarbour\source\rdd\wafunc.c]

[\xHarbour\source\rdd\delim1.c]
[\xHarbour\source\rdd\sdf1.c]

[\xHarbour\source\rdd\dbf1.c]
[\xHarbour\source\rdd\dbfuncs.prg]
[\xHarbour\source\rdd\dblist.prg]
[\xHarbour\source\rdd\dbsort.prg]
[\xHarbour\source\rdd\dbupdat.prg]
[\xHarbour\source\rdd\rddord.prg]
[\xHarbour\source\rdd\rddsys.prg]
[\xHarbour\source\rdd\dbtotal.prg]
[\xHarbour\source\rdd\dbstrux.prg]

[\xHarbour\source\rdd\dbdelim.prg]
[\xHarbour\source\rdd\dbjoin.prg]
[\xHarbour\source\rdd\dbsdf.prg]

[\xHarbour\source\rdd\hbsix\sxcompr.c]
[\xHarbour\source\rdd\hbsix\sxcrypt.c]
[\xHarbour\source\rdd\hbsix\sxdate.c]

[\xHarbour\source\rdd\hsx\hsx.c]
[\xHarbour\source\rdd\hsx\cftsfunc.c]

[\xHarbour\source\rdd\usrrdd\usrrdd.c]

[\xHarbour\source\rdd\usrrdd\rdds\smtcdx.prg]
[\xHarbour\source\rdd\usrrdd\rdds\adordd.prg]

[\xHarbour\source\rdd\dbcmd53.c]
[\xHarbour\source\rdd\dbcmdx.c]
[\xHarbour\source\rdd\dbcmdhb.c]
[\xHarbour\source\rdd\dbdrop.c]
[\xHarbour\source\rdd\dbexists.c]
[\xHarbour\source\rdd\fieldhb.c]
[\xHarbour\source\rdd\rddinfo.c]

[\xHarbour\source\rdd\dbtotalx.prg]
[\xHarbour\source\rdd\dblistx.prg]
[\xHarbour\source\rdd\dbfuncsx.prg]
[\xHarbour\source\rdd\dbsortx.prg]
[\xHarbour\source\rdd\dbstruxx.prg]
[\xHarbour\source\rdd\dbstruxu.prg]
[\xHarbour\source\rdd\dbupdatx.prg]
[\xHarbour\source\rdd\rddordu.prg]
[\xHarbour\source\rdd\dbjoinx.prg]

[\xHarbour\contrib\filemem\filemem.c]
