MYDEFINES = HB_BACK_END=xHarbourBackEnd(szFileName)

[source\compiler\hbmain.c]
[source\compiler\harbour.c]
[source\compiler\comptool.c]

[source\compiler\harbour.sly]

[source\compiler\cmdcheck.c]
[source\compiler\hbusage.c]
[source\compiler\hbident.c]
[source\compiler\hbgenerr.c]
[source\compiler\hbpcode.c]
[source\compiler\hbdead.c]
[source\compiler\hbstripl.c]
[source\compiler\hbfix.c]

[source\compiler\genc.c]
[source\compiler\gencobj.c]
[source\compiler\genhrb.c]

#[source\compiler\genjava.c]
#[source\compiler\genobj32.c]

[source\compiler\expropta.c]
[source\compiler\exproptb.c]
[source\compiler\exproptc.c]

[source\compiler\hbfunchk.c]

[source\compiler\gencc.c]
[source\compiler\gencc1.c]

[source\compiler\hbpcstat.c]
[source\compiler\hbdbginf.c]
[source\compiler\hblbl.c]

[source\compiler\hbslex.c]

[source\common\hbhash.c]
[source\common\reserved.c]
[source\common\hbgete.c]


#[source\common\hbfhnd.c]

[source\common\hbver.c]
[source\common\expropt2.c]
[source\common\hbfsapi.c]
[source\common\hbstr.c]
[source\common\hbwince.c]
[source\common\expropt1.c]
[source\common\hbtrace.c]
[source\common\hbdate.c]
[source\common\hbfopen.c]


[source\compiler\ppcomp.c]
[source\pp\ppcore.c]
[source\pp\pptable.c]


[source\common\hbprintf.c]


[\xHarbour.com\xHarbour-Builder\xhb.c]

[\xHarbour.com\xHarbour-XCC\xcc\xcc.lib]
