##################################
# $Id: Makefile,v 1.1 2003/04/02 00:56:38 jonnymind Exp $
#
# Makefile for XWT library
#

TARGET=libxwt.a

PRGFLAGS=-I../include
CFLAGS+=-I../include
XWT_INSTALL=../lib

CSOURCES=xwt_api.c

include ../Rules.make
