#
# File:     makefile.b32
# Author:   Francesco Saverio Giudice (on a makefile by Julian Smart)
# Created:  2002
# Updated:
# Copyright: (C) Francesco Saverio Giudice - FreeImage Library
#
# Makefile : Builds GD library (Harbour & BC++ 32-bit)

# Global paths
#
HBR_DIR=..\..
APP_DIR=.
APP_NAME=fi_lib

!include <env\bccwin32.mak>

# library
#

APPLIB      = lib\$(APP_NAME).lib

APPDLL      = lib\$(APP_NAME).dll

APPOBJ      = fi_wrp.obj fi_winfu.obj

!include $(APP_DIR)\env\makelib.b32

