##################################
# $Id: Makefile,v 1.1 2005/10/24 13:17:10 fsgiudice Exp $
#
# Toplevel FreeImage makefile

all:
	make -C source
	#make -C test

clean:
	make -C source clean
	#make -C test clean
	rm -f lib/*.a


install:
	make -C source install
