#
# $Id$
#

ROOT = ../../

C_SOURCES = \
   base64x.c \
   utils.c \
   base64.c \

PRG_SOURCES= \
   cgi.prg \
   client.prg \
   credent.prg \
   encb64.prg \
   encoder.prg \
   encqp.prg \
   encurl.prg \
   ftpcln.prg \
   httpcln.prg \
   mail.prg \
   popcln.prg \
   sendmail.prg \
   smtpcln.prg\
   thtml.prg \
   url.prg \

LIBNAME=tip

include $(TOP)$(ROOT)config/lib.cf
