HB_INC_COMPILE=$(TOP)../include -I$(TOP)$(ROOT)include
ROOT=../../../
C_SOURCES=\
	commond.c \
	control.c \
   dialog.c \
	draw.c \
	drawtext.c \
	freeimg.c \
	menu_c.c \
	message.c \
	misc.c \
	registry.c \
	wbrowse.c \
	shellapi.c \
	media_c.c \
	richedit.c \
	wprint.c \
	window.c \
	
PRG_SOURCES=\
	drawwidg.prg \
	errorsys.prg \
	guimain.prg \
	hbrowse.prg \
	hcheck.prg \
	hcombo.prg \
	hcontrol.prg \
	hdatepic.prg \
	hedit.prg \
	hfreeimg.prg \
	hfrmtmpl.prg \
	hgraph.prg \
	hownbtn.prg \
	hpanel.prg \
	hprinter.prg \
	hradio.prg \
	hriched.prg \
	htab.prg \
	hupdown.prg \
	hwindow.prg \
	menu.prg \
	printer.prg \
	repexec.prg \
	hprogres.prg \
	hdialog.prg \
	htimer.prg \
	htree.prg \
	hsplit.prg \
	
LIBNAME=hwgui

DIRS=\
	procmisc \
	qhtm


include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
