#
# $Id: Makefile,v 1.2 2004/05/10 10:38:06 mauriliolongo Exp $
#

ROOT = ../../../

C_SOURCES=\
	dbffpt1.c \

ifeq ($(HB_MT),MT)
   MT_LIBNAME=dbffptmt
endif

LIBNAME=dbffpt

include $(TOP)$(ROOT)config/lib.cf
