#
# $Id: Makefile,v 1.1 2000/05/31 21:47:19 vszel Exp $
#

ROOT = ../../

C_SOURCES=\
	date.c \
	dbf.c \
	environ.c \
	gauge.c \
	num.c \
	stack.c \
	status.c \
	time.c \

PRG_SOURCES=\

LIBNAME=samples

include $(TOP)$(ROOT)config/lib.cf
