#
# $Id: Makefile 9279 2011-02-14 18:06:32Z druzus $
#

ROOT = ../../

C_SOURCES = \
	core.c \

PRG_SOURCES= \
	hbmagis.prg \

C_HEADERS=\

PRG_HEADERS=\
	hbmagic.ch

LIBNAME=hbmagic

include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/header.cf
