#
# $Id: Makefile,v 1.1 2005/04/07 23:19:13 likewolf Exp $
#

ROOT = ../../../

PRG_HEADERS=\
	html.ch \
	colors.ch \
	default.ch \
	ferror.ch \
	forms.ch \
	lowfiles.ch \
 
include $(TOP)$(ROOT)config/header.cf
