/* Use underscore on basic types to avoid clashing with Windows types */
/*
xx(symbol,      value,  prec,   op,     optree,         kind,       string)
*/
yy(0,            0,     0,      0,      0,              0,          0)
xx(FLOAT_,       1,     0,      0,      0,              CHAR_,      "float")
xx(DOUBLE_,      2,     0,      0,      0,              CHAR_,      "double")
xx(CHAR_,        3,     0,      0,      0,              CHAR_,      "char")
xx(SHORT_,       4,     0,      0,      0,              CHAR_,      "short")
xx(INT_,         5,     0,      0,      0,              CHAR_,      "int")
xx(UNSIGNED,     6,     0,      0,      0,              CHAR_,      "unsigned")
xx(POINTER,      7,     0,      0,      0,              0,          "pointer")
xx(VOID_,        8,     0,      0,      0,              CHAR_,      "void")
xx(STRUCT,       9,     0,      0,      0,              CHAR_,      "struct")
xx(UNION,       10,     0,      0,      0,              CHAR_,      "union")
xx(FUNCTION,    11,     0,      0,      0,              0,          "function")
xx(ARRAY,       12,     0,      0,      0,              0,          "array")
xx(ENUM,        13,     0,      0,      0,              CHAR_,      "enum")
xx(LONG_,       14,     0,      0,      0,              CHAR_,      "long")
xx(CONST_,      15,     0,      0,      0,              CHAR_,      "const")
xx(VOLATILE_,   16,     0,      0,      0,              CHAR_,      "volatile")
xx(BOOL_,       17,     0,      0,      0,              CHAR_,      "_Bool")
#ifdef HAS_C99_COMPLEX
xx(COMPLEX_,    18,     0,      0,      0,              CHAR_,      "_Complex")
#else
yy(0,           18,     0,      0,      0,              0,          0)
#endif
yy(0,           19,     0,      0,      0,              0,          0)
yy(0,           20,     0,      0,      0,              0,          0)
yy(0,           21,     0,      0,      0,              0,          0)
yy(0,           22,     0,      0,      0,              0,          0)
yy(0,           23,     0,      0,      0,              0,          0)
yy(0,           24,     0,      0,      0,              0,          0)
yy(0,           25,     0,      0,      0,              0,          0)
yy(0,           26,     0,      0,      0,              0,          0)
yy(0,           27,     0,      0,      0,              0,          0)
yy(0,           28,     0,      0,      0,              0,          "long long")                /* LONG_+LONG_ */
yy(0,           29,     0,      0,      0,              0,          0)
yy(0,           30,     0,      0,      0,              0,          0)
yy(0,           31,     0,      0,      0,              0,          "const volatile")           /* CONST_+VOLATILE_ */
xx(ID,          32,     0,      0,      0,              ID,         "identifier")
yy(0,           33,     0,      0,      0,              ID,         "!")
xx(FCONST,      34,     0,      0,      0,              ID,         "floating constant")
xx(ICONST,      35,     0,      0,      0,              ID,         "integer constant")
xx(SCONST,      36,     0,      0,      0,              ID,         "string constant")
yy(0,           37,     13,     MOD,    bit_tree,       '%',        "%")
yy(0,           38,     8,      BAND,   bit_tree,       ID,         "&")
xx(INCR,        39,     0,      ADD,    add_tree,       ID,         "++")
yy(0,           40,     0,      0,      0,              ID,         "(")
yy(0,           41,     0,      0,      0,              ')',        ")")
yy(0,           42,     13,     MUL,    mul_tree,       ID,         "*")
yy(0,           43,     12,     ADD,    add_tree,       ID,         "+")
yy(0,           44,     1,      0,      0,              ',',        ",")
yy(0,           45,     12,     SUB,    sub_tree,       ID,         "-")
yy(0,           46,     0,      0,      0,              '.',        ".")
yy(0,           47,     13,     DIV,    mul_tree,       '/',        "/")
xx(DECR,        48,     0,      SUB,    sub_tree,       ID,         "--")
xx(DEREF,       49,     0,      0,      0,              DEREF,      "->")
xx(ANDAND,      50,     5,      AND,    and_tree,       ANDAND,     "&&")
xx(OROR,        51,     4,      OR,     and_tree,       OROR,       "||")
xx(LEQ,         52,     10,     LE,     cmp_tree,       LEQ,        "<=")
xx(EQL,         53,     9,      EQ,     equality_tree,  EQL,        "==")
xx(NEQ,         54,     9,      NE,     equality_tree,  NEQ,        "!=")
xx(GEQ,         55,     10,     GE,     cmp_tree,       GEQ,        ">=")
xx(RSHIFT,      56,     11,     RSH,    shift_tree,     RSHIFT,     ">>")
xx(LSHIFT,      57,     11,     LSH,    shift_tree,     LSHIFT,     "<<")
yy(0,           58,     0,      0,      0,              ':',        ":")
yy(0,           59,     0,      0,      0,              IF,         ";")
yy(0,           60,     10,     LT,     cmp_tree,       '<',        "<")
yy(0,           61,     2,      ASGN,   assignment_tree,'=',        "=")
yy(0,           62,     10,     GT,     cmp_tree,       '>',        ">")
yy(0,           63,     0,      0,      0,              '?',        "?")
xx(ELLIPSIS,    64,     0,      0,      0,              ELLIPSIS,   "...")
xx(SIZEOF,      65,     0,      0,      0,              ID,         "sizeof")
yy(0,           66,     0,      0,      0,              0,          0)
xx(AUTO,        67,     0,      0,      0,              STATIC,     "auto")
xx(BREAK,       68,     0,      0,      0,              IF,         "break")
xx(CASE,        69,     0,      0,      0,              IF,         "case")
xx(CONTINUE,    70,     0,      0,      0,              IF,         "continue")
xx(DEFAULT,     71,     0,      0,      0,              IF,         "default")
xx(DO,          72,     0,      0,      0,              IF,         "do")
xx(ELSE,        73,     0,      0,      0,              IF,         "else")
xx(EXTERN,      74,     0,      0,      0,              STATIC,     "extern")
xx(FOR,         75,     0,      0,      0,              IF,         "for")
xx(GOTO,        76,     0,      0,      0,              IF,         "goto")
xx(IF,          77,     0,      0,      0,              IF,         "if")
xx(REGISTER,    78,     0,      0,      0,              STATIC,     "register")
xx(RETURN,      79,     0,      0,      0,              IF,         "return")
xx(SIGNED,      80,     0,      0,      0,              CHAR_,      "signed")
xx(STATIC,      81,     0,      0,      0,              STATIC,     "static")
xx(SWITCH,      82,     0,      0,      0,              IF,         "switch")
xx(TYPEDEF,     83,     0,      0,      0,              STATIC,     "typedef")
xx(WHILE,       84,     0,      0,      0,              IF,         "while")
yy(0,           85,     0,      0,      0,              0,          0)
yy(0,           86,     0,      0,      0,              0,          0)
yy(0,           87,     0,      0,      0,              0,          0)
yy(0,           88,     0,      0,      0,              0,          0)
yy(0,           89,     0,      0,      0,              0,          0)
xx(RESTRICT_,   90,     0,      0,      0,              CHAR_,      "restrict")
yy(0,           91,     0,      0,      0,              '[',        "[")
yy(0,           92,     0,      0,      0,              0,          0)
yy(0,           93,     0,      0,      0,              ']',        "]")
yy(0,           94,     7,      BXOR,   bit_tree,       '^',        "^")
yy(0,           95,     0,      0,      0,              0,          0)
yy(0,           96,     0,      0,      0,              0,          0)
yy(0,           97,     0,      0,      0,              0,          0)
yy(0,           98,     0,      0,      0,              0,          0)
yy(0,           99,     0,      0,      0,              0,          0)
yy(0,           100,    0,      0,      0,              0,          0)
yy(0,           101,    0,      0,      0,              0,          0)
yy(0,           102,    0,      0,      0,              0,          0)
yy(0,           103,    0,      0,      0,              0,          0)
yy(0,           104,    0,      0,      0,              0,          0)
yy(0,           105,    0,      0,      0,              0,          "const restrict")           /* CONST_+RESTRICT_ */
yy(0,           106,    0,      0,      0,              0,          "volatile restrict")        /* VOLATILE_+RESTRICT_ */
yy(0,           107,    0,      0,      0,              0,          0)
yy(0,           108,    0,      0,      0,              0,          0)
yy(0,           109,    0,      0,      0,              0,          0)
xx(DECLSPEC,    110,    0,      0,      0,              STATIC,     "__declspec")
xx(STDCALL_,    111,    0,      0,      0,              STATIC,     "__stdcall")
xx(CDECL_,      112,    0,      0,      0,              STATIC,     "__cdecl")
xx(FASTCALL_,   113,    0,      0,      0,              STATIC,     "__fastcall")
xx(INLINE,      114,    0,      0,      0,              STATIC,     "inline")
xx(ASM,         115,    0,      0,      0,              IF,         "__asm")
xx(TRY,         116,    0,      0,      0,              IF,         "__try")
xx(EXCEPT,      117,    0,      0,      0,              IF,         "__except")
xx(FINALLY,     118,    0,      0,      0,              IF,         "__finally")
xx(LEAVE,       119,    0,      0,      0,              IF,         "__leave")
yy(0,           120,    0,      0,      0,              0,          0)
yy(0,           121,    0,      0,      0,              0,          "const volatile restrict")  /* CONST_+VOLATILE_+RESTRICT_ */
yy(0,           122,    0,      0,      0,              0,          0)
yy(0,           123,    0,      0,      0,              IF,         "{")
yy(0,           124,    6,      BOR,    bit_tree,       '|',        "|")
yy(0,           125,    0,      0,      0,              '}',        "}")
yy(0,           126,    0,      BCOM,   0,              ID,         "~")
xx(EOI,         127,    0,      0,      0,              EOI,        "end of input")
#undef xx
#undef yy
