#
# $Id: Makefile,v 1.4 2007/02/27 15:59:34 druzus Exp $
#

ROOT = ../../

C_SOURCES=\
	hbfhnd.c \
	hbfopen.c \
	hbfsapi.c \
	hbgete.c \
	hbhash.c \
	hbstr.c \
	hbdate.c \
	hbtrace.c \
	hbver.c \
	hbarch.c \
	reserved.c \
	expropt1.c \
	expropt2.c \

PRG_SOURCES=\

LIBNAME=common

include $(TOP)$(ROOT)config/lib.cf
