#
# $Id: Makefile,v 1.1.1.1 2001/12/21 10:44:34 ronpinkas Exp $
#

ROOT = ../../

C_SOURCES=\
	hbfhnd.c \
	hbfsapi.c \
	hbgete.c \
	hbhash.c \
	hbstr.c \
	hbtrace.c \
	hbver.c \
	reserved.c \
	expropt1.c \
	expropt2.c \

PRG_SOURCES=\

LIBNAME=common

include $(TOP)$(ROOT)config/lib.cf
