#
# $Id: Makefile,v 1.5 2007/12/29 12:50:54 likewolf Exp $
#

ROOT = ../../

C_SOURCES=\
	hbfopen.c \
	hbfsapi.c \
	hbgete.c \
	hbhash.c \
	hbstr.c \
	hbdate.c \
	hbtrace.c \
	hbver.c \
	hbarch.c \
	reserved.c \
	expropt1.c \
	expropt2.c \

PRG_SOURCES=\

LIBNAME=common

include $(TOP)$(ROOT)config/lib.cf
