#
# $Id: Makefile,v 1.3 2004/11/01 04:30:15 druzus Exp $
#

ROOT = ../../

C_SOURCES= \
	hbppcore.c \
	hbppcomp.c \
	hbppcalc.c \
	hbpptbl.c  \
	pragma.c   \

C_MAIN=hbpp.c

LIBS=\
	common \

include $(TOP)$(ROOT)config/bin.cf
