#
# $Id: Makefile,v 1.2 2004/10/31 13:15:47 druzus Exp $
#

ROOT = ../../

vpath %.c $(TOP)$(ROOT)source/compiler/

C_SOURCES=calconst.c

C_MAIN=hbpp.c

LIBS=\
	pp \
	common \

include $(TOP)$(ROOT)config/bin.cf
