#
# $Id: Makefile,v 1.1.1.1 2001/12/21 10:44:58 ronpinkas Exp $
#

ROOT = ../../

C_SOURCES=$(TOP)$(ROOT)source/compiler/calconst.c

C_MAIN=hbpp.c

LIBS=\
	pp \
	common \

include $(TOP)$(ROOT)config/bin.cf
