#
# $Id: Makefile,v 1.1 2004/08/22 17:20:14 lf_sfnet Exp $
#

ROOT = ../../../

C_SOURCES=\
	../hvm.c \
	../fm.c \
	../classes.c 

LIBNAME=optcon

include $(TOP)$(ROOT)config/lib.cf

CFLAGS += -DHB_OPT_CON
