#
# $Id: Makefile,v 1.2 2004/09/12 15:37:33 lf_sfnet Exp $
#

vpath %.c ../

ROOT = ../../../

C_SOURCES=\
	hvm.c \
	fm.c \
	classes.c 

LIBNAME=optcon

include $(TOP)$(ROOT)config/lib.cf

CFLAGS += -DHB_OPT_CON
