#
# $Id$
#

ROOT = ../../

PRG_SOURCES=\
	blddbf.prg \
	sitesvr.prg \
	
PRG_MAIN=sitesvr.prg 

LIBS=\
	debug \
	vmmt \
	rtlmt \
	lang \
	rddmt \
	dbfntxmt \
	dbfdbt \
	rtlmt \
	vmmt \
	macro \
	ppmt \
	common \
	

include $(TOP)$(ROOT)config/bin.cf
