#
# $Id: Makefile,v 1.6 2003/02/12 11:23:30 jonnymind Exp $
#

ROOT = ../../

PRG_SOURCES=\
	blddbf.prg \
	sitesvr.prg \
	
PRG_MAIN=sitesvr.prg 

LIBS=\
	debug \
	vmmt \
	rtlmt \
	lang \
	rddmt \
	rtlmt \
	vmmt \
	macro \
	ppmt \
	common \

include $(TOP)$(ROOT)config/bin.cf
