#
# $Id: Makefile,v 1.2 2003/01/04 13:14:09 jonnymind Exp $
#

ROOT = ../../

PRG_SOURCES=\
	blddbf.prg \
	sitesrv.prg \
	
PRG_MAIN=sitesrv.prg 

LIBS=\
	debug \
	vmmt \
	rtlmt \
	lang \
	rddmt \
	rtlmt \
	vmmt \
	macro \
	pp \
	common \
   pthread \

include $(TOP)$(ROOT)config/bin.cf
