#
# $Id$
#

ROOT = ../../

C_SOURCES = \
   inetssl.c \

PRG_SOURCES= \
	httpcln.prg \
	popcln.prg \
	mail.prg \
	client.prg \
   smtpcln.prg \
   sendmail.prg 

LIBNAME=tipssl

include $(TOP)$(ROOT)config/lib.cf
