#
# $Id: Makefile,v 1.7 2007/05/11 16:30:46 hazi01 Exp $
#

ROOT = ../../

C_SOURCES = \
   inetssl.c \

PRG_SOURCES= \
	httpcln.prg \
	popcln.prg \
	mail.prg \
	client.prg \
   smtpcln.prg \
   sendmail.prg 

LIBNAME=tipssl

include $(TOP)$(ROOT)config/lib.cf
