##################################
# $Id$
#
# Makefile for FreeImage library
#

TARGET=libfi.a

PRGFLAGS=-I../include
CFLAGS+=-I../include
TGD_INSTALL=../lib

CSOURCES=fi_wrp.c

include ../Rules.make
