##################################
# $Id: Makefile,v 1.1 2005/10/24 13:17:10 fsgiudice Exp $
#
# Makefile for FreeImage library
#

TARGET=libfi.a

PRGFLAGS=-I../include
CFLAGS+=-I../include
TGD_INSTALL=../lib

CSOURCES=fi_wrp.c

include ../Rules.make
