#
# $Id: Makefile,v 1.24 2000/08/09 10:05:20 lculik Exp $
#

ifeq ($(HB_MAIN),)
    HB_MAIN = std
endif

ROOT = ../../

PRG_SOURCES=\
	hbdoc.prg \
	genos2.prg \
	gentrf.prg \
	genng.prg \
	genhtm.prg \
    genchm.prg \
	genrtf.prg \
	genhpc.prg \
	genasc.prg \
	html.prg \
	ng.prg \
	os2.prg \
	rtf.prg \
	troff.prg \
	fclass1.prg \
	ffile1.prg \
	ft_funcs.prg \

PRG_MAIN=hbdoc.prg

LIBS=\
	debug \
	vm \
	rtl \
	rdd \
	rtl \
	vm \
	macro \
	pp \
	lang \
	common \

include $(TOP)$(ROOT)config/bin.cf

